/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._member;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.regex.Pattern;
import malgnsoft.json.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _join__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    

//request.setCharacterEncoding("utf-8");

final String BUILDVERSION = "24.02.01";

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(RuntimeException re) {
	m.errorLog("Overflow file size. - " + re.getMessage(), re);
	return;
}
catch(Exception ex) {
	m.errorLog("Overflow file size. - " + ex.getMessage(), ex);
	return;
}

SiteDao Site = new SiteDao(); //Site.clear();
DataSet siteinfo = Site.getSiteInfo(request.getServerName());
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("status") || "".equals(siteinfo.s("doc_root"))) {
	//m.jsReplace("about:blank", "top");
	return;
}

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//CSAP \uc18c\uc15c \ub85c\uadf8\uc778 \uc0ac\uc6a9 \uc548\ud568
siteinfo.put("oauth_vendor", "");
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 1\uc2dc\uac04
siteinfo.put("session_hour", 1);
//\uacb0\uc81c\ud398\uc774\uc9c0 \uc548\ub0b4 \ubb38\uad6c
String allowTags = "a,b,br,cite,code,dd,dl,dt,div,em,i,li,ol,p,pre,q,small,span,strike,strong,sub,sup,u,ul,article,aside,details,div,dt,figcaption,footer,form,fieldset,header,hgroup,html,main,nav,section,summary,body,p,dl,multicol,dd,figure,address,center,blockquote,h1,h2,h3,h4,h5,h6,listing,xmp,pre,plaintext,menu,dir,ul,ol,li,hr,table,tbody,thead,tfoot,th,tr,td,caption,textarea,img,input,textarea,hr,iframe,video,audio";
String allowRegexr = "<(\\/?)(?!.*" + Malgn.replace(allowTags, ",", "[ >]|.*") + "[ >])([^>]*)>";
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));
boolean isDevServer = -1 < request.getServerName().indexOf("politech.malgn.co.kr");
String webUrl = request.getScheme() + "://" + request.getServerName();
int port = request.getServerPort();
if(port != 80 && port != 443) webUrl += ":" + port;
String dataDir = siteinfo.s("doc_root") + "/data";
String tplRoot = siteinfo.s("doc_root") + "/html";
f.dataDir = dataDir;
m.dataDir = dataDir;
m.dataUrl = Config.getDataUrl();

if(!"".equals(siteinfo.s("logo"))) siteinfo.put("logo_url", m.getUploadUrl(siteinfo.s("logo")));
else siteinfo.put("logo_url", "/common/images/default/malgn_logo.jpg");

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr();
if(!"".equals(siteinfo.s("allow_ip_user")) && !Site.checkIP(userIp, siteinfo.s("allow_ip_user"))) {
	m.redirect("/main/guide.jsp");
	return;
}

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/Users/kyounghokim/IdeaProjects/MalgnLMS/public_html/html");

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String loginMethod = "";
String userName = "";
String userEmail = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
int userGroupDisc = 0;
//String aloginYn = "";
String userSessionId = "";
boolean userB2BBlock = false;
String userB2BName = "";
String userB2BFile = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean isRespWeb = (5 <= siteinfo.i("skin_cd"));
boolean isGoMobile = !isRespWeb && m.isMobile();
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));

SessionDao mSession = new SessionDao(request, response);

DataSet auth2Info = Config.getDataSet("//config/userAuth2");
auth2Info.next();

Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "MLMS14" + siteId + "7";
if(0 < siteinfo.i("session_hour")) auth.setValidTime(siteinfo.i("session_hour") * 3600);
if(auth.isValid()) {
	userId = auth.getInt("ID");
	loginId = auth.getString("LOGINID");
	loginMethod = auth.getString("LOGINMETHOD");
	userName = auth.getString("NAME");
	userEmail = auth.getString("EMAIL");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	userGroupDisc = !"null".equals(auth.getString("GROUPS_DISC")) ? m.parseInt(auth.getString("GROUPS_DISC")) : 0;
	//aloginYn = auth.getString("ALOGIN_YN");
	userSessionId = auth.getString("SESSIONID");
	userB2BName = auth.getString("B2BNAME");
	userB2BFile = auth.getString("B2BFILE");
	if(userGroups != null) {
		if(-1 < userGroups.indexOf(",")) for(String userGroupId : m.split(",", userGroups)) p.setVar("SYS_USERGROUP_" + userGroupId, true);
		else p.setVar("SYS_USERGROUP_" + userGroups, true);
	}

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if("direct".equals(loginMethod)
		&& "Y".equals(auth2Info.s("auth2Yn"))
		&& !"Y".equals(auth.getString("USER_AUTH2_YN"))
		&& "Y".equals(auth.getString("DEPT_AUTH2_YN")) //\uad00\ub9ac\uc790\ub2e8-\ud68c\uc6d0\uc18c\uc18d\uad00\ub9ac\uc5d0\uc11c 2\ucc28\uc778\uc99d\uc124\uc815 \uc5ec\ubd80 Y/N	 20230126
		//&& !"".equals(auth.getString("USER_AUTH2_TYPE"))
		//&& !"malgn".equals(loginId)
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/auth2.jsp?returl=" + Malgn.urlencode(m.getThisURI()), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/logout.jsp");
		return;
	}

	if(
		(
			(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) //\uc0dd\ub144\uc6d4\uc77c
			|| (1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) //\uc131\ubcc4
			|| (1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) //\ud734\ub300\uc804\ud654\ubc88\ud638
			|| ("".equals(auth.getString("NAME"))) //\uc131\uba85
			|| ("".equals(auth.getString("EMAIL"))) //\uc774\uba54\uc77c
		)
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/member/privacy_agree.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_verify.jsp")
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		int tut = m.getUnixTime();
		String tek = m.encrypt(tut + "|" + loginId + "|7B1F83A608723CEDDFA9AED338FC796C", "SHA-256");
		String noInfoString = "";

		if(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) noInfoString = "\uc0dd\ub144\uc6d4\uc77c";
		else if(1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) noInfoString = "\uc131\ubcc4";
		else if(1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) noInfoString = "\ud734\ub300\uc804\ud654\ubc88\ud638";
		else if("".equals(auth.getString("NAME"))) noInfoString = "\uc131\uba85";
		else if("".equals(auth.getString("EMAIL"))) noInfoString = "\uc774\uba54\uc77c";
		m.jsAlert("\ud68c\uc6d0 \ud544\uc218 \uc815\ubcf4 [" + noInfoString + "](\uc774)\uac00 \ub204\ub77d\ub418\uc5b4\\n\uc218\uc815\ud398\uc774\uc9c0\ub85c \uc774\ub3d9\ud569\ub2c8\ub2e4.");
		m.jsReplace("/mypage/modify.jsp?ek=" + tek + "&ut=" + tut);
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

	p.setVar("login_block", true);
} else {
	p.setVar("login_block", false);

	if(siteinfo.b("close_yn")) {
		boolean isNeedLogin = true;
		String[] exceptPages = m.split("|", siteinfo.s("close_except"));

		if(-1 < request.getRequestURI().indexOf("/member/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/find.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/alogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin_input.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/sysop_slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/main/site_cache.jsp")
			|| -1 < request.getRequestURI().indexOf("/mobile/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate_course.jsp")
			|| -1 < request.getRequestURI().indexOf("/kollus/check_api.jsp")
			|| -1 < request.getRequestURI().indexOf("/common/")
			|| -1 < request.getRequestURI().indexOf("/api/auto_send.jsp")
		) {
			isNeedLogin = false;
		} else if(!"".equals(siteinfo.s("close_except"))) {
			for(int i = 0; i < exceptPages.length; i++) {
				if(-1 < request.getRequestURI().indexOf(exceptPages[i])) { isNeedLogin = false; continue; }
			}
		}

		if(isNeedLogin) {
			m.redirect(!isGoMobile ? auth.loginURL : "/mobile/login.jsp");
			return;
		}
	}
}

userB2BBlock = !"".equals(userB2BName) && null != userB2BName;
p.setVar("SYS_HTTPHOST", request.getServerName());
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERID", userId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SYS_DEPTID", userDeptId);
p.setVar("SYS_GROUP_DISC", userGroupDisc);
p.setVar("SYS_B2BBLOCK", userB2BBlock);
p.setVar("SYS_B2BNAME", userB2BName);
p.setVar("SYS_B2BFILE", userB2BFile);
p.setVar("SYS_PAGE_URL", request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : ""));
p.setVar("SYS_TITLE", siteinfo.s("site_nm"));
p.setVar("webUrl", webUrl);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("CURR_DATE", m.time("yyyyMMdd"));
p.setVar("SYS_EK", m.encrypt(loginId + siteinfo.s("sso_key") + m.time("yyyyMMdd"), "SHA-256"));
p.setVar("IS_RESP_WEB", isRespWeb);
p.setVar("IS_MOBILE", m.isMobile());
p.setVar("IS_GO_MOBILE", isGoMobile);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);
p.setVar("script", siteinfo.s("header_script"));

for(int IndexSkin = 1; IndexSkin < 5; IndexSkin++) {
	p.setVar("SKIN_LT_" + IndexSkin, siteinfo.i("skin_cd") < IndexSkin);
	p.setVar("SKIN_LTE_" + IndexSkin, siteinfo.i("skin_cd") <= IndexSkin);
	p.setVar("SKIN_GT_" + IndexSkin, siteinfo.i("skin_cd") > IndexSkin);
	p.setVar("SKIN_GTE_" + IndexSkin, siteinfo.i("skin_cd") >= IndexSkin);
}

MenuDao Menu = new MenuDao(p, sysLocale);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && !siteinfo.b("duplication_yn") && !UserSession.isValid(userSessionId, userId)) {
	if(request.getRequestURI().indexOf("/member/logout.jsp") == -1 && request.getRequestURI().indexOf("/mobile/logout.jsp") == -1) {
		m.jsAlert(_message.get("alert.common.logout_session"));
		if(request.getRequestURI().indexOf("/mobile/") != -1) m.jsReplace("/mobile/logout.jsp?mode=session");
		else m.jsReplace("/member/logout.jsp?mode=session");
		return;
	}
}


    out.write('\n');
    

String ch = "member";

String sslDomain = request.getServerName().indexOf(".malgn.co.kr") > 0 ? "ssl.malgn.co.kr" : "ssl.malgnlms.com";
boolean isSSL = "https".equals(request.getScheme()) && sslDomain.equals(request.getServerName()) && !"".equals(f.get("domain"));

if(siteinfo.b("ssl_yn")) {
	sslDomain = siteinfo.s("domain");
	isSSL = false;
}

//if("edu.kuca.kr".equals(f.get("domain"))) m.js("try { console.log(\"a - " + isSSL + " / " + siteinfo.i("id") + " / " + siteinfo.s("domain") + "\"); } catch {}");
if(isSSL) {
	//Site.remove(f.get("domain"));
	siteinfo = Site.getSiteInfo(f.get("domain"));
	if("".equals(siteinfo.s("doc_root"))) { m.jsError(_message.get("alert.site.nodata")); return; }
	siteId = siteinfo.i("id");
	
	SiteConfig = new SiteConfigDao(siteinfo.i("id"));

	mSession.put("id", f.get("session_id"));
}
p.setVar("SSL_DOMAIN", sslDomain);


    

//\ub85c\uadf8\uc778
if(userId != 0) { m.redirect("../main/index.jsp"); return; }

//SSO
if(siteinfo.b("sso_yn") && !"".equals(siteinfo.s("sso_url"))) {
	String url = siteinfo.s("sso_url") + ( siteinfo.s("sso_url").indexOf("?") > -1 ?  "&mode=join" : "?mode=join");
	m.redirect(url);
	return;
}

//\uc81c\ud55c
String ek = m.rs("ek");
String key = m.rs("k");
if(!ek.equals(m.encrypt(key + "_AGREE"))) { m.jsError(_message.get("alert.common.abnormal_access")); return; }

//\uc81c\ud55c
if(0 > siteinfo.i("join_status")) {
	m.jsAlert(_message.get("alert.member.stop_join"));
	m.jsReplace("/");
	return;
}

//\ubcc0\uc218
String marketYn = "N";
String emailYn = "N";
String smsYn = "N";

//\ub9c8\ucf00\ud305\ub3d9\uc758\uc5ec\ubd80
marketYn = "Y".equals(m.getCookie("market_yn")) ? "Y" : "N";
emailYn = "Y".equals(m.getCookie("email_yn")) ? "Y" : "N";
smsYn = "Y".equals(m.getCookie("sms_yn")) ? "Y" : "N";



//\uc815\ubcf4-\uc0ac\uc774\ud2b8\uc124\uc815
DataSet siteconfig = SiteConfig.getArr(new String[] {"join_", "modify_", "user_etc_", "ktalk_"});

//\uac1d\uccb4
UserDao user = new UserDao(); user.setInsertIgnore(true);
UserDeptDao userDept = new UserDeptDao();
AgreementLogDao agreementLog = new AgreementLogDao(p, siteId);
MailDao mail = new MailDao();
SmsTemplateDao smsTemplate = new SmsTemplateDao(siteId);
FileDao file = new FileDao();
MCal mcal = new MCal(); mcal.yearRange = 50;

SmsDao sms = new SmsDao(siteId);
if(siteinfo.b("sms_yn")) sms.setAccount(siteinfo.s("sms_id"), siteinfo.s("sms_pw"));
KtalkDao ktalk = new KtalkDao(siteId);
if("Y".equals(siteconfig.s("ktalk_yn"))) ktalk.setAccount(siteinfo.s("sms_id"), siteinfo.s("sms_pw"), siteconfig.s("ktalk_sender_key"));
KtalkTemplateDao ktalkTemplate = new KtalkTemplateDao(siteId);

//\uc774\ub3d9-\uac00\uc785\uc124\uc815\uc0ac\uc6a9\uc5ec\ubd80
if("Y".equals(siteconfig.s("join_config_yn"))) {
	m.redirect("join2.jsp?" + m.qs());
	return;
}

//\ubcc0\uc218-\ubbf8\ub9ac\uc785\ub825\ub41c\uc815\ubcf4
DataSet ainfo = new DataSet();
boolean loginIdBlock = false;
boolean userNmBlock = false;
boolean passwdBlock = false;
boolean birthdayBlock = false;
boolean genderBlock = false;
boolean emailBlock = false;
boolean mobileBlock = false;
String pattern = "(\\d{3})(\\d{3,4})(\\d{4})";

//\ud0c0\uc0ac\uacc4\uc815\ub85c\uadf8\uc778
boolean isOAuth = "oauth".equals(mSession.s("join_method"));
if(isOAuth) {
	DataSet temp = new DataSet();
	try { temp = Json.decode(mSession.s("join_data")); }
	catch(JSONException jsone) { m.errorLog("JSONException : " + jsone.getMessage(), jsone); m.jsError(_message.get("alert.common.error_view")); return; }
	catch(Exception e) { m.errorLog("Exception : " + e.getMessage(), e); m.jsError(_message.get("alert.common.error_view")); return; }
	if(!temp.next()) { m.jsError(_message.get("alert.common.error_view")); return; }

	ainfo.addRow();
	ainfo.put("login_id", mSession.s("join_vendor") + "_" + temp.s("id"));
	ainfo.put("user_nm", temp.s("name"));
	loginIdBlock = true;
	userNmBlock = true;
	passwdBlock = true;

	if("naver".equals(mSession.s("join_vendor"))) {
		ainfo.put("email", temp.s("email"));
		ainfo.put("gender", "M".equals(temp.s("gender")) ? "1" : "2");
		ainfo.put("gender_conv", m.getValue(ainfo.s("gender"), user.gendersMsg));
		emailBlock = true;
		genderBlock = true;
	} else if("facebook".equals(mSession.s("join_vendor"))
			|| "google".equals(mSession.s("join_vendor"))
			|| "kakao".equals(mSession.s("join_vendor"))) {
		ainfo.put("email", temp.s("email"));
		emailBlock = true;
	//} else if("sba".equals(mSession.s("join_vendor"))) {
	//	userNmBlock = false;
	}

	//\uc81c\ud55c
	if(isOAuth && 0 < user.findCount("login_id = '" + ainfo.s("login_id") + "' AND site_id = " + siteId + "")) {
		m.jsError(_message.get("alert.member.used_oauth"));
		return;
	}
}

//\ubcf8\uc778\uc778\uc99d-NICE
boolean isAuth = (siteinfo.b("auth_yn") || siteinfo.b("ipin_yn"));
if(isAuth) {
	//\ud0c0\uc0ac\uacc4\uc815\ub85c\uadf8\uc778\uacfc \ub3d9\uc2dc \uc801\uc6a9\uc2dc addRow\ud558\uba74 \ud0c0\uc0ac\uacc4\uc815\ub85c\uadf8\uc778\uc815\ubcf4\uac00 \ub0a0\uc544\uac10.
	if(!isOAuth) ainfo.addRow();

	//\ud0c0\uc0ac\uacc4\uc815\ub85c\uadf8\uc778\uc5d0\uc11c \uc815\ubcf4\uac00 \uc788\ub294\ub370 \ubcf8\uc778\uc778\uc99d\uc5d0\uc11c \ube48 \uac12\uc774 \ub4e4\uc5b4\uc62c \ub54c \ube48 \uac12\uc73c\ub85c \ub36e\uc5b4\uc4f0\ub294\uac78 \ubc29\uc9c0.
	//\ubcf8\uc778\uc778\uc99d\uc5d0\uc11c \ub4e4\uc5b4\uc624\ub294 \uac12\uc774 \ube48 \uac12\uc774 \uc544\ub2c8\uba74 \ub354 \uc2e0\ub8b0\uc131\uc774 \ub192\uc740 \ubcf8\uc778\uc778\uc99d \uc815\ubcf4\ub85c \ub36e\uc5b4\uc500
	if(!"".equals(mSession.s("sName"))) { ainfo.put("user_nm", mSession.s("sName")); userNmBlock = true; }
	if(!"".equals(mSession.s("sGenderCode"))) { ainfo.put("gender_code", mSession.s("sGenderCode")); genderBlock = true; }
	if(!"".equals(mSession.s("sBirthDate"))) { ainfo.put("birthday", mSession.s("sBirthDate")); birthdayBlock = true; }
	if(!"".equals(mSession.s("sMobileNo"))) { ainfo.put("mobile", mSession.s("sMobileNo")); mobileBlock = true; }
	ainfo.put("dupinfo", mSession.s("sDupInfo")); //\uc911\ubcf5\uac00\uc785 \ud655\uc778\uac12 (DI - 64 byte \uace0\uc720\uac12)
	ainfo.put("national_info", mSession.s("sNationalInfo")); //\ub0b4/\uc678\uad6d\uc778 \uc815\ubcf4 (\uac1c\ubc1c \uac00\uc774\ub4dc \ucc38\uc870)

	//\ud3ec\ub9f7\ud305
	ainfo.put("gender", "0".equals(ainfo.s("gender_code")) ? "2" : ainfo.s("gender_code"));
	ainfo.put("gender_conv", m.getValue(ainfo.s("gender"), user.gendersMsg));
	ainfo.put("birthday_conv", m.time(_message.get("format.date.local"), ainfo.s("birthday")));
	ainfo.put("mobile_conv", ainfo.s("mobile").replaceAll(pattern, "$1-$2-$3"));

	//\uc81c\ud55c
	if("".equals(ainfo.s("dupinfo"))) { m.jsAlert(_message.get("alert.auth.nodupinfo")); return; }
	if(0 < user.findCount("dupinfo = '" + ainfo.s("dupinfo") + "' AND status != -1")) {
		if(!"125.129.123.211".equals(userIp)) {
			m.jsAlert(_message.get("alert.member.used_dupinfo"));
			m.jsReplace("../" + (!isGoMobile ? "member" : "mobile") + "/login.jsp");
		} else {
			out.print(_message.get("alert.member.used_dupinfo") + "<br>" + ainfo.s("dupinfo"));
		}
		return;
	}
}

//\ucc98\ub9ac
if("CHECK".equals(m.rs("mode"))) {
	String value = m.rs("v");
	if("".equals(value)) { return; }

	//\uc911\ubcf5\uc5ec\ubd80
	if(0 < user.findCount("login_id = ? AND site_id = ?", new Object[] {value.toLowerCase(), siteId})) {
		out.print("<span class='bad'>" + _message.get("alert.member.used_id") + "</span>");
	} else {
		out.print("<span class='good'>\uc0ac\uc6a9\ud560 \uc218 \uc788\ub294 \ub85c\uadf8\uc778\uc544\uc774\ub514\uc785\ub2c8\ub2e4.</span>");
	}
	return;
} else if("EMAIL".equals(m.rs("mode"))) {
	//\ubcc0\uc218
	String email = f.get("e").toLowerCase();

	//\uc81c\ud55c
	if(0 < user.findCount("email = ? AND site_id = ? AND user_kind = 'U' AND status = 1", new Object[] {email, siteId})) { m.jsAlert(_message.get("alert.member.used_email_detail", new String[] {"email=>" + email})); return; }

	//\ubc1c\uc1a1
	int authNo = m.getRandInt(123456, 864198);
	p.setVar("auth_no", authNo + "");
	mail.send(siteinfo, email, "findpw_authno", p);

	//\uc138\uc158
	mSession.put("JOIN_EMAIL", email);
	mSession.put("JOIN_AUTHNO", "" + authNo);
	mSession.put("JOIN_SITEID", "" + siteId);
	mSession.put("JOIN_EMAIL_VERIFIED", "");
	mSession.put("JOIN_EMAIL_VERIFYDATE", "");
	mSession.save();

	m.jsAlert(_message.get("alert.member.find.authno_to_email"));
	m.js("try { parent.setVerify(); } catch(e) {}");
	return;
} else if("VERIFY".equals(m.rs("mode"))) {
	//\ubcc0\uc218
	String email = f.get("e").toLowerCase();
	String code = f.get("c");

	//\uc81c\ud55c-\uc774\uba54\uc77c
	if(0 < user.findCount("email = ? AND site_id = ? AND user_kind = 'U' AND status = 1", new Object[] {email, siteId})) { m.jsAlert(_message.get("alert.member.used_email_detail", new String[] {"email=>" + email})); return; }

	//\uc81c\ud55c-\uc778\uc99d\ubc88\ud638
	String authEmail = mSession.s("JOIN_EMAIL");
	String authNo = mSession.s("JOIN_AUTHNO");
	int authSiteId = mSession.i("JOIN_SITEID");

	if(!authEmail.equals(email) || !authNo.equals(code) || siteId != authSiteId) {
		m.jsAlert(_message.get("alert.member.email_fail"));
		return;
	}

	//\uc138\uc158
	mSession.put("JOIN_EMAIL_VERIFIED", email);
	mSession.put("JOIN_EMAIL_VERIFYDATE", m.time("yyyyMMdd"));
	mSession.save();

	m.jsAlert(_message.get("alert.member.email_success"));
	m.js(""
		+ " try { "
			+ " parent.setSuccess(); "
			+ " parent.document.forms['form1']['verify_email_yn'].value = 'Y'; "
		+ " } catch(e) {} "
	);
	return;
}

//\ud3fc\uccb4\ud06c
if(!loginIdBlock) f.addElement("login_id", null, "hname:'\ub85c\uadf8\uc778\uc544\uc774\ub514', required:'Y', pattern:'^[a-zA-Z]{1}[a-zA-Z0-9]{1,19}$', errmsg:'\uc601\ubb38\uc73c\ub85c \uc2dc\uc791\ud558\ub294 2-20\uc790 \uc601\ubb38, \uc22b\uc790 \uc870\ud569\uc744 \uc785\ub825\ud558\uc138\uc694.'");
if(!userNmBlock) f.addElement("user_nm", null, "hname:'\uc131\uba85', required:'Y'");
if(!passwdBlock) f.addElement("passwd", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y', minbyte:'9', match:'passwd2'");
if(!passwdBlock) f.addElement("passwd2", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y', minbyte:'9'");
if(!birthdayBlock) f.addElement("birthday_year", null, "hname:'\uc0dd\ub144\uc6d4\uc77c(\ub144\ub3c4)'" + (1 < siteconfig.i("join_birthday_status") ? ", required:'Y'" : ""));
if(!birthdayBlock) f.addElement("birthday_month", null, "hname:'\uc0dd\ub144\uc6d4\uc77c(\uc6d4)'" + (1 < siteconfig.i("join_birthday_status") ? ", required:'Y'" : ""));
if(!birthdayBlock) f.addElement("birthday_day", null, "hname:'\uc0dd\ub144\uc6d4\uc77c(\uc77c)'" + (1 < siteconfig.i("join_birthday_status") ? ", required:'Y'" : ""));
//f.addElement("dept_id", siteinfo.s("dept_id"), "hname:'\ud68c\uc6d0\uc18c\uc18d'");
f.addElement("dept_id", null, "hname:'\ud68c\uc6d0\uc18c\uc18d'");
if(!genderBlock) f.addElement("gender", null, "hname:'\uc131\ubcc4'" + (1 < siteconfig.i("join_gender_status") ? ", required:'Y'" : ""));
if(!emailBlock) f.addElement("email1", null, "hname:'\uc774\uba54\uc77c', required:'Y', glue:'email2'");
if(!emailBlock) f.addElement("email2", null, "hname:'\uc774\uba54\uc77c', required:'Y'");
if(!mobileBlock) f.addElement("mobile1", null, "hname:'\ud734\ub300\ud3f0\ubc88\ud638'" + (1 < siteconfig.i("join_mobile_status") ? ", required:'Y'" : ""));
if(!mobileBlock) f.addElement("mobile2", null, "hname:'\ud734\ub300\ud3f0\ubc88\ud638'" + (1 < siteconfig.i("join_mobile_status") ? ", required:'Y'" : ""));
if(!mobileBlock) f.addElement("mobile3", null, "hname:'\ud734\ub300\ud3f0\ubc88\ud638'" + (1 < siteconfig.i("join_mobile_status") ? ", required:'Y'" : ""));
f.addElement("zipcode", null, "hname:'\uc6b0\ud3b8\ubc88\ud638'");
f.addElement("addr", null, "hname:'\uad6c \uc8fc\uc18c'");
f.addElement("new_addr", null, "hname:'\ub3c4\ub85c\uba85 \uc8fc\uc18c'");
f.addElement("addr_dtl", null, "hname:'\uc0c1\uc138\uc8fc\uc18c'");
f.addElement("user_file", null, "hname:'\uc0ac\uc9c4'");
f.addElement("user_file_k", null, "hname:'\uc0ac\uc9c4'");
f.addElement("user_file_ek", null, "hname:'\uc0ac\uc9c4'");
f.addElement("email_yn", "Y", "hname:'\uc774\uba54\uc77c\uc218\uc2e0\ub3d9\uc758'");
f.addElement("sms_yn", "Y", "hname:'SMS\uc218\uc2e0\ub3d9\uc758'");

//\uac00\uc785
if(m.isPost() && f.validate()) {

	//\uc81c\ud55c
	if(!isOAuth && 0 < user.findCount("login_id = ? AND site_id = ?", new Object[] {f.get("login_id").toLowerCase(), siteId})) {
		m.jsAlert(_message.get("alert.member.used_id"));
		m.js("parent.resetPassword();");
		return;
	}

	//\uc81c\ud55c-\ube44\ubc00\ubc88\ud638
	if(!passwdBlock && !f.get("passwd").matches("^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[\\W_]).{9,}$")) {
		m.jsAlert(_message.get("alert.member.rule_password"));
		return;
	}

	String email = (emailBlock ? ainfo.s("email") : f.glue("@", "email1,email2").toLowerCase());
	if(!"@".equals(email)) {
		if(!emailBlock && !mail.isMail(email)) {
			m.jsAlert(_message.get("alert.member.unvalid_email"));
			m.js("parent.resetPassword();");
			return;
		}

		if(!emailBlock && 0 < user.findCount("email = ? AND site_id = ? AND user_kind = 'U' AND status = 1", new Object[] {email, siteId})) {
			m.jsAlert(_message.get("alert.member.used_email_detail", new String[] {"email=>" + email}));
			m.js("parent.resetPassword();");
			return;
		}
	} else {
		email = "";
	}

	int newId = user.getSequence();
//	String emailYn = f.get("email_yn", "N");
//	String smsYn = f.get("sms_yn", "N");
	String passwd = passwdBlock ? "" : f.get("passwd");
	if(64 > passwd.length()) passwd = m.encrypt(passwd, "SHA-256");

	//\uc81c\ud55c-\ud734\ub300\ud3f0
	String mobile = "";
	if(!mobileBlock) {
		if(!"Y".equals(SiteConfig.s("foreign_yn"))) {
			if(!"".equals(f.get("mobile2")) || !"".equals(f.get("mobile3"))) {
				mobile = f.get("mobile1") + f.get("mobile2") + f.get("mobile3");
				if(!Pattern.matches(pattern, mobile)) {
					m.jsAlert(_message.get("alert.member.unvalid_mobile"));
					m.js("parent.resetPassword();");
					return;
				}
				mobile = mobile.replaceAll(pattern, "$1-$2-$3");
			}
		} else {
			mobile = f.get("mobile1");
		}
	} else {
		mobile = ainfo.s("mobile").replaceAll(pattern, "$1-$2-$3");
	}

	//\uc778\uc99d-\uc774\uba54\uc77c
	if("Y".equals(siteinfo.s("verify_email_yn"))) {
		if(!email.equals(mSession.s("JOIN_EMAIL_VERIFIED"))
			|| !m.time("yyyyMMdd").equals(mSession.s("JOIN_EMAIL_VERIFYDATE"))
			|| !"Y".equals(f.get("verify_email_yn", "N"))) {
			m.jsAlert(_message.get("alert.member.email_expired"));
			m.js("parent.resetPassword();");
			return;
		}
	}

	user.item("id", newId);
	user.item("site_id", siteId);
	user.item("login_id", loginIdBlock ? ainfo.s("login_id") : f.get("login_id").toLowerCase());
	user.item("user_nm", userNmBlock ? ainfo.s("user_nm") : f.get("user_nm"));
	user.item("passwd", passwd);
	user.item("user_kind", "U");
	user.item("email", email);
	user.item("gender", genderBlock ? ainfo.s("gender") : f.getInt("gender", 1));
	user.item("birthday", birthdayBlock ? ainfo.s("birthday") : f.get("birthday_year") + f.get("birthday_month") + f.get("birthday_day"));

	user.item("mobile", mobile);
	user.item("zipcode", f.get("zipcode"));
	user.item("addr", f.get("addr"));
	user.item("new_addr", f.get("new_addr"));
	user.item("addr_dtl", f.get("addr_dtl"));
	user.item("dept_id", f.getInt("dept_id", siteinfo.i("dept_id")));
	user.item("conn_date", "");
	user.item("etc1", f.get("etc1"));
	user.item("etc2", f.get("etc2"));
	user.item("etc3", f.get("etc3"));
	user.item("etc4", f.get("etc4"));
	user.item("etc5", f.get("etc5"));
	user.item("dupinfo", isAuth ? ainfo.s("dupinfo") : "");
	user.item("oauth_vendor", mSession.s("join_vendor"));

	//\ud30c\uc77c
	if("Y".equals(SiteConfig.s("join_userfile_yn"))) {
		int tempId = f.getInt("temp_id");
		if(0 > tempId) {
			file.item("module_id", newId);
			if(!file.update("module_id = " + tempId)) { }
		}
	}

//	user.item("email_yn", emailYn);
//	user.item("sms_yn", smsYn);
	user.item("email_yn", "Y".equals(marketYn) ? emailYn : f.get("email_yn"));
	user.item("sms_yn", "Y".equals(marketYn) ? smsYn : f.get("sms_yn"));
	user.item("privacy_yn", "Y");
	user.item("passwd_date", m.addDate("d", siteinfo.i("passwd_day"), m.time("yyyyMMdd"), "yyyyMMdd"));
	user.item("conn_date", m.time("yyyyMMddHHmmss"));
	user.item("reg_date", m.time("yyyyMMddHHmmss"));
	user.item("status", ("0".equals(siteinfo.s("join_status")) ? "0" : "1"));

	if(!user.insert()) {
		m.jsAlert(_message.get("alert.common.error_insert"));
		m.js("parent.resetPassword();");
		return;
	}

	//\uc815\ubcf4
	DataSet info = user.find("id = " + newId + "");
	if(!info.next()) { }

//	agreementLog.insertLog(siteinfo, info, "email", emailYn, "join");
//	agreementLog.insertLog(siteinfo, info, "sms", smsYn, "join");
	agreementLog.insertLog(siteinfo, info, "marketing", marketYn, "join");
	agreementLog.insertLog(siteinfo, info, "email", "Y".equals(marketYn) ? emailYn : f.get("email_yn"), "join");
	agreementLog.insertLog(siteinfo, info, "sms", "Y".equals(marketYn) ? smsYn : f.get("sms_yn"), "join");
	agreementLog.insertLog(siteinfo, info, "privacy", "Y", "join");

	//\uba54\uc77c
	info.put("reg_date_conv", m.time(_message.get("format.datetime.local")));
	p.setVar("info", info);
	mail.send(siteinfo, info, "join", p);
	if("Y".equals(siteconfig.s("ktalk_yn"))) {
		p.setVar("user_nm", info.s("user_nm"));
		ktalkTemplate.sendKtalk(siteinfo, info, "join", p);
	} else {
		smsTemplate.sendSms(siteinfo, info, "join", p);
	}

	//\uc138\uc158\ucd08\uae30\ud654
	mSession.put("join_method", "");
	mSession.put("join_vendor", "");
	mSession.put("join_vendor_nm", "");
	mSession.put("join_data", "");
	mSession.put("sName", "");
	mSession.put("sGenderCode", "");
	mSession.put("sBirthDate", "");
	mSession.put("sMobileNo", "");
	mSession.put("sDupInfo", "");
	mSession.put("sNationalInfo", "");
	mSession.save();

	if(isSSL) m.jsReplace("http://" + f.get("domain") + "/member/join_success.jsp?ek=" + ek + "&k=" + key + "&uek=" + m.encrypt(newId + "_NEWUSERID") + "&uk=" + newId, "parent");
	else m.jsReplace("join_success.jsp?ek=" + ek + "&k=" + key + "&uek=" + m.encrypt(newId + "_NEWUSERID") + "&uk=" + newId, "parent");

	return;
}

//\ucd9c\ub825
p.setLayout(!isGoMobile ? ch : "mobile");
p.setBody((!isGoMobile ? ch : "mobile") + ".join");
p.setVar("p_title", "\ud68c\uc6d0\uac00\uc785");
p.setVar("query", m.qs("mode"));
p.setVar("form_script", f.getScript());

p.setVar("ainfo", ainfo);
p.setVar("SITE_CONFIG", siteconfig);

p.setVar("is_auth", isAuth);
p.setVar("is_oauth", isOAuth);
p.setVar("login_id_block", loginIdBlock);
p.setVar("user_nm_block", userNmBlock);
p.setVar("passwd_block", passwdBlock);
p.setVar("email_block", emailBlock);
p.setVar("mobile_block", mobileBlock);
p.setVar("gender_block", genderBlock);
p.setVar("birthday_block", birthdayBlock);
p.setVar("oauth_vendor", mSession.s("join_vendor"));
p.setVar("oauth_vendor_nm", mSession.s("join_vendor_nm"));

//\ucd5c\uc0c1\uc704 \ub178\ucd9c \uc5ec\ubd80 \uccb4\ud06c
DataSet rs = userDept.getList(siteId, "U", 0);
DataSet deptList = new DataSet();
while(rs.next()) {
	if("Y".equals(rs.s("display_yn"))) deptList.addRow(rs.getRow());
}

//p.setLoop("dept_list", userDept.getList(siteId, "U", 0));
p.setLoop("dept_list", deptList);
p.setLoop("years", mcal.getYears(m.addDate("Y", -49, m.time("yyyyMMdd"), "yyyy")));
p.setLoop("months", mcal.getMonths());
p.setLoop("days", mcal.getDays());
p.setLoop("receive_yn", m.arr2loop(user.receiveYn));
p.setVar("domain", request.getServerName());
p.setVar("session_id", mSession.s("id"));
p.setVar("temp_id", m.getRandInt(-2000000, 1990000));

p.setVar("sms_yn", "Y".equals(smsYn));
p.setVar("email_yn", "Y".equals(emailYn));
p.setVar("market_yn", "Y".equals(marketYn));

p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("member/join.jsp"), -4232811014076863324L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("member/init.jsp"), 9054591303382699975L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 2912615399035486559L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\n\n".toCharArray();
  }
}
