-- 다중 영상 차시(플레이리스트) 기능 추가용 DDL
-- 상용 서버 사이드이펙트 최소화를 위해 기존 테이블/로직은 유지하고,
-- 다중 영상이 설정된 차시만 새 테이블을 타도록 설계했습니다.

-- 1) 과정-차시 테이블에 다중영상 플래그/합산시간 캐시 컬럼 추가
ALTER TABLE `LM_COURSE_LESSON`
  ADD COLUMN `MULTI_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '다중영상 차시 여부',
  ADD COLUMN `MULTI_TOTAL_TIME` int NOT NULL DEFAULT '0' COMMENT '다중영상 학습시간 합(분)',
  ADD COLUMN `MULTI_COMPLETE_TIME` int NOT NULL DEFAULT '0' COMMENT '다중영상 인정시간 합(분)';

-- 2) 차시 안에 들어가는 서브영상(레슨) 목록/순서 테이블
DROP TABLE IF EXISTS `LM_COURSE_LESSON_VIDEO`;
CREATE TABLE `LM_COURSE_LESSON_VIDEO` (
  `COURSE_ID` int NOT NULL DEFAULT '0' COMMENT '과정아이디',
  `LESSON_ID` int NOT NULL DEFAULT '0' COMMENT '차시 레슨아이디(부모)',
  `VIDEO_ID` int NOT NULL DEFAULT '0' COMMENT '서브영상 레슨아이디',
  `SORT` int NOT NULL DEFAULT '1' COMMENT '순서',
  `SITE_ID` int NOT NULL DEFAULT '-1' COMMENT '사이트아이디(참고용)',
  `REG_DATE` varchar(14) DEFAULT NULL COMMENT '등록일',
  `STATUS` int NOT NULL DEFAULT '1' COMMENT '상태',
  PRIMARY KEY (`COURSE_ID`,`LESSON_ID`,`VIDEO_ID`),
  KEY `LM_CLV_COURSE_LESSON_INDEX` (`COURSE_ID`,`LESSON_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COMMENT='과정차시-서브영상 매핑';

-- 3) 서브영상별 진도/학습시간 테이블 (기존 LM_COURSE_PROGRESS 구조 + VIDEO_ID)
DROP TABLE IF EXISTS `LM_COURSE_PROGRESS_VIDEO`;
CREATE TABLE `LM_COURSE_PROGRESS_VIDEO` (
  `COURSE_ID` int NOT NULL DEFAULT '0' COMMENT '과정아이디',
  `LESSON_ID` int NOT NULL DEFAULT '0' COMMENT '차시 레슨아이디(부모)',
  `VIDEO_ID` int NOT NULL DEFAULT '0' COMMENT '서브영상 레슨아이디',
  `CHAPTER` int DEFAULT NULL COMMENT '장',
  `COURSE_USER_ID` int NOT NULL COMMENT '수강생아이디',
  `USER_ID` int NOT NULL COMMENT '회원아이디',
  `LESSON_TYPE` varchar(2) DEFAULT NULL COMMENT '영상타입',
  `STUDY_PAGE` int DEFAULT '0' COMMENT '학습페이지 갯수',
  `STUDY_TIME` int DEFAULT '0' COMMENT '학습시간(초)',
  `CURR_PAGE` varchar(255) DEFAULT NULL COMMENT '현재페이지',
  `CURR_TIME` int DEFAULT '0' COMMENT '현재위치',
  `LAST_TIME` int DEFAULT '0' COMMENT '최대위치(초)',
  `PARAGRAPH` varchar(4000) DEFAULT NULL COMMENT '수강한절번호',
  `RATIO` decimal(11,2) DEFAULT '0.00' COMMENT '진도율',
  `COMPLETE_YN` varchar(1) DEFAULT 'N' COMMENT '완료여부',
  `COMPLETE_DATE` varchar(14) DEFAULT NULL COMMENT '완료일자',
  `VIEW_CNT` int DEFAULT '0' COMMENT '횟수',
  `LAST_DATE` varchar(14) DEFAULT NULL COMMENT '마지막수강일',
  `CHANGE_USER_ID` int DEFAULT NULL COMMENT '임의변경자',
  `REG_DATE` varchar(14) NOT NULL COMMENT '등록일',
  `STATUS` int DEFAULT '1' COMMENT '상태',
  `SITE_ID` int DEFAULT '0' COMMENT '사이트아이디',
  PRIMARY KEY (`COURSE_USER_ID`,`LESSON_ID`,`VIDEO_ID`),
  KEY `LM_CPV_COURSE_LESSON_INDEX` (`COURSE_ID`,`LESSON_ID`),
  KEY `LM_CPV_USER_INDEX` (`COURSE_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COMMENT='서브영상 진도관리';

