/*
 * JSP generated by Resin-4.0.67 (built Thu, 01 Aug 2024 10:12:42 PDT)
 */

package _jsp._api;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;
import malgnsoft.json.*;

public class _file__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;

  
  
  class MySort implements Comparator<File> {
      public int compare(File f1, File f2) {
          if (f1.getName().compareTo(f2.getName()) > 0) { return 1; }
          else if (f1.getName().compareTo(f2.getName()) < 0) { return -1; }
          return 0;
      }
  }
  

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

Malgn m = new Malgn(request, response, out);
String ip = m.getRemoteAddr();
if(!ip.startsWith("10.")) return;

Form f = new Form("form1");
try { f.setRequest(request); }
catch(Exception ex) { out.print("Overflow file size. - " + ex.getMessage()); return; }

//if(!m.isPost()) return;

String uid = f.get("uid").replace("..", "");
String mode = f.get("mode");
String folder = f.get("folder").replace("..", "");
String file = f.get("file").replace("..", "");

String dir = "/home/" + uid + "/public_html/html/" + folder;
String pnm = f.get("pnm");

if("files".equals(mode)) {
    //\ud3f4\ub354\ub0b4 \ud30c\uc77c\ubaa9\ub85d \uc870\ud68c
    DataSet list = new DataSet();
    try {
        if(new File(dir).exists()) {
            File[] files = new File(dir).listFiles();
            Arrays.sort(files, new MySort());
            int max = files.length;
            for(int i = 0; i < max; i++) {
                if(files[i].isFile()) {
                    if(!"".equals(pnm) && files[i].getName().indexOf(pnm) < 0) continue;
                    list.addRow();
                    list.put("id", "" + (i + 1));
                    list.put("name", files[i].getName());
                    list.put("path", files[i].toString());
                    list.put("length", new Long(files[i].length()));
                    list.put("time", new Long(files[i].lastModified()));
                    list.put("pname", files[i].getName().replace(".html", "").replace(".css", ""));
                }
            }
        }
    } catch(NullPointerException npe) {
        m.errorLog(npe.getMessage());
    }
    list.first();
    JSONObject jsonObject = new JSONObject();
    jsonObject.put("files", new JSONArray(list));
    out.print(jsonObject);
/*
out.print(list.serialize());
*/
    return;
}
else if("read".equals(mode)) {

    String filepath = dir + "/" + file;
    File f1 = new File(filepath);

    if(f1.exists() && f1.isFile()) {
        out.print(m.readFile(filepath));
    } else {
        JSONObject json = new JSONObject();
        json.put("error", 1);
        json.put("message", "\ud30c\uc77c\uc774 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
        out.print(json.toString());
        out.print("");
    }
    return;
}
else if("readwrite".equals(mode)) {

    String filepath = dir + "/" + file;
    File f1 = new File(filepath);

    if(f1.exists() && f1.isFile()) {
        out.print(m.readFile(filepath));
    } else {
        m.writeFile(filepath, "");
        try { Runtime.getRuntime().exec("chown -R " + uid + ":" + uid + " " + filepath); }
        catch(RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage(), re); }
        catch(Exception e) { m.errorLog("Exception : " + e.getMessage(), e); }
    }
    return;
}
else if("edit".equals(mode)) {
    f.addElement("body", null, "allowscript:'Y', allowhtml:'Y', allowiframe:'Y', allowlink:'Y', allowobject:'Y'");
    String body = f.get("body");
    String filepath = dir + "/" + file;
    File f1 = new File(filepath);

    JSONObject json = new JSONObject();
    if(f1.exists() && f1.isFile()) {

        File backup = new File(f1.getParent() + "/_backup");
        if(!backup.exists()) backup.mkdir();
        f1.renameTo(new File(f1.getParent() + "/_backup/" + f1.getName() + "." + m.time()));

        m.writeFile(filepath, body);
        try { Runtime.getRuntime().exec("chown -R " + uid + ":" + uid + " " + filepath); }
        catch(RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage(), re); }
        catch(Exception e) { m.errorLog("Exception : " + e.getMessage(), e); }
        json.put("error", 0);
        json.put("message", "Success");
    } else {
        json.put("error", 2);
        json.put("message", "\ud30c\uc77c\uc774 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
    }
    out.print(json.toString());
    return;
}
else if("write".equals(mode)) {
    f.addElement("body", null, "allowscript:'Y', allowhtml:'Y', allowiframe:'Y', allowlink:'Y', allowobject:'Y'");
    String body = f.get("body");
    String filepath = dir + "/" + file;
    File f1 = new File(filepath);

    JSONObject json = new JSONObject();
    if(!f1.exists()) {
        m.writeFile(filepath, body);
        try { Runtime.getRuntime().exec("chown -R " + uid + ":" + uid + " " + filepath); }
        catch(RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage(), re); }
        catch(Exception e) { m.errorLog("Exception : " + e.getMessage(), e); }
        json.put("error", 0);
        json.put("message", "Success");
    } else {
        json.put("error", 3);
        json.put("message", "\uc774\ubbf8 \ud30c\uc77c\uc774 \uc874\uc7ac\ud569\ub2c8\ub2e4.");
    }
    out.print(json.toString());
    return;
}
else if("mkdir".equals(mode)) {
    String body = f.get("body");
    String filepath = dir + "/" + file;
    File f1 = new File(filepath);

    JSONObject json = new JSONObject();
    if(!f1.exists()) {
        f1.mkdirs();
        json.put("error", 0);
        json.put("message", "Success");
    } else {
        json.put("error", 3);
        json.put("message", "\uc774\ubbf8 \ud3f4\ub354\uac00 \uc874\uc7ac\ud569\ub2c8\ub2e4.");
    }
    out.print(json.toString());
    return;
}


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5413665724253103304L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("api/file.jsp"), 7966816382451785556L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
