/*
 * JSP generated by Resin-4.0.67 (built Thu, 01 Aug 2024 10:12:42 PDT)
 */

package _jsp._sysop._course;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.text.DecimalFormat;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _course_0modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();
String tplRoot = Config.getDocRoot() + "/sysop/html";

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch (RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage()); return; }
catch (Exception ex) { m.errorLog("\uc81c\ud55c \uc6a9\ub7c9 \ucd08\uacfc - " + ex.getMessage()); return; }

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/home/lms/public_html/html");

SiteDao Site = new SiteDao();
DataSet siteinfo = Site.getSiteInfo(request.getServerName(), "sysop");
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("sysop_status") || "".equals(siteinfo.s("doc_root"))) { m.jsReplace("/main/guide.jsp", "top"); return; }
//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 60\ubd84
siteinfo.put("sysop_session_hour", 60);
//B2b\uc0ac\uc6a9X
SiteConfig.put("join_b2b_yn", "N");

//String siteDomain = request.getScheme() + "://" + request.getServerName();
String siteDomain = "https://" + request.getServerName();
/*int port = request.getServerPort();
if(port != 80) siteDomain += ":" + port;*/
String webUrl = siteDomain + "/sysop";

String dataDir = siteinfo.s("doc_root") + "/data";
f.dataDir = dataDir;
m.dataDir = dataDir;
//m.dataUrl = Config.getDataUrl() + (!"/data".equals(Config.getDataUrl()) ? siteinfo.s("ftp_id") : "");
m.dataUrl = Config.getDataUrl();

boolean isDevServer = -1 < request.getServerName().indexOf("lms.malgn.co.kr");
siteinfo.put("logo_url", (!"/data".equals(Config.getDataUrl()) ? "" : siteDomain) + m.getUploadUrl(siteinfo.s("logo")));

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr(); //Lb \uc0ac\uc6a9
if(userIp.contains(",")) {
	String[] userIpArr = m.split(",", userIp);
	userIp = userIpArr[0].trim();
}

boolean isMalgnOffice = "1.212.252.90|3.35.211.181|52.79.184.225|127.0.0.1".contains(userIp);
isMalgnOffice = true;
//if(!"".equals(siteinfo.s("allow_ip_sysop")) && !isMalgnOffice && !Site.checkIP(userIp, siteinfo.s("allow_ip_sysop"))) {
//	m.redirect("/");
//	return;
//}

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
//String sysLocale = "default";
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

//\uae30\ubcf8 \ud68c\uc6d0\uc815\ubcf4
int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
String manageCourses = "";
String userSessionId = "";
String pagreeDate = "";
boolean isUserMaster = false;
String winTitle = "[\uad00\ub9ac\uc790] " + siteinfo.s("site_nm");
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
String surl = request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : "");
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));
final int sysExcelCnt = 20000;

SessionDao mSession = new SessionDao(request, response);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "MLMSKEY2014" + siteId + "7";
if(0 < siteinfo.i("sysop_session_hour")) auth.setValidTime(siteinfo.i("sysop_session_hour") * 60);
if(auth.isValid()) {
	userId = m.parseInt(auth.getString("ID"));
	loginId = auth.getString("LOGINID");
	userName = auth.getString("NAME");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	manageCourses = auth.getString("MANAGE_COURSES");
	userSessionId = userSessionId = auth.getString("SESSIONID");
	pagreeDate = auth.getString("PAGREE_DATE");
	isUserMaster = "Y".equals(auth.getString("IS_USER_MASTER"));

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if(request.getRequestURI().indexOf("/main/auth2.jsp") == -1
		//&& "Y".equals(siteinfo.s("auth2_yn"))
		&& !"Y".equals(auth.getString("AUTH2_YN"))
		//&& !"".equals(siteinfo.s("auth2_type"))
		//&& !"malgn".equals(loginId)
		&& request.getRequestURI().indexOf("/main/otpkey_register.jsp") == -1
		&& request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1
		&& request.getRequestURI().indexOf("/main/modify_passwd.jsp") == -1
	) {
		m.jsReplace("/sysop/main/auth2.jsp?returl=" + m.rs("returl", "/sysop/index.jsp"), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& -1 == request.getRequestURI().indexOf("/sysop/main/logout.jsp")
		&& -1 == request.getRequestURI().indexOf("/sysop/main/login.jsp")
		&& -1 == request.getRequestURI().indexOf("/main/modify_passwd.jsp")
	) {
		m.jsReplace("/sysop/main/logout.jsp");
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

} else {
	if(request.getRequestURI().indexOf("/main/login.jsp") == -1
		&& request.getRequestURI().indexOf("/vod/upload.jsp") == -1
		&& request.getRequestURI().indexOf("/main/slogin.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_template.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_maildir.jsp") == -1
		&& (request.getRequestURI().indexOf("/user/sleep_insert.jsp") == -1 || !"log".equals(m.rs("after")))
	) {
		m.jsReplace(auth.loginURL, "top");
		return;
	}
}

MenuDao Menu = new MenuDao(p, siteId, "default");
SiteMenuDao SiteMenu = new SiteMenuDao();

boolean superBlock = "S".equals(userKind);
boolean adminBlock = "S".equals(userKind) || "A".equals(userKind);
boolean courseManagerBlock = "C".equals(userKind);
boolean deptManagerBlock = "D".equals(userKind);

//boolean isAuthCrm = superBlock || (-1 < siteinfo.s("auth_crm").indexOf("|" + userKind + "|"));
boolean isAuthCrm = superBlock || Menu.accessible(-999, userId, userKind, false);

//\ub85c\uadf8\uc544\uc6c3-\uacfc\uc815\uc6b4\uc601\uc790
if(courseManagerBlock && "".equals(manageCourses) && request.getRequestURI().indexOf("/main/logout.jsp") == -1) {
	m.jsAlert("\ub2f4\ub2f9\ud55c \uacfc\uc815\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\\n \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc138\uc694.");
	m.jsReplace("/sysop/main/logout.jsp", "top");
	return;
}

//\ub9e4\ub274\uc5bc
ManualDao Manual = new ManualDao();
int ManualId = Menu.getOneInt("SELECT manual_id FROM " + Menu.table + " WHERE link = '" + m.replace(request.getRequestURI(), "/sysop", "..") + "'");
if(0 < ManualId) {
	int ManualStatus = Manual.getOneInt("SELECT status FROM " + Manual.table + " WHERE id = " + ManualId);
	if(0 < ManualStatus) p.setVar("SYS_MENU_MANUAL_ID", ManualId);
}

p.setVar("WEB_URL", webUrl);
p.setVar("FRONT_URL", siteDomain);
p.setVar("SYS_TITLE", winTitle);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("IS_AUTH_CRM", isAuthCrm);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_COMMON_CDN", "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);

p.setVar("user_master_block", isUserMaster || isMalgnOffice);
p.setVar("malgn_office_block", isMalgnOffice);
p.setVar("super_block", superBlock);
p.setVar("admin_block", adminBlock);
p.setVar("course_manager_block", courseManagerBlock);
p.setVar("dept_manager_block", deptManagerBlock);
p.setVar("SYS_URL", surl);

//boolean isBlindUser = !sysToday.equals(pagreeDate);
//p.setVar("SYS_BLINDUSER", isBlindUser);

//\uac1c\uc778\uc815\ubcf4\ucc98\ub9ac \uc218\uc815 - 2024.03.25
boolean isBlindUser = !"Y".equals(m.getCookie("PCONFIRM_YN"));
p.setVar("SYS_BLINDUSER", isBlindUser);
p.setVar("PCONFIRM_YN", m.getCookie("PCONFIRM_YN"));
String inquiryPurpose = m.getCookie("INQUIRYPURPOSE");

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
UserSession.setType("sysop");
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && "N".equals(siteinfo.s("dup_sysop_yn")) && ("".equals(userSessionId) || userSessionId == null || !UserSession.isValid(userSessionId, userId))) {
	if(request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1) {
		m.jsAlert("\uc138\uc158\uc774 \ub9cc\ub8cc\ub418\uc5c8\uac70\ub098 \uc911\ubcf5 \ub85c\uadf8\uc778\uc774 \ub418\uc5b4 \uc790\ub3d9\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ub429\ub2c8\ub2e4.");
		m.jsReplace("/sysop/main/logout.jsp?mode=session", "top");
		return;
	}
}

InfoLogDao _log = new InfoLogDao(siteId); _log.setItems(userId, "B", surl, userIp);
InfoUserDao _logUser = new InfoUserDao(siteId);


    

String ch = "sysop";

p.setVar("auth_course_block", Menu.accessible(33, userId, userKind, false));
p.setVar("auth_management_block", Menu.accessible(75, userId, userKind, false));
p.setVar("auth_complete_block", Menu.accessible(76, userId, userKind, false));
p.setVar("auth_auto_block", Menu.accessible(42, userId, userKind, false));


    

//\uc811\uadfc\uad8c\ud55c
if(!Menu.accessible(33, userId, userKind)) { m.jsError("\uc811\uadfc \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uae30\ubcf8\ud0a4
int id = m.ri("id");
if(id == 0) { m.jsError("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc788\uc5b4\uc57c \ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
CourseDao course = new CourseDao();
CourseUserDao courseUser = new CourseUserDao();
CourseRenewDao courseRenew = new CourseRenewDao();
CourseLessonDao courseLesson = new CourseLessonDao();
CourseModuleDao courseModule = new CourseModuleDao();
LmCategoryDao category = new LmCategoryDao("course");
LessonDao lesson = new LessonDao();

CourseBookDao courseBook = new CourseBookDao();
CourseTutorDao courseTutor = new CourseTutorDao();
CourseTargetDao courseTarget = new CourseTargetDao();
CoursePrecedeDao coursePrecede = new CoursePrecedeDao();
CourseManagerDao courseManager = new CourseManagerDao();
CoursePackageDao coursePackage = new CoursePackageDao();

CertificateTemplateDao certificateTemplate = new CertificateTemplateDao();

BookDao book = new BookDao();
UserDao user = new UserDao();
TutorDao tutor = new TutorDao();
GroupDao group = new GroupDao();

MCal mcal = new MCal(); mcal.yearRange = 10;

//\uc815\ubcf4-\uc0ac\uc774\ud2b8\uc124\uc815
DataSet siteconfig = SiteConfig.getArr(new String[] {"cert_template_yn", "kollus"});

//m.p(siteconfig);

//\uce74\ud14c\uace0\ub9ac
DataSet categories = category.getList(siteId);

DataSet info = course.query(
	"SELECT a.*, c.course_nm before_course_nm, l.lesson_nm sample_lesson_nm "
	+ " FROM " + course.table + " a "
	+ " LEFT JOIN " + course.table + " c ON a.before_course_id = c.id "
	+ " LEFT JOIN " + lesson.table + " l ON a.sample_lesson_id = l.id "
	+ " WHERE a.id = " + id	+ " AND a.status != -1 AND a.site_id = " + siteId + ""
	+ ("C".equals(userKind) ? " AND a.id IN (" + manageCourses + ") " : "")
);
if(!info.next()) { m.jsError("\ud574\ub2f9 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uc628\ub77c\uc778 \uc815\uaddc\uac15\uc758\uc758 \uacbd\uc6b0 \ud654\uc0c1\uac15\uc758 \ucc28\uc2dc\uac00 \uc874\uc7ac\ud558\uba74 \ucc28\uc2dc\ubcc4 \ud559\uc2b5\uae30\uac04 \uc0ac\uc6a9\uc73c\ub85c \uace0\uc815
boolean isOnlineRegular = "N".equals(info.s("onoff_type")) & "R".equals(info.s("course_type"));
boolean hasTwoway = false;
if(isOnlineRegular) {
	hasTwoway = 0 < courseLesson.getOneInt(
		" SELECT COUNT(*) FROM " + courseLesson.table + " a "
		+ " INNER JOIN " + lesson.table + " l ON a.lesson_id = l.id AND l.site_id = " + siteId
		+ " WHERE a.course_id = " + info.i("id") + " AND a.site_id = " + siteId	+ " AND l.onoff_type = 'T'"
	);
}

info.put("lesson_time", new DecimalFormat("#.##").format(info.d("lesson_time")));
info.put("limit_ratio", new DecimalFormat("#.##").format(info.d("limit_ratio")));
info.put("request_sdate", m.time("yyyy-MM-dd", info.s("request_sdate")));
info.put("request_edate", m.time("yyyy-MM-dd", info.s("request_edate")));
info.put("study_sdate", m.time("yyyy-MM-dd", info.s("study_sdate")));
info.put("study_edate", m.time("yyyy-MM-dd", info.s("study_edate")));
info.put("onoff_type_" + info.s("onoff_type"), true);
info.put("course_type_" + info.s("course_type"), true);
info.put("cate_name", category.getTreeNames(info.i("category_id")));
info.put("lesson_order_block", "N".equals(info.s("onoff_type")));
info.put("period_block", isOnlineRegular & !hasTwoway);
info.put("online_block", "N".equals(info.s("onoff_type")));
info.put("lesson_order_conv", info.b("lesson_order_yn") ? "\uc0ac\uc6a9" : "\ubbf8\uc0ac\uc6a9");
info.put("period_yn_conv", info.b("period_yn") ? "\uc0ac\uc6a9" : "\ubbf8\uc0ac\uc6a9");

//\ubcc0\uc218
boolean closed = info.b("close_yn");
boolean isPackage = "P".equals(info.s("onoff_type"));
boolean usePlayrate = "Y".equals(siteconfig.s("kollus_playrate_yn"));
String[] courseAddr = m.split("|", info.s("course_address"));

//\ud30c\uc77c\uc0ad\uc81c
if("fdel".equals(m.rs("mode"))) {
	//\uc81c\ud55c
	if(closed) { m.jsAlert("\ud574\ub2f9 \uacfc\uc815\uc740 \uc885\ub8cc\ub418\uc5b4 \ud30c\uc77c\uc744 \uc0ad\uc81c\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

	if(!"".equals(info.s("course_file"))) {
		course.item("course_file", "");
		if(course.update("id = " + id)) {
			m.delFileRoot(m.getUploadPath(info.s("course_file")));
		}
	}
	return;
}

//\ud3fc\uccb4\ud06c
f.addElement("onoff_type", info.s("onoff_type"), "hname:'\uacfc\uc815 \uad6c\ubd84', required:'Y'");
f.addElement("category_id", info.i("category_id"), "hname:'\uce74\ud14c\uace0\ub9ac', required:'Y'");
f.addElement("category_nm", category.getTreeNames(info.i("category_id")), "hname:'\uce74\ud14c\uace0\ub9ac', required:'Y'");

f.addElement("course_nm", info.s("course_nm"), "hname:'\uacfc\uc815\uba85', required:'Y'");
f.addElement("course_type", info.s("course_type"), "hname:'\uacfc\uc815\uad6c\ubd84', required:'Y'");
f.addElement("year", info.s("year"), "hname:'\ub144\ub3c4', required:'Y'");

//f.addElement("step", info.s("step"), "hname:'\uae30\uc218', required:'Y', option:'number'");
//f.addElement("grade", info.s("grade"), "hname:'\ud559\ub144', required:'Y'");
f.addElement("term", info.s("term"), "hname:'\ud559\uae30', required:'Y'");
//f.addElement("subject", info.s("subject"), "hname:'\uacfc\ubaa9', required:'Y'");

f.addElement("request_sdate", info.s("request_sdate"), "hname:'\uc218\uac15\uc2e0\uccad\uc2dc\uc791\uc77c'");
f.addElement("request_edate", info.s("request_edate"), "hname:'\uc218\uac15\uc2e0\uccad\uc885\ub8cc\uc77c'");
f.addElement("study_sdate", info.s("study_sdate"), "hname:'\ud559\uc2b5\uc2dc\uc791\uc77c'");
f.addElement("study_edate", info.s("study_edate"), "hname:'\ud559\uc2b5\uc885\ub8cc\uc77c'");
f.addElement("user_date_yn", "N", "hname:'\uae30\uc874\uc218\uac15\uc0dd \ud559\uc2b5\uae30\uac04 \uc77c\uad04\ubcc0\uacbd \uc5ec\ubd80'");
f.addElement("lesson_day", info.i("lesson_day"), "hname:'\ud559\uc2b5\uc77c\uc218', option:'number', min:'1'");
f.addElement("course_file", null, "hname:'\uba54\uc778\uc774\ubbf8\uc9c0', allow:'jpg|jpeg|gif|png'");
f.addElement("list_price", info.i("list_price"), "hname:'\uc815\uac00', option:'number', required:'Y'");
f.addElement("price", info.i("price"), "hname:'\uc218\uac15\ub8cc', option:'number', required:'Y'");
f.addElement("taxfree_yn", info.s("taxfree_yn"), "hname:'\ubd80\uac00\uc138\uba74\uc138\uc5ec\ubd80'");
f.addElement("disc_group_yn", info.s("disc_group_yn"), "hname:'\uadf8\ub8f9\ud560\uc778\uc801\uc6a9\uc5ec\ubd80'");
f.addElement("memo_yn", info.s("memo_yn"), "hname:'\uc8fc\ubb38\uba54\ubaa8 \uc0ac\uc6a9\uc5ec\ubd80'");
if(!isPackage) {
	f.addElement("renew_yn", info.s("renew_yn"), "hname:'\uc218\uac15\uae30\uac04 \uc5f0\uc7a5\uacb0\uc81c \uc0ac\uc6a9\uc5ec\ubd80'");
	f.addElement("renew_max_cnt", info.i("renew_max_cnt"), "hname:'\ucd5c\ub300 \uc5f0\uc7a5\ud69f\uc218', option:'number', min:'0', max:'999'");
	f.addElement("renew_price", info.i("renew_price"), "hname:'\uc5f0\uc7a5\ube44\uc6a9', option:'number', min:'0'");
	f.addElement("credit", info.i("credit"), "hname:'\ud559\uc810', required:'Y'");
	f.addElement("lesson_time", info.s("lesson_time"), "hname:'\uc2dc\uc218', min:'0.01', required:'Y'");
}
f.addElement("mobile_yn", info.s("mobile_yn"), "hname:'\ubaa8\ubc14\uc77c \uc9c0\uc6d0\uc5ec\ubd80'");
f.addElement("evaluation_yn", info.s("evaluation_yn"), "hname:'\uc218\ub8cc\uae30\uc900 \ub178\ucd9c\uc5ec\ubd80'");
//f.addElement("top_yn", info.s("top_yn"), "hname:'\uc0c1\uc2dc \uc0c1\uc704\uace0\uc815'");

f.addElement("recomm_yn", info.s("recomm_yn"), "hname:'\ucd94\ucc9c\uacfc\uc815'");
f.addElement("auto_approve_yn", info.s("auto_approve_yn"), "hname:'\uc2e0\uccad\uc989\uc2dc \uc2b9\uc778\uc5ec\ubd80'");
f.addElement("sms_yn", info.s("sms_yn"), "hname:'SMS \uc778\uc99d\uc5ec\ubd80'");
f.addElement("target_yn", info.s("target_yn"), "hname:'\ud559\uc2b5\ub300\uc0c1\uc790 \uc0ac\uc6a9\uc5ec\ubd80'");
if(!isPackage) f.addElement("complete_auto_yn", info.s("complete_auto_yn"), "hname:'\uc790\ub3d9 \uc218\ub8cc\ucc98\ub9ac'");
//else f.addElement("complete_auto_yn", info.s("complete_auto_yn"), "hname:'\uc790\ub3d9 \uc218\ub8cc\ucc98\ub9ac'");
f.addElement("restudy_yn", info.s("restudy_yn"), "hname:'\ubcf5\uc2b5\uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("restudy_day", info.i("restudy_day"), "hname:'\ubcf5\uc2b5\ud5c8\uc6a9\uae30\uac04', option:'number', max:'3700'");

f.addElement("limit_lesson_yn", info.s("limit_lesson_yn"), "hname:'\ud559\uc2b5\uac15\uc758\uc81c\ud55c \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("limit_lesson", info.i("limit_lesson"), "hname:'\ud559\uc2b5\uc81c\ud55c \uac15\uc758 \uc218', option:'number'");
f.addElement("limit_people_yn", info.s("limit_people_yn"), "hname:'\uc218\uac15\uc778\uc6d0\uc81c\ud55c \uc0ac\uc6a9\uc720\ubb34'");
f.addElement("limit_people", info.i("limit_people"), "hname:'\uc218\uac15\uc81c\ud55c\uc778\uc6d0', option:'number'");
f.addElement("limit_ratio_yn", info.s("limit_ratio_yn"), "hname:'\ubc30\uc218\uc81c\ud55c \uc0ac\uc6a9\uc720\ubb34'");
f.addElement("limit_ratio", info.s("limit_ratio"), "hname:'\ubc30\uc218\uc81c\ud55c\ube44\uc728'");
f.addElement("limit_seek_yn", info.s("limit_seek_yn"), "hname:'\ud0d0\uc0c9\uc81c\ud55c \uc0ac\uc6a9\uc720\ubb34'");
f.addElement("lesson_order_yn", info.s("lesson_order_yn"), "hname:'\uac15\uc758 \uc21c\ucc28\uc801\uc6a9 \uc5ec\ubd80'");
if(!isPackage) f.addElement("period_yn", info.s("period_yn"), "hname:'\ucc28\uc2dc\ubcc4 \uc218\uac15\uae30\uac04'");
if(usePlayrate) f.addElement("playrate_yn", info.s("playrate_yn"), "hname:'\uc218\uac15\uc81c\ud55c\uc778\uc6d0'");

f.addElement("exam_yn", info.s("exam_yn"), "hname:'\uc2dc\ud5d8 \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("homework_yn", info.s("homework_yn"), "hname:'\uacfc\uc81c \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("forum_yn", info.s("forum_yn"), "hname:'\ud1a0\ub860 \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("survey_yn", info.s("survey_yn"), "hname:'\uc124\ubb38 \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("review_yn", info.s("review_yn"), "hname:'\uc0ac\uc6a9\ud6c4\uae30 \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("cert_course_yn", info.s("cert_course_yn"), "hname:'\uc218\uac15\uc99d \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("cert_complete_yn", info.s("cert_complete_yn"), "hname:'\uc218\ub8cc\uc99d \uc0ac\uc6a9\uc5ec\ubd80'");
//\uc0c8\ub85c \ucd94\uac00 Start
//f.addElement("cert_course2_yn", info.s("cert_course2_yn"), "hname:'2\ud559\uae30 \ud569\uaca9\uc99d \uc0ac\uc6a9\uc5ec\ubd80'");
//f.addElement("cert_complete2_yn", info.s("cert_complete2_yn"), "hname:'2\ud559\uae30 \uc218\ub8cc\uc99d \uc0ac\uc6a9\uc5ec\ubd80'");
//f.addElement("status_fullcourse", info.s("status_fullcourse"), "hname:'\uc218\ub8cc\uc99d\ud569\uaca9\uc99d 4\ubc88\uc0ac\uc6a9\uc5ec\ubd80'");
//\uc0c8\ub85c \ucd94\uac00 End
f.addElement("sample_lesson_nm", info.s("sample_lesson_nm"), "hname:'\uc0d8\ud50c\ub3d9\uc601\uc0c1'");
f.addElement("before_course_nm", info.s("before_course_nm"), "hname:'\uc120\ud589\uacfc\uc815'");
f.addElement("course_addr", courseAddr[0], "hname:'\uad50\uc721\uc7a5 \uc8fc\uc18c'");
f.addElement("course_addr_dtl", (1 < courseAddr.length ? courseAddr[1] : ""), "hname:'\uad50\uc721\uc7a5 \uc0c1\uc138\uc8fc\uc18c'");

f.addElement("subtitle", null, "hname:'\uacfc\uc815\ubaa9\ub85d \uc18c\uac1c\ubb38\uad6c'");
f.addElement("content1", null, "hname:'\ud14d\uc2a4\ud2b81', allowiframe:'Y', allowhtml:'Y'");
f.addElement("content2", null, "hname:'\ud14d\uc2a4\ud2b82', allowiframe:'Y'");
f.addElement("content1_title", info.s("content1_title"), "hname:'\ud14d\uc2a4\ud2b81 \ud0c0\uc774\ud2c0'");
f.addElement("content2_title", info.s("content2_title"), "hname:'\ud14d\uc2a4\ud2b82 \ud0c0\uc774\ud2c0'");
//f.addElement("manager_id", info.s("manager_id"), "hname:'\ub2f4\ub2f9\uc790'");
//f.addElement("manager_name", info.s("manager_name"), "hname:'\ub2f4\ub2f9\uc790'");
f.addElement("etc1", info.s("etc1"), "hname:'\uae30\ud0c01'");
f.addElement("etc2", info.s("etc2"), "hname:'\uae30\ud0c02'");
f.addElement("sale_yn", info.s("sale_yn"), "hname:'\ud310\ub9e4\uc5ec\ubd80'");
f.addElement("display_yn", info.s("display_yn"), "hname:'\ub178\ucd9c\uc5ec\ubd80'");
f.addElement("status", info.s("status"), "hname:'\uc0c1\ud0dc'");

	if(!isPackage) {
		f.addElement("assign_progress", info.i("assign_progress"), "hname:'\ucd9c\uc11d(\uc9c4\ub3c4) \ubc30\uc810\ube44\uc728', option:'number', required:'Y'");
		f.addElement("assign_exam", info.i("assign_exam"), "hname:'\uc2dc\ud5d8 \ubc30\uc810\ube44\uc728', option:'number', required:'Y'");
	f.addElement("assign_homework", info.i("assign_homework"), "hname:'\uacfc\uc81c \ubc30\uc810\ube44\uc728', option:'number', required:'Y'");
	f.addElement("assign_forum", info.i("assign_forum"), "hname:'\ud1a0\ub860 \ubc30\uc810\ube44\uc728', option:'number', required:'Y'");
		f.addElement("assign_etc", info.i("assign_etc"), "hname:'\uae30\ud0c0 \ubc30\uc810\ube44\uc728', option:'number', required:'Y'");
		f.addElement("assign_survey_yn", info.s("assign_survey_yn"), "hname:'\uc124\ubb38\ucc38\uc5ec \ud544\uc218\uc5ec\ubd80'");
		f.addElement("limit_total_score", info.i("limit_total_score"), "hname:'\ucd1d\uc810 \uc218\ub8cc\uae30\uc900', option:'number', required:'Y'");
		f.addElement("limit_progress", info.i("limit_progress"), "hname:'\uc9c4\ub3c4 \uc218\ub8cc\uae30\uc900', option:'number', required:'Y'");
		f.addElement("limit_exam", info.i("limit_exam"), "hname:'\uc2dc\ud5d8 \uc218\ub8cc\uae30\uc900', option:'number', required:'Y'");
		f.addElement("limit_homework", info.i("limit_homework"), "hname:'\uacfc\uc81c \uc218\ub8cc\uae30\uc900', option:'number', required:'Y'");
		f.addElement("limit_forum", info.i("limit_forum"), "hname:'\ud1a0\ub860 \uc218\ub8cc\uae30\uc900', option:'number', required:'Y'");
		f.addElement("limit_etc", info.i("limit_etc"), "hname:'\uae30\ud0c0 \uc218\ub8cc\uae30\uc900', option:'number', required:'Y'");
		f.addElement("complete_limit_progress", info.i("complete_limit_progress"), "hname:'\uc9c4\ub3c4 \uc218\ub8cc(\uc644\ub8cc) \uae30\uc900', option:'number', required:'Y'");
		f.addElement("complete_limit_total_score", info.i("complete_limit_total_score"), "hname:'\ucd1d\uc810 \uc218\ub8cc(\uc644\ub8cc) \uae30\uc900', option:'number', required:'Y'");
	f.addElement("push_survey_yn", info.s("push_survey_yn"), "hname:'\uc124\ubb38\ucc38\uc5ec \ub3c5\ub824\uc5ec\ubd80'");

	f.addElement("cert_template_id", info.i("cert_template_id"), "hname:'\uc218\ub8cc\uc99d \ud15c\ud50c\ub9bf'");
	f.addElement("complete_prefix", info.s("complete_prefix"), "hname:'\uc218\ub8cc\ubc88\ud638'");
	f.addElement("complete_no_yn", info.s("complete_no_yn"), "hname:'\uc218\ub8cc\ubc88\ud638 \uc0ac\uc6a9\uc5ec\ubd80'");
	f.addElement("postfix_cnt", info.i("postfix_cnt"), "hname:'\uc218\ub8cc\ubc88\ud638 \ub4b7\uc790\ub9ac\uc218'");
	f.addElement("postfix_type", info.s("postfix_type"), "hname:'\uc218\ub8cc\ubc88\ud638 \ub4b7\uc790\ub9ac\ubc29\uc2dd'");
	f.addElement("postfix_ord", info.s("postfix_ord"), "hname:'\uc218\ub8cc\ubc88\ud638 \uc815\ub82c\ubc29\uc2dd'");
}

//\ub4f1\ub85d
if(m.isPost() && f.validate()) {

	//\uc81c\ud55c
	if(closed) { m.jsAlert("\ud574\ub2f9 \uacfc\uc815\uc740 \uc885\ub8cc\ub418\uc5b4 \uc218\uc815\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

	//\uc81c\ud55c-\ud328\ud0a4\uc9c0
	if(isPackage && "Y".equals(f.get("sale_yn")) && 0 >= coursePackage.findCount("package_id = " + id)) {
		m.jsAlert("\ud574\ub2f9 \ud328\ud0a4\uc9c0\uc5d0 \ub4f1\ub85d\ub41c \uacfc\uc815\uc774 \uc5c6\uc5b4 \ud310\ub9e4\uc5ec\ubd80\ub97c \ubcc0\uacbd\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.");
		return;
	}

	if(!isPackage) {
		if(f.get("complete_prefix").length() > 20) { m.jsAlert("\uc218\ub8cc\ubc88\ud638 \uc55e\uc790\ub9ac\ub294 20\uc790\ub97c \ucd08\uacfc\ud574 \uc124\uc815\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }
		if(f.getInt("postfix_cnt") > 8) { m.jsAlert("\uc218\ub8cc\ubc88\ud638 \ub4b7\uc790\ub9ac\uc218\ub294 8\uac1c\ub97c \ucd08\uacfc\ud574 \uc124\uc815\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

		if(f.getInt("complete_limit_progress") > f.getInt("limit_progress")) {
			m.jsAlert("\uc218\ub8cc(\uc644\ub8cc) \uc9c4\ub3c4 \uae30\uc900\uc740 \ud569\uaca9 \uc9c4\ub3c4 \uae30\uc900\uc744 \ub118\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."); return;
		}
		if(f.getInt("complete_limit_total_score") > f.getInt("limit_total_score")) {
			m.jsAlert("\uc218\ub8cc(\uc644\ub8cc) \ucd1d\uc810 \uae30\uc900\uc740 \ud569\uaca9 \ucd1d\uc810 \uae30\uc900\uc744 \ub118\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."); return;
		}
	}


	//\uc81c\ud55c
	/*
	if(0 < course.findCount(
			"site_id = " + siteId + " AND subject_id = " + info.i("subject_id") + " "
			+ " AND year = " + f.getInt("year") + " AND step = " + f.getInt("step") + " "
			+ " AND id != " + id + " AND status != -1"
	)) {
		m.jsAlert("\uacfc\uc815\uba85/\ub144\ub3c4/\uae30\uc218\ub97c \uc0ac\uc6a9 \uc911\uc785\ub2c8\ub2e4. \ub2e4\uc2dc \uc785\ub825\ud558\uc138\uc694.");
		return;
	}
	*/

	//\uc81c\ud55c-\uc774\ubbf8\uc9c0URI\ubc0f\uc6a9\ub7c9
	String subtitle = f.get("subtitle");
	String content1 = f.get("content1");
	String content2 = f.get("content2");
	int bytest = subtitle.replace("\r\n", "\n").getBytes("UTF-8").length;
	int bytes1 = content1.replace("\r\n", "\n").getBytes("UTF-8").length;
	int bytes2 = content2.replace("\r\n", "\n").getBytes("UTF-8").length;
	if(-1 < content1.indexOf("<img") && -1 < content1.indexOf("data:image/") && -1 < content1.indexOf("base64")) {
		m.jsAlert(f.get("content1_title") + " \uc774\ubbf8\uc9c0\ub294 \ucca8\ubd80\ud30c\uc77c \uae30\ub2a5\uc73c\ub85c \uc5c5\ub85c\ub4dc \ud574 \uc8fc\uc138\uc694.");
		return;
	}
	if(500 < bytest) { m.jsAlert("\uacfc\uc815\ubaa9\ub85d \uc18c\uac1c\ubb38\uad6c \ub0b4\uc6a9\uc740 500\ubc14\uc774\ud2b8\ub97c \ucd08\uacfc\ud574 \uc791\uc131\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\\n(\ud604\uc7ac " + bytest + "\ubc14\uc774\ud2b8)"); return; }
	if(60000 < bytes1) { m.jsAlert(f.get("content1_title") + " \ub0b4\uc6a9\uc740 60000\ubc14\uc774\ud2b8\ub97c \ucd08\uacfc\ud574 \uc791\uc131\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\\n(\ud604\uc7ac " + bytes1 + "\ubc14\uc774\ud2b8)"); return; }
	if(60000 < bytes2) { m.jsAlert(f.get("content2_title") + " \ub0b4\uc6a9\uc740 60000\ubc14\uc774\ud2b8\ub97c \ucd08\uacfc\ud574 \uc791\uc131\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\\n(\ud604\uc7ac " + bytes2 + "\ubc14\uc774\ud2b8)"); return; }

	course.item("course_nm", f.get("course_nm"));
	course.item("category_id", f.get("category_id"));

	course.item("year", f.get("year"));
//	course.item("step", f.get("step"));
//	course.item("grade", f.get("grade"));
	course.item("term", f.get("term"));
//	course.item("subject", f.get("subject"));

	String ssdate = "";
	String sedate = "";
	course.item("course_type", f.get("course_type"));
	if("R".equals(f.get("course_type"))) { //\uc815\uaddc
		ssdate = m.time("yyyyMMdd", f.get("study_sdate"));
		sedate = m.time("yyyyMMdd", f.get("study_edate"));

		course.item("request_sdate", m.time("yyyyMMdd", f.get("request_sdate")));
		course.item("request_edate", m.time("yyyyMMdd", f.get("request_edate")));
		course.item("study_sdate", ssdate);
		course.item("study_edate", sedate);

	} else if("A".equals(f.get("course_type"))) { //\uc0c1\uc2dc
		course.item("request_sdate", "");
		course.item("request_edate", "");
		course.item("study_sdate", "");
		course.item("study_edate", "");
	}

	if("P".equals(f.get("onoff_type"))) {
		course.item("study_sdate", "");
		course.item("study_edate", "");
	}

	course.item("lesson_day", f.getInt("lesson_day"));
	course.item("lesson_time", f.getDouble("lesson_time"));

	boolean isUpload = false;
	if(null != f.getFileName("course_file")) {
		File f1 = f.saveFile("course_file");
		if(f1 != null) {
			isUpload = true;
			course.item("course_file", f.getFileName("course_file"));
			if(!"".equals(info.s("course_file")) && new File(m.getUploadPath(info.s("course_file"))).exists()) {
				m.delFileRoot(m.getUploadPath(info.s("course_file")));
			}
		}
	}
	course.item("list_price", f.getInt("list_price"));
	course.item("price", f.getInt("price"));
	course.item("taxfree_yn", f.get("taxfree_yn", "N"));
	course.item("disc_group_yn", f.get("disc_group_yn", "N"));
	course.item("memo_yn", f.get("memo_yn", "N"));
	course.item("renew_price", f.getInt("renew_price"));
	course.item("renew_max_cnt", f.getInt("renew_max_cnt"));
	course.item("renew_yn", f.get("renew_yn", "N"));

	course.item("credit", f.getInt("credit"));
	course.item("mobile_yn", f.get("mobile_yn", "N"));
	course.item("evaluation_yn", f.get("evaluation_yn", "N"));
	//course.item("top_yn", f.get("top_yn", "N"));

	course.item("recomm_yn", f.get("recomm_yn", "N"));
	course.item("auto_approve_yn", f.get("auto_approve_yn", "N"));
	course.item("sms_yn", f.get("sms_yn", "N"));
	course.item("target_yn", f.get("target_yn", "N"));
	course.item("complete_auto_yn", f.get("complete_auto_yn", "N"));
		course.item("restudy_yn", f.get("restudy_yn", "N"));
	course.item("restudy_day", "Y".equals(f.get("restudy_yn", "N")) ? (3700 > f.getInt("restudy_day") ? f.getInt("restudy_day") : 3700) : 0);

	course.item("limit_lesson_yn", f.get("limit_lesson_yn", "N"));
	course.item("limit_lesson", "Y".equals(f.get("limit_lesson_yn", "N")) ? f.getInt("limit_lesson") : 0);
	course.item("limit_people_yn", f.get("limit_people_yn", "N"));
	course.item("limit_people", "Y".equals(f.get("limit_people_yn", "N")) ? f.getInt("limit_people") : 0);
	course.item("limit_ratio_yn", f.get("limit_ratio_yn", "N"));
	course.item("limit_ratio", "Y".equals(f.get("limit_ratio_yn", "N")) ? f.getDouble("limit_ratio") : 0);
	course.item("limit_seek_yn", f.get("limit_seek_yn", "N"));
	course.item("lesson_order_yn", f.get("lesson_order_yn", "N"));
	if(!isPackage) {

		if(isOnlineRegular &&
			0 < courseLesson.getOneInt(
			" SELECT COUNT(*) FROM " + courseLesson.table + " a "
			+ " INNER JOIN " + lesson.table + " l ON a.lesson_id = l.id AND l.site_id = " + siteId
			+ " WHERE a.course_id = " + info.i("id") + " AND a.site_id = " + siteId	+ " AND l.onoff_type = 'T'"
		)) {
			course.item("period_yn", "Y");
		} else {
			course.item("period_yn", f.get("period_yn", "N"));
		}

	}
	if(usePlayrate) course.item("playrate_yn", f.get("playrate_yn", "N"));

	course.item("push_survey_yn", f.get("push_survey_yn", "N"));

	course.item("sample_lesson_id", f.getInt("sample_lesson_id"));
	//course.item("before_course_id", f.getInt("before_course_id"));
	//course.item("course_address", f.get("course_address"));
	course.item("course_address", f.glue("|", "course_addr,course_addr_dtl"));

	course.item("exam_yn", f.get("exam_yn", "N"));
	course.item("homework_yn", f.get("homework_yn", "N"));
	course.item("forum_yn", f.get("forum_yn", "N"));
	course.item("survey_yn", f.get("survey_yn", "N"));
	course.item("review_yn", f.get("review_yn", "N"));
	course.item("cert_course_yn", f.get("cert_course_yn", "N"));
	course.item("cert_complete_yn", f.get("cert_complete_yn", "N"));
	//\uc0c8\ub85c \ucd94\uac00 Start
		//course.item("cert_course2_yn", f.get("cert_course2_yn", "N"));
		//course.item("cert_complete2_yn", f.get("cert_complete2_yn", "N"));
		//course.item("status_fullcourse", f.get("status_fullcourse", "N"));
	//\uc0c8\ub85c \ucd94\uac00 End
	course.item("subtitle", subtitle);
	course.item("content1_title", f.get("content1_title"));
	course.item("content1", content1);
	course.item("content2_title", f.get("content2_title"));
	course.item("content2", content2);
	//if(!"C".equals(userKind)) course.item("manager_id", f.getInt("manager_id") != 0 ? f.getInt("manager_id") : userId);
	course.item("etc1", f.get("etc1"));
	course.item("etc2", f.get("etc2"));
	course.item("sale_yn", f.get("sale_yn", "N"));
	course.item("display_yn", f.get("display_yn", "N"));
	course.item("status", f.get("status", "0"));

	if(!isPackage) {
		course.item("assign_progress", f.getInt("assign_progress"));
		course.item("assign_exam", f.getInt("assign_exam"));
		course.item("assign_homework", f.getInt("assign_homework"));
		course.item("assign_forum", f.getInt("assign_forum"));
		course.item("assign_etc", f.getInt("assign_etc"));
		course.item("assign_survey_yn", f.get("assign_survey_yn"));
		course.item("limit_progress", f.getInt("limit_progress"));
		course.item("limit_exam", f.getInt("limit_exam"));
		course.item("limit_homework", f.getInt("limit_homework"));
		course.item("limit_forum", f.getInt("limit_forum"));
		course.item("limit_etc", f.getInt("limit_etc"));
		course.item("limit_total_score", f.getInt("limit_total_score"));
		course.item("complete_limit_progress", f.getInt("complete_limit_progress"));
		course.item("complete_limit_total_score", f.getInt("complete_limit_total_score"));
		course.item("cert_template_id", f.getInt("cert_template_id"));
		course.item("complete_prefix", f.get("complete_prefix"));
		course.item("complete_no_yn", f.get("complete_no_yn"));
		course.item("postfix_cnt", f.getInt("postfix_cnt"));
		course.item("postfix_type", f.get("postfix_type"));
		course.item("postfix_ord", f.get("postfix_ord"));
	}

	if(!course.update("id = " + id + "")) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	//\uac31\uc2e0-\ud559\uc2b5\uae30\uac04\ubcc0\uacbd\uc2dc
	String oldSsdate = m.time("yyyyMMdd", info.s("study_sdate"));
	String oldSedate = m.time("yyyyMMdd", info.s("study_edate"));
	if("R".equals(f.get("course_type")) && "Y".equals(f.get("user_date_yn"))) {
		courseUser.item("start_date", ssdate);
		courseUser.item("end_date", sedate);
		if(!courseUser.update("course_id = " + id + "")) {
			m.jsAlert("\uc218\uac15\uc0dd \uc815\ubcf4\ub97c \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return;
		}

		//\ub4f1\ub85d-\uc218\uac15\uae30\uac04\uc774\ub825
		courseRenew.item("site_id", siteId);
		courseRenew.item("renew_type", "U");
		courseRenew.item("user_id", userId);
		courseRenew.item("start_date", ssdate);
		courseRenew.item("end_date", sedate);
		courseRenew.item("order_item_id", -99);
		courseRenew.item("reg_date", sysNow);
		courseRenew.item("status", 1);
		DataSet culist = courseUser.find("course_id = " + id + "");
		while(culist.next()) {
			courseRenew.item("course_user_id", culist.i("id"));
			if(!courseRenew.insert()) { m.jsError("\uc218\uac15\uc774\ub825\uc744 \ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
		}


		//\uac31\uc2e0-\uac15\uc758\uae30\uac04
		if(!oldSsdate.equals(ssdate)) {
			String where = (0 > m.diffDate("D", oldSsdate, ssdate) ? "a.start_date = '" + oldSsdate + "'" : "a.start_date <= '" + ssdate + "'");
			DataSet cllist = courseLesson.query(
				" SELECT a.lesson_id, a.start_date, l.onoff_type "
				+ " FROM " + courseLesson.table + " a "
				+ " INNER JOIN " + lesson.table + " l ON a.lesson_id = l.id "
				+ " WHERE a.course_id = " + id + " AND " + where + " AND a.status != -1 "
			);

			courseLesson.clear();
			courseLesson.item("start_date", ssdate);
			while(cllist.next()) {
				courseLesson.item("end_date", !"F".equals(cllist.s("onoff_type")) ? cllist.s("end_date") : ssdate);
				if(!courseLesson.update("course_id = " + id + " AND lesson_id = " + cllist.i("lesson_id"))) { m.jsAlert("\uac15\uc758 \uc815\ubcf4\ub97c \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
			}
		}
		if(!oldSedate.equals(sedate)) {
			String where = (0 < m.diffDate("D", oldSedate, sedate) ? "a.end_date = '" + oldSedate + "'" : "a.end_date >= '" + sedate + "'");
			DataSet cllist = courseLesson.query(
				" SELECT a.lesson_id, a.start_date, l.onoff_type "
				+ " FROM " + courseLesson.table + " a "
				+ " INNER JOIN " + lesson.table + " l ON a.lesson_id = l.id "
				+ " WHERE a.course_id = " + id + " AND " + where + " AND a.status != -1 "
			);

			courseLesson.clear();
			courseLesson.item("end_date", sedate);
			while(cllist.next()) {
				courseLesson.item("start_date", !"F".equals(cllist.s("onoff_type")) ? cllist.s("start_date") : sedate);
				if(!courseLesson.update("course_id = " + id + " AND lesson_id = " + cllist.i("lesson_id"))) { m.jsAlert("\uac15\uc758 \uc815\ubcf4\ub97c \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
			}
		}
	}

	//\uac31\uc2e0-\ucc28\uc2dc\ubcc4\uc21c\ucc28\ud559\uc2b5\ubcc0\uacbd\uc2dc-\uae30\uc874\ucc28\uc2dc\ud559\uc2b5\uae30\uac04\ubd80\uc5ec
	if("Y".equals(f.get("period_yn")) && !"Y".equals(info.s("period_yn"))) {
		DataSet cllist = courseLesson.query(
			" SELECT a.lesson_id "
			+ " FROM " + courseLesson.table + " a "
			+ " INNER JOIN " + lesson.table + " l ON a.lesson_id = l.id AND l.onoff_type = 'N' "
			+ " WHERE a.course_id = " + id
			+ " AND (a.start_date IS NULL OR a.start_date = '') OR (a.end_date IS NULL OR a.end_date = '') "
			+ " AND a.status != -1 "
		);

		courseLesson.clear();
		courseLesson.item("start_date", ssdate);
		courseLesson.item("start_time", "000000");
		courseLesson.item("end_date", sedate);
		courseLesson.item("end_time", "235559");

		ArrayList<Integer> lidx = new ArrayList<Integer>();
		while(cllist.next()) {
			if(!lidx.contains(cllist.i("lesson_id"))) lidx.add(cllist.i("lesson_id"));
		}
		if(0 < cllist.size() && !courseLesson.update("course_id = " + id + " AND lesson_id IN (" + m.join(",", lidx.toArray()) + ")")) {
			m.jsAlert("\uac15\uc758 \uc815\ubcf4\ub97c \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.");
			return;
		}
	}

	//\ub3c4\uc11c
	if(-1 != courseBook.execute("DELETE FROM " + courseBook.table + " WHERE course_id = " + id + "")) {
		if(null != f.getArr("book_id")) {
			courseBook.item("course_id", id);
			courseBook.item("site_id", siteId);
			for(int i = 0; i < f.getArr("book_id").length; i++) {
				courseBook.item("book_id", f.getArr("book_id")[i]);
				if(!courseBook.insert()) { }
			}
		}
	}

	//\uac15\uc0ac
	if(-1 != courseTutor.execute("DELETE FROM " + courseTutor.table + " WHERE course_id = " + id + "")) {
		if(null != f.getArr("major_tutor_id")) {
			courseTutor.item("course_id", id);
			courseTutor.item("site_id", siteId);
			courseTutor.item("type", "major");
			for(int i = 0; i < f.getArr("major_tutor_id").length; i++) {
				courseTutor.item("user_id", f.getArr("major_tutor_id")[i]);
				if(!courseTutor.insert()) { }
			}
		}
	}

	//\uacfc\uc815\ub2f4\ub2f9\uc790
	if(adminBlock && -1 != courseManager.execute("DELETE FROM " + courseManager.table + " WHERE course_id = " + id + "")) {
		if(null != f.getArr("manager_id")) {
			courseManager.item("course_id", id);
			courseManager.item("site_id", siteId);
			for(int i = 0; i < f.getArr("manager_id").length; i++) {
				courseManager.item("user_id", f.getArr("manager_id")[i]);
				if(!courseManager.insert()) { }
			}
		}
	}

	//\uadf8\ub8f9
	if(-1 != courseTarget.execute("DELETE FROM " + courseTarget.table + " WHERE course_id = " + id + "")) {
		if(null != f.getArr("group_id")) {
			courseTarget.item("course_id", id);
			courseTarget.item("site_id", siteId);
			for(int i = 0; i < f.getArr("group_id").length; i++) {
				courseTarget.item("group_id", f.getArr("group_id")[i]);
				if(!courseTarget.insert()) { }
			}
		}
	}

	//\uc120\ud589
	if(-1 != coursePrecede.execute("DELETE FROM " + coursePrecede.table + " WHERE course_id = " + id + "")) {
		if(null != f.getArr("precede_id")) {
			coursePrecede.item("course_id", id);
			coursePrecede.item("site_id", siteId);
			for(int i = 0; i < f.getArr("precede_id").length; i++) {
				coursePrecede.item("precede_id", f.getArr("precede_id")[i]);
				if(!coursePrecede.insert()) { }
			}
		}
	}

	//\ud30c\uc77c\ub9ac\uc0ac\uc774\uc9d5
	if(isUpload) {
		try {
			String imgPath = m.getUploadPath(f.getFileName("course_file"));
			String cmd = "convert -resize 1000x> " + imgPath + " " + imgPath;
			Runtime.getRuntime().exec(cmd);
		}
		catch(RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage(), re); }
		catch(Exception e) { m.errorLog("Exception : " + e.getMessage(), e); }
	}

	m.jsAlert("\uc131\uacf5\uc801\uc73c\ub85c \uc218\uc815\ud588\uc2b5\ub2c8\ub2e4.");
	m.jsReplace("course_modify.jsp?" + m.qs(), "parent");
	return;
}

//\ud3ec\uba67\ud305
info.put("content1", m.htt(info.s("content1")));
info.put("course_file_conv", m.encode(info.s("course_file")));
info.put("course_file_url", m.getUploadUrl(info.s("course_file")));
info.put("course_file_ek", m.encrypt(info.s("course_file") + m.time("yyyyMMdd")));

int userCnt = courseUser.findCount("course_id = " + id + " AND status != -1");
boolean isModify = 0 == userCnt; //\uc218\uc815\uac00\ub2a5\uc5ec\ubd80
info.put("delete_block", isModify);

//\ubaa9\ub85d-\ub3c4\uc11c
DataSet books = courseBook.query(
	"SELECT a.*, b.book_nm "
	+ " FROM " + courseBook.table + " a "
	+ " INNER JOIN " + book.table + " b ON a.book_id = b.id "
	+ " WHERE a.course_id = " + id + ""
);

//\ubaa9\ub85d-\uac15\uc0ac
DataSet tutors = courseTutor.query(
	"SELECT a.*, t.tutor_nm "
	+ " FROM " + courseTutor.table + " a "
	+ " INNER JOIN " + tutor.table + " t ON t.user_id = a.user_id "
	+ " WHERE a.course_id = " + id + ""
);

//\ubaa9\ub85d-\uacfc\uc815\ub2f4\ub2f9\uc790
DataSet managers = courseManager.query(
	"SELECT a.*, u.user_nm manager_nm, u.login_id "
	+ " FROM " + courseManager.table + " a "
	+ " INNER JOIN " + user.table + " u ON u.id = a.user_id "
	+ " WHERE a.course_id = " + id + " AND u.site_id = " + siteId + " AND u.status != -1 "
);

//\ubaa9\ub85d-\ub300\uc0c1\uc790
DataSet targets = courseTarget.query(
	"SELECT a.*, g.group_nm "
	+ " FROM " + courseTarget.table + " a "
	+ " INNER JOIN " + group.table + " g ON a.group_id = g.id AND g.site_id = " + siteId + " "
	+ " WHERE a.course_id = " + id + ""
);

//\ubaa9\ub85d-\uc120\ud589
DataSet pcourses = coursePrecede.query(
	"SELECT c.* "
	+ " FROM " + coursePrecede.table + " a "
	+ " INNER JOIN " + course.table + " c ON a.precede_id = c.id "
	+ " WHERE a.course_id = " + id + ""
);
while(pcourses.next()) {
	pcourses.put("course_nm_conv", m.cutString(pcourses.s("course_nm"), 40));
	pcourses.put("status_conv", m.getItem(pcourses.s("status"), course.statusList));
	pcourses.put("display_conv", pcourses.b("display_yn") ? "\uc815\uc0c1" : "\uc228\uae40");
	pcourses.put("type_conv", m.getItem(pcourses.s("course_type"), course.types));
	pcourses.put("onoff_type_conv", m.getItem(pcourses.s("onoff_type"), course.onoffTypes));

	pcourses.put("alltimes_block", "A".equals(pcourses.s("course_type")));
	pcourses.put("request_sdate_conv", m.time("yyyy.MM.dd", pcourses.s("request_sdate")));
	pcourses.put("request_edate_conv", m.time("yyyy.MM.dd", pcourses.s("request_edate")));
	pcourses.put("study_sdate_conv", m.time("yyyy.MM.dd", pcourses.s("study_sdate")));
	pcourses.put("study_edate_conv", m.time("yyyy.MM.dd", pcourses.s("study_edate")));
}

//\ucd9c\ub825
p.setBody("course.course_insert");
p.setVar("list_query", m.qs("id"));
p.setVar("query", m.qs());
p.setVar("form_script", f.getScript());

p.setVar(info);
p.setVar("modify", true);
p.setVar("admin_block", adminBlock);
p.setVar("is_package", isPackage);

p.setLoop("years", mcal.getYears());
p.setLoop("types", m.arr2loop(course.types));
//p.setLoop("managers", user.getManagers(siteId, "C|S"));

p.setLoop("books", books);
p.setLoop("tutors", tutors);
p.setLoop("managers", managers);
p.setLoop("targets", targets);
p.setLoop("pcourses", pcourses);

p.setLoop("sale_yn", m.arr2loop(course.saleYn));
p.setLoop("display_yn", m.arr2loop(course.displayYn));
p.setLoop("taxfree_yn", m.arr2loop(course.taxfreeYn));
p.setLoop("status_list", m.arr2loop(course.statusList));
p.setVar("template_block", "Y".equals(siteconfig.s("cert_template_yn")));
p.setVar("playrate_block", usePlayrate);
p.setLoop("template_list", certificateTemplate.getList(siteId));
p.setLoop("pf_types", m.arr2loop(course.postfixType));
p.setLoop("pf_ord_list", m.arr2loop(course.postfixOrd));

p.setLoop("grades", m.arr2loop(course.grades));
p.setLoop("terms", m.arr2loop(course.terms));
p.setLoop("subjects", m.arr2loop(course.subjects));

p.setVar("closed", closed);
p.setVar("tab_modify", "current");
p.setVar("cid", id);
p.display();


    out.write(_jsp_string0, 0, _jsp_string0.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5413665724253103304L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/course/course_modify.jsp"), -4449961483057009039L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/course/init.jsp"), 4867222188672443604L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 4999103467299093826L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n".toCharArray();
  }
}
