/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._sysop._management;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _exam_0user_0view__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();
String tplRoot = Config.getDocRoot() + "/sysop/html";

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch (RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage()); return; }
catch (Exception ex) { m.errorLog("\uc81c\ud55c \uc6a9\ub7c9 \ucd08\uacfc - " + ex.getMessage()); return; }

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/Users/kyounghokim/IdeaProjects/MalgnLMS/public_html/html");

SiteDao Site = new SiteDao();
DataSet siteinfo = Site.getSiteInfo(request.getServerName(), "sysop");
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("sysop_status") || "".equals(siteinfo.s("doc_root"))) { m.jsReplace("/main/guide.jsp", "top"); return; }
//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 60\ubd84
siteinfo.put("sysop_session_hour", 60);
//B2b\uc0ac\uc6a9X
SiteConfig.put("join_b2b_yn", "N");

//String siteDomain = request.getScheme() + "://" + request.getServerName();
String siteDomain = "https://" + request.getServerName();
/*int port = request.getServerPort();
if(port != 80) siteDomain += ":" + port;*/
String webUrl = siteDomain + "/sysop";

String dataDir = siteinfo.s("doc_root") + "/data";
f.dataDir = dataDir;
m.dataDir = dataDir;
//m.dataUrl = Config.getDataUrl() + (!"/data".equals(Config.getDataUrl()) ? siteinfo.s("ftp_id") : "");
m.dataUrl = Config.getDataUrl();

boolean isDevServer = -1 < request.getServerName().indexOf("lms.malgn.co.kr");
siteinfo.put("logo_url", (!"/data".equals(Config.getDataUrl()) ? "" : siteDomain) + m.getUploadUrl(siteinfo.s("logo")));

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr(); //Lb \uc0ac\uc6a9
if(userIp.contains(",")) {
	String[] userIpArr = m.split(",", userIp);
	userIp = userIpArr[0].trim();
}
boolean isMalgnOffice = "1.212.252.90|3.35.211.181|52.79.184.225|127.0.0.1".contains(userIp);
if(!"".equals(siteinfo.s("allow_ip_sysop")) && !isMalgnOffice && !Site.checkIP(userIp, siteinfo.s("allow_ip_sysop"))) {
	m.redirect("/");
	return;
}

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
//String sysLocale = "default";
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

//\uae30\ubcf8 \ud68c\uc6d0\uc815\ubcf4
int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
String manageCourses = "";
String userSessionId = "";
String pagreeDate = "";
boolean isUserMaster = false;
String winTitle = "[\uad00\ub9ac\uc790] " + siteinfo.s("site_nm");
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
String surl = request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : "");
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));
final int sysExcelCnt = 20000;

SessionDao mSession = new SessionDao(request, response);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "MLMSKEY2014" + siteId + "7";
if(0 < siteinfo.i("sysop_session_hour")) auth.setValidTime(siteinfo.i("sysop_session_hour") * 60);
if(auth.isValid()) {
	userId = m.parseInt(auth.getString("ID"));
	loginId = auth.getString("LOGINID");
	userName = auth.getString("NAME");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	manageCourses = auth.getString("MANAGE_COURSES");
	userSessionId = userSessionId = auth.getString("SESSIONID");
	pagreeDate = auth.getString("PAGREE_DATE");
	isUserMaster = "Y".equals(auth.getString("IS_USER_MASTER"));

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if(request.getRequestURI().indexOf("/main/auth2.jsp") == -1
		//&& "Y".equals(siteinfo.s("auth2_yn"))
		&& !"Y".equals(auth.getString("AUTH2_YN"))
		//&& !"".equals(siteinfo.s("auth2_type"))
		//&& !"malgn".equals(loginId)
		&& request.getRequestURI().indexOf("/main/otpkey_register.jsp") == -1
		&& request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1
		&& request.getRequestURI().indexOf("/main/modify_passwd.jsp") == -1
	) {
		m.jsReplace("/sysop/main/auth2.jsp?returl=" + m.rs("returl", "/sysop/index.jsp"), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& -1 == request.getRequestURI().indexOf("/sysop/main/logout.jsp")
		&& -1 == request.getRequestURI().indexOf("/sysop/main/login.jsp")
		&& -1 == request.getRequestURI().indexOf("/main/modify_passwd.jsp")
	) {
		m.jsReplace("/sysop/main/logout.jsp");
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

} else {
	if(request.getRequestURI().indexOf("/main/login.jsp") == -1
		&& request.getRequestURI().indexOf("/vod/upload.jsp") == -1
		&& request.getRequestURI().indexOf("/main/slogin.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_template.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_maildir.jsp") == -1
		&& (request.getRequestURI().indexOf("/user/sleep_insert.jsp") == -1 || !"log".equals(m.rs("after")))
	) {
		m.jsReplace(auth.loginURL, "top");
		return;
	}
}

MenuDao Menu = new MenuDao(p, siteId, "default");
SiteMenuDao SiteMenu = new SiteMenuDao();

boolean superBlock = "S".equals(userKind);
boolean adminBlock = "S".equals(userKind) || "A".equals(userKind);
boolean courseManagerBlock = "C".equals(userKind);
boolean deptManagerBlock = "D".equals(userKind);

//boolean isAuthCrm = superBlock || (-1 < siteinfo.s("auth_crm").indexOf("|" + userKind + "|"));
boolean isAuthCrm = superBlock || Menu.accessible(-999, userId, userKind, false);

//\ub85c\uadf8\uc544\uc6c3-\uacfc\uc815\uc6b4\uc601\uc790
if(courseManagerBlock && "".equals(manageCourses) && request.getRequestURI().indexOf("/main/logout.jsp") == -1) {
	m.jsAlert("\ub2f4\ub2f9\ud55c \uacfc\uc815\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\\n \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc138\uc694.");
	m.jsReplace("/sysop/main/logout.jsp", "top");
	return;
}

//\ub9e4\ub274\uc5bc
ManualDao Manual = new ManualDao();
int ManualId = Menu.getOneInt("SELECT manual_id FROM " + Menu.table + " WHERE link = '" + m.replace(request.getRequestURI(), "/sysop", "..") + "'");
if(0 < ManualId) {
	int ManualStatus = Manual.getOneInt("SELECT status FROM " + Manual.table + " WHERE id = " + ManualId);
	if(0 < ManualStatus) p.setVar("SYS_MENU_MANUAL_ID", ManualId);
}

p.setVar("WEB_URL", webUrl);
p.setVar("FRONT_URL", siteDomain);
p.setVar("SYS_TITLE", winTitle);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("IS_AUTH_CRM", isAuthCrm);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_COMMON_CDN", "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);

p.setVar("user_master_block", isUserMaster || isMalgnOffice);
p.setVar("malgn_office_block", isMalgnOffice);
p.setVar("super_block", superBlock);
p.setVar("admin_block", adminBlock);
p.setVar("course_manager_block", courseManagerBlock);
p.setVar("dept_manager_block", deptManagerBlock);
p.setVar("SYS_URL", surl);

//boolean isBlindUser = !sysToday.equals(pagreeDate);
//p.setVar("SYS_BLINDUSER", isBlindUser);

//\uac1c\uc778\uc815\ubcf4\ucc98\ub9ac \uc218\uc815 - 2024.03.25
boolean isBlindUser = !"Y".equals(m.getCookie("PCONFIRM_YN"));
p.setVar("SYS_BLINDUSER", isBlindUser);
p.setVar("PCONFIRM_YN", m.getCookie("PCONFIRM_YN"));
String inquiryPurpose = m.getCookie("INQUIRYPURPOSE");

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
UserSession.setType("sysop");
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && "N".equals(siteinfo.s("dup_sysop_yn")) && ("".equals(userSessionId) || userSessionId == null || !UserSession.isValid(userSessionId, userId))) {
	if(request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1) {
		m.jsAlert("\uc138\uc158\uc774 \ub9cc\ub8cc\ub418\uc5c8\uac70\ub098 \uc911\ubcf5 \ub85c\uadf8\uc778\uc774 \ub418\uc5b4 \uc790\ub3d9\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ub429\ub2c8\ub2e4.");
		m.jsReplace("/sysop/main/logout.jsp?mode=session", "top");
		return;
	}
}

InfoLogDao _log = new InfoLogDao(siteId); _log.setItems(userId, "B", surl, userIp);
InfoUserDao _logUser = new InfoUserDao(siteId);


    

String ch = "sysop";

//\uacfc\uc815
CourseDao course = new CourseDao();
DataSet cinfo = new DataSet();
int courseId = m.ri("cid");
String ptitle = "";
boolean alltime = false;
if(courseId > 0) {
	cinfo = course.find(
		"id = " + courseId + " AND site_id = " + siteId + " AND status != -1"
		+ ("C".equals(userKind) ? " AND id IN (" + manageCourses + ") " : "")
	);
	if(!cinfo.next()) { m.jsAlert("\ud574\ub2f9 \uacfc\uc815\uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }
	ptitle = "<span style='color:#666666'>[" + cinfo.s("year") + "\ub144/" + cinfo.s("step") + "\uae30]</span> "
		+ "<span style='color:#4C5BA9'>" + cinfo.s("course_nm") + "</span>";

	cinfo.put("std_progress", m.nf(cinfo.i("assign_progress") * cinfo.i("limit_progress") / 100, 1));
	cinfo.put("std_exam", m.nf(cinfo.i("assign_exam") * cinfo.i("limit_exam") / 100, 1));
	cinfo.put("std_homework", m.nf(cinfo.i("assign_homework") * cinfo.i("limit_homework") / 100, 1));
	cinfo.put("std_forum", m.nf(cinfo.i("assign_forum") * cinfo.i("limit_forum") / 100, 1));
	cinfo.put("std_etc", m.nf(cinfo.i("assign_etc") * cinfo.i("limit_etc") / 100, 1));

	cinfo.put("study_sdate_conv", m.time("yyyy-MM-dd", cinfo.s("study_sdate")));
	cinfo.put("study_edate_conv", m.time("yyyy-MM-dd", cinfo.s("study_edate")));

	alltime = "A".equals(cinfo.s("course_type"));
	cinfo.put("alltime_block", alltime);

	cinfo.put("attend_block", !"N".equals(cinfo.s("onoff_type")));

	p.setVar("course", cinfo);
}

p.setVar("auth_course_block", Menu.accessible(33, userId, userKind, false));
p.setVar("auth_management_block", Menu.accessible(75, userId, userKind, false));
p.setVar("auth_complete_block", Menu.accessible(76, userId, userKind, false));
p.setVar("auth_auto_block", Menu.accessible(42, userId, userKind, false));


    

//MANAGEMENT

//\uc811\uadfc\uad8c\ud55c
if(!Menu.accessible(75, userId, userKind)) { m.jsErrClose("\uc811\uadfc \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uae30\ubcf8\ud0a4
int eid = m.ri("eid");
int cuid = m.ri("cuid");
if(eid == 0 || cuid == 0) { m.jsErrClose("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); return; }

//PDF
String type = m.rs("type");
if("pdf".equals(type)) {
	String url = webUrl + "/management/exam_user_view.jsp?eid=" + eid + "&cuid=" + cuid;
	String path = dataDir + "/tmp/" + m.getUniqId() + ".pdf";
	String cmd = "/usr/local/bin/wkhtmltopdf -s A4 "
			+ " --cookie MLMSKEY2014" + siteId + "7 " + m.getCookie("MLMS14" + siteId + "7")
			+ (siteId > 1 ? " --disable-smart-shrinking " : "")
			+ " " + url + " " + path;

	m.exec(cmd);
	m.output(path, null);
	m.delFile(path);
	return;
}

//\uac1d\uccb4
ExamDao exam = new ExamDao();
ExamUserDao examUser = new ExamUserDao();
QuestionDao question = new QuestionDao();
ExamResultDao examResult = new ExamResultDao();
CourseUserDao courseUser = new CourseUserDao();
CourseModuleDao courseModule = new CourseModuleDao();
UserDao user = new UserDao(isBlindUser);
UserDeptDao userDept = new UserDeptDao();

//\ubcc0\uc218
String whrPk = "";
boolean	printBlock = "print".equals(m.rs("mode"));

//\ud3c9\uac00\uc751\uc2dc\uc790\uc815\ubcf4
DataSet euinfo = examUser.query(
	"SELECT a.course_user_id, a.course_id, a.confirm_yn, a.user_id, a.score eu_score, a.marking_score eu_marking_score, a.exam_step, a.reg_date exam_user_reg_date "
	+ ", c.course_nm, c.year, c.step "
	+ ", e.user_nm, f.module_nm, f.assign_score cm_assign_score "
	+ ", g.* "
	+ " FROM " + examUser.table + " a "
	+ " INNER JOIN " + course.table + " c ON a.course_id = c.id "
	+ " INNER JOIN " + user.table + "  e ON a.user_id = e.id " + (deptManagerBlock ? " AND e.dept_id IN (" + userDept.getSubIdx(siteId, userDeptId) + ") " : "")
	+ " INNER JOIN " + courseModule.table + " f ON a.exam_id = f.module_id AND a.course_id = f.course_id AND f.module = 'exam' "
	+ " INNER JOIN " + exam.table + " g ON a.exam_id = g.id "
	+ " WHERE a.exam_id = " + eid + " AND a.course_user_id = " + cuid + " "
);
if(!euinfo.next()) { m.jsErrClose("\uc751\uc2dc\uc815\ubcf4\ub97c \uc54c\uc218 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }
euinfo.put("reg_date_conv", m.time("yyyy.MM.dd HH:mm", euinfo.s("reg_date")));
euinfo.put("exam_user_reg_date_conv", m.time("yyyy.MM.dd HH:mm", euinfo.s("exam_user_reg_date")));
user.maskInfo(euinfo);

//\uae30\ub85d-\uac1c\uc778\uc815\ubcf4\uc870\ud68c
if("".equals(m.rs("mode")) && euinfo.size() > 0 && !isBlindUser) _log.add("V", Menu.menuNm, euinfo.size(), "\uc774\ub7ec\ub2dd \uc6b4\uc601", euinfo);

//\ucc44\uc810\uc5ec\ubd80
boolean isConfirm = "Y".equals(euinfo.s("confirm_yn"));

//\uc810\uc218\uc800\uc7a5
if(m.isPost() && f.validate()) {
	String[] ilist = f.getArr("question_id");
	double total = 0;
	for(int i=0; i<ilist.length; i++) {
		double score = m.parseDouble(f.getArr("score")[i]);
		examResult.item("score", score);
		examResult.update("exam_id = " + eid + " AND course_user_id = " + cuid + " AND exam_step = " + euinfo.i("exam_step") + " AND question_id = " + ilist[i] + "");
		total += score;
	}

	//\ucd1d\uc810 \uc800\uc7a5
	examUser.execute(
		"UPDATE " + examUser.table + " "
		+ " SET confirm_yn = 'Y' "
		+ ", score = " + Math.min(euinfo.d("cm_assign_score"), euinfo.d("cm_assign_score") * total / 100) + " "
		+ ", marking_score = " + Math.min(total, 100.0) + " "
		+ ", confirm_user_id = " + userId + " "
		+ ", confirm_date = '" + m.time("yyyyMMddHHmmss") + "' "
		+ " WHERE exam_id = " + eid + " AND course_user_id = " + cuid + " AND exam_step = " + euinfo.i("exam_step") + " "
	);

	//\uc810\uc218 \uc5c5\ub370\uc774\ud2b8
	courseUser.setCourseUserScore(cuid, "exam");

	out.print("<script>alert('\ucc44\uc810\uc774 \uc644\ub8cc\ub418\uc5c8\uc2b5\ub2c8\ub2e4.');opener.location.reload();window.close();</script>");
	return;
}

//\ud3c9\uac00\ubb38\uc81c\ubaa9\ub85d
ListManager lm = new ListManager(jndi);
//lm.d(out);
lm.setRequest(request);
lm.setListNum(1000);
lm.setTable(
	examResult.table + " a "
	+ " INNER JOIN " + question.table + " b ON a.question_id = b.id "
);
lm.setFields("a.question_id, a.answer user_answer, a.score, b.*");
lm.addWhere("a.status = 1");
lm.addWhere("a.exam_id = " + eid + "");
lm.addWhere("a.exam_step = " + euinfo.i("exam_step") + "");
lm.addWhere("a.course_user_id = " + cuid + "");
lm.addWhere("a.course_id = " + euinfo.i("course_id") + "");
lm.setOrderBy("a.question_id ASC");

//\ud3ec\ub9f7\ud305
String[] typeList = question.types;
DataSet list = lm.getDataSet();
while(list.next()) {
	boolean isAuto = list.i("question_type") <= 3;
	list.put("ox_block", isAuto);
	list.put("ans_block", list.i("question_type") == 3);
	list.put("choice_block", list.i("question_type") <= 2);
	list.put("textarea_block", list.i("question_type") == 4);
	list.put("input_type", list.i("question_type") == 1 ? "radio" : (list.i("question_type") == 2 ? "checkbox" : "text"));
	list.put("assign_score", euinfo.i("assign" + list.s("grade")));
	list.put("question_file_url", m.getUploadUrl(list.s("question_file")));
	list.put("question_text", list.s("question_text").trim());
	list.put("description_conv", m.nl2br(list.s("description")));
	list.put("user_answer_conv", m.htmlToText(list.s("user_answer")));

	Vector<Hashtable<String, Object>> items = new Vector<Hashtable<String, Object>>();
	String answer = "||" + list.s("answer").trim() + "||";

	for(int i = 1; i <= list.i("item_cnt"); i++) {
		Hashtable<String, Object> tmp = new Hashtable<String, Object>();
		tmp.put("id", i + "");
		tmp.put("name", list.s("item" + i));
		tmp.put("file", !"".equals(list.s("item" + i + "_file")) ? m.getUploadUrl(list.s("item" + i + "_file")) : "");

		tmp.put("is_answer", "");
		tmp.put("is_answer_txt", "");
		if(answer.indexOf("||" + i + "||") != -1) {
			tmp.put("is_answer", "style=\"font-weight:normal;color:red\"");
			tmp.put("is_answer_txt", "<font style=\"font-weight:normal;\"> [\uc815\ub2f5]</font>");
		}
		items.add(tmp);
	}

	boolean isCorrect = false;
	if("2".equals(list.s("question_type"))) {
		String[] ans1 = list.s("answer").split("\\|\\|");
		String[] ans2 = list.s("user_answer").split("\\|\\|");
		Arrays.sort(ans1);
		Arrays.sort(ans2);

		if(ans1.length == ans2.length) {
			isCorrect = true;
			for(int i=0, max=ans1.length; i<max; i++) {
				if(!ans1[i].equals(ans2[i])) { isCorrect = false; break; }
			}
		}
	} else if(!"4".equals(list.s("question_type"))) {
		isCorrect = list.s("user_answer").equals(list.s("answer"));
	}


	list.put("collect_yn", isCorrect
		? "<font style=\"font-family:tahoma;font-weight:bold;font-size:18px;color:blue;\">O</font>"
		: (isAuto ? "<font style=\"font-family:tahoma;font-weight:bold;font-size:18px;color:red;\">X</font>" : "<font style=\"font-family:tahoma;font-weight:bold;font-size:18px;color:black;\">-</font>")
	);
	if(isConfirm) {
		list.put("score", list.d("score"));
	} else {
		list.put("score", isCorrect ? list.i("assign_score") : 0);
		if(!isCorrect && !isAuto) list.put("score", "");
	}

	//if("Y".equals(info.s("shuffle_yn"))) Collections.shuffle(items);

	DataSet answers = new DataSet();
	for(int i=1; i<=items.size(); i++) {
		answers.addRow(items.get(i - 1));
	}
	list.put("question_type_conv", m.getItem(list.s("question_type"), typeList));
	list.put("grade", m.getItem(list.s("grade"), question.grades));
	list.put(".subLoop", answers);
}

//\ucd9c\ub825
p.setLayout(!printBlock ? "pop" : "blank");
p.setBody("management.exam_user_view" + (!printBlock ? "" : "_div"));
p.setVar("p_title", "\uc2dc\ud5d8 \ud3c9\uac00");
p.setVar("query", m.qs());

p.setVar("euinfo", euinfo);
p.setLoop("list", list);

p.setVar("print_block", printBlock);
p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/management/exam_user_view.jsp"), -8836962437917192955L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/management/init.jsp"), -7835635302239791729L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 9197471702019162279L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
