/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._exsignon._sso;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _slo__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, null, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    

/*
\uc778\uc99d\uc11c\ubc84\uc5d0 \ud1b5\ud569\ub85c\uadf8\uc544\uc6c3 \uc694\uccad\uc774 \ub4e4\uc5b4\uc624\uba74, \ub85c\uadf8\uc778 \ub418\uc5b4 \uc788\ub294 \ubaa8\ub4e0 \uc5f0\uacc4\uc2dc\uc2a4\ud15c\uc5d0\uc11c \uc77c\uad04\uc801\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ucc98\ub9ac\ub97c \uc2dc\ucf1c\uc57c \ud55c\ub2e4.
\ub54c\ubb38\uc5d0 \ud0c0 \uc5f0\uacc4\uc2dc\uc2a4\ud15c\uc5d0\uc11c \ud1b5\ud569\ub85c\uadf8\uc544\uc6c3\uc744 \uc694\uccad\ud588\uc744 \ub54c\uc5d0 \ud604\uc7ac\uc758 \uc5f0\uacc4\uc2dc\uc2a4\ud15c\uc744 \ub85c\uadf8\uc544\uc6c3 \uc2dc\ud0a4\uae30 \uc704\ud574 \uc774 \ud30c\uc77c\uc744 \ud638\ucd9c\ud55c\ub2e4.
\ub9cc\uc77c \ub85c\uadf8\uc544\uc6c3 \uc804\ucc98\ub9ac\uac00 \ud544\uc694\ud560 \uacbd\uc6b0 \uc138\uc158 \ub9cc\ub8cc \uc774\uc804\uc5d0 \uc791\uc5c5\uc774 \uac00\ub2a5\ud558\ub2e4.
*/

// TO DO...(\ub85c\uadf8\uc544\uc6c3 \uc804\ucc98\ub9ac)

// \uc138\uc158 \ub9cc\ub8cc
HttpSession session = request.getSession();
session.invalidate();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("exsignon/sso/slo.jsp"), 8626105640316444912L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
