/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._mypage;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.regex.Pattern;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

//request.setCharacterEncoding("utf-8");

final String BUILDVERSION = "24.02.01";

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(RuntimeException re) {
	m.errorLog("Overflow file size. - " + re.getMessage(), re);
	return;
}
catch(Exception ex) {
	m.errorLog("Overflow file size. - " + ex.getMessage(), ex);
	return;
}

SiteDao Site = new SiteDao(); //Site.clear();
DataSet siteinfo = Site.getSiteInfo(request.getServerName());
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("status") || "".equals(siteinfo.s("doc_root"))) {
	//m.jsReplace("about:blank", "top");
	return;
}

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//CSAP \uc18c\uc15c \ub85c\uadf8\uc778 \uc0ac\uc6a9 \uc548\ud568
siteinfo.put("oauth_vendor", "");
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 1\uc2dc\uac04
siteinfo.put("session_hour", 1);
//\uacb0\uc81c\ud398\uc774\uc9c0 \uc548\ub0b4 \ubb38\uad6c
String allowTags = "a,b,br,cite,code,dd,dl,dt,div,em,i,li,ol,p,pre,q,small,span,strike,strong,sub,sup,u,ul,article,aside,details,div,dt,figcaption,footer,form,fieldset,header,hgroup,html,main,nav,section,summary,body,p,dl,multicol,dd,figure,address,center,blockquote,h1,h2,h3,h4,h5,h6,listing,xmp,pre,plaintext,menu,dir,ul,ol,li,hr,table,tbody,thead,tfoot,th,tr,td,caption,textarea,img,input,textarea,hr,iframe,video,audio";
String allowRegexr = "<(\\/?)(?!.*" + Malgn.replace(allowTags, ",", "[ >]|.*") + "[ >])([^>]*)>";
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));
boolean isDevServer = -1 < request.getServerName().indexOf("politech.malgn.co.kr");
String webUrl = request.getScheme() + "://" + request.getServerName();
int port = request.getServerPort();
if(port != 80 && port != 443) webUrl += ":" + port;
String dataDir = siteinfo.s("doc_root") + "/data";
String tplRoot = siteinfo.s("doc_root") + "/html";
f.dataDir = dataDir;
m.dataDir = dataDir;
m.dataUrl = Config.getDataUrl();

if(!"".equals(siteinfo.s("logo"))) siteinfo.put("logo_url", m.getUploadUrl(siteinfo.s("logo")));
else siteinfo.put("logo_url", "/common/images/default/malgn_logo.jpg");

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr();
if(!"".equals(siteinfo.s("allow_ip_user")) && !Site.checkIP(userIp, siteinfo.s("allow_ip_user"))) {
	m.redirect("/main/guide.jsp");
	return;
}

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/Users/kyounghokim/IdeaProjects/MalgnLMS/public_html/html");

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String loginMethod = "";
String userName = "";
String userEmail = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
int userGroupDisc = 0;
//String aloginYn = "";
String userSessionId = "";
boolean userB2BBlock = false;
String userB2BName = "";
String userB2BFile = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean isRespWeb = (5 <= siteinfo.i("skin_cd"));
boolean isGoMobile = !isRespWeb && m.isMobile();
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));

SessionDao mSession = new SessionDao(request, response);

DataSet auth2Info = Config.getDataSet("//config/userAuth2");
auth2Info.next();

Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "MLMS14" + siteId + "7";
if(0 < siteinfo.i("session_hour")) auth.setValidTime(siteinfo.i("session_hour") * 3600);
if(auth.isValid()) {
	userId = auth.getInt("ID");
	loginId = auth.getString("LOGINID");
	loginMethod = auth.getString("LOGINMETHOD");
	userName = auth.getString("NAME");
	userEmail = auth.getString("EMAIL");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	userGroupDisc = !"null".equals(auth.getString("GROUPS_DISC")) ? m.parseInt(auth.getString("GROUPS_DISC")) : 0;
	//aloginYn = auth.getString("ALOGIN_YN");
	userSessionId = auth.getString("SESSIONID");
	userB2BName = auth.getString("B2BNAME");
	userB2BFile = auth.getString("B2BFILE");
	if(userGroups != null) {
		if(-1 < userGroups.indexOf(",")) for(String userGroupId : m.split(",", userGroups)) p.setVar("SYS_USERGROUP_" + userGroupId, true);
		else p.setVar("SYS_USERGROUP_" + userGroups, true);
	}

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if("direct".equals(loginMethod)
		&& "Y".equals(auth2Info.s("auth2Yn"))
		&& !"Y".equals(auth.getString("USER_AUTH2_YN"))
		&& "Y".equals(auth.getString("DEPT_AUTH2_YN")) //\uad00\ub9ac\uc790\ub2e8-\ud68c\uc6d0\uc18c\uc18d\uad00\ub9ac\uc5d0\uc11c 2\ucc28\uc778\uc99d\uc124\uc815 \uc5ec\ubd80 Y/N	 20230126
		//&& !"".equals(auth.getString("USER_AUTH2_TYPE"))
		//&& !"malgn".equals(loginId)
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/auth2.jsp?returl=" + Malgn.urlencode(m.getThisURI()), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/logout.jsp");
		return;
	}

	if(
		(
			(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) //\uc0dd\ub144\uc6d4\uc77c
			|| (1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) //\uc131\ubcc4
			|| (1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) //\ud734\ub300\uc804\ud654\ubc88\ud638
			|| ("".equals(auth.getString("NAME"))) //\uc131\uba85
			|| ("".equals(auth.getString("EMAIL"))) //\uc774\uba54\uc77c
		)
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/member/privacy_agree.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_verify.jsp")
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		int tut = m.getUnixTime();
		String tek = m.encrypt(tut + "|" + loginId + "|7B1F83A608723CEDDFA9AED338FC796C", "SHA-256");
		String noInfoString = "";

		if(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) noInfoString = "\uc0dd\ub144\uc6d4\uc77c";
		else if(1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) noInfoString = "\uc131\ubcc4";
		else if(1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) noInfoString = "\ud734\ub300\uc804\ud654\ubc88\ud638";
		else if("".equals(auth.getString("NAME"))) noInfoString = "\uc131\uba85";
		else if("".equals(auth.getString("EMAIL"))) noInfoString = "\uc774\uba54\uc77c";
		m.jsAlert("\ud68c\uc6d0 \ud544\uc218 \uc815\ubcf4 [" + noInfoString + "](\uc774)\uac00 \ub204\ub77d\ub418\uc5b4\\n\uc218\uc815\ud398\uc774\uc9c0\ub85c \uc774\ub3d9\ud569\ub2c8\ub2e4.");
		m.jsReplace("/mypage/modify.jsp?ek=" + tek + "&ut=" + tut);
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

	p.setVar("login_block", true);
} else {
	p.setVar("login_block", false);

	if(siteinfo.b("close_yn")) {
		boolean isNeedLogin = true;
		String[] exceptPages = m.split("|", siteinfo.s("close_except"));

		if(-1 < request.getRequestURI().indexOf("/member/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/find.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/alogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin_input.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/sysop_slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/main/site_cache.jsp")
			|| -1 < request.getRequestURI().indexOf("/mobile/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate_course.jsp")
			|| -1 < request.getRequestURI().indexOf("/kollus/check_api.jsp")
			|| -1 < request.getRequestURI().indexOf("/common/")
			|| -1 < request.getRequestURI().indexOf("/api/auto_send.jsp")
		) {
			isNeedLogin = false;
		} else if(!"".equals(siteinfo.s("close_except"))) {
			for(int i = 0; i < exceptPages.length; i++) {
				if(-1 < request.getRequestURI().indexOf(exceptPages[i])) { isNeedLogin = false; continue; }
			}
		}

		if(isNeedLogin) {
			m.redirect(!isGoMobile ? auth.loginURL : "/mobile/login.jsp");
			return;
		}
	}
}

userB2BBlock = !"".equals(userB2BName) && null != userB2BName;
p.setVar("SYS_HTTPHOST", request.getServerName());
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERID", userId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SYS_DEPTID", userDeptId);
p.setVar("SYS_GROUP_DISC", userGroupDisc);
p.setVar("SYS_B2BBLOCK", userB2BBlock);
p.setVar("SYS_B2BNAME", userB2BName);
p.setVar("SYS_B2BFILE", userB2BFile);
p.setVar("SYS_PAGE_URL", request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : ""));
p.setVar("SYS_TITLE", siteinfo.s("site_nm"));
p.setVar("webUrl", webUrl);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("CURR_DATE", m.time("yyyyMMdd"));
p.setVar("SYS_EK", m.encrypt(loginId + siteinfo.s("sso_key") + m.time("yyyyMMdd"), "SHA-256"));
p.setVar("IS_RESP_WEB", isRespWeb);
p.setVar("IS_MOBILE", m.isMobile());
p.setVar("IS_GO_MOBILE", isGoMobile);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);
p.setVar("script", siteinfo.s("header_script"));

for(int IndexSkin = 1; IndexSkin < 5; IndexSkin++) {
	p.setVar("SKIN_LT_" + IndexSkin, siteinfo.i("skin_cd") < IndexSkin);
	p.setVar("SKIN_LTE_" + IndexSkin, siteinfo.i("skin_cd") <= IndexSkin);
	p.setVar("SKIN_GT_" + IndexSkin, siteinfo.i("skin_cd") > IndexSkin);
	p.setVar("SKIN_GTE_" + IndexSkin, siteinfo.i("skin_cd") >= IndexSkin);
}

MenuDao Menu = new MenuDao(p, sysLocale);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && !siteinfo.b("duplication_yn") && !UserSession.isValid(userSessionId, userId)) {
	if(request.getRequestURI().indexOf("/member/logout.jsp") == -1 && request.getRequestURI().indexOf("/mobile/logout.jsp") == -1) {
		m.jsAlert(_message.get("alert.common.logout_session"));
		if(request.getRequestURI().indexOf("/mobile/") != -1) m.jsReplace("/mobile/logout.jsp?mode=session");
		else m.jsReplace("/member/logout.jsp?mode=session");
		return;
	}
}


    out.write('\n');
    

//\ub85c\uadf8\uc778
if(0 == userId) { auth.loginForm(); return; }

//\uc815\ubcf4-\ud68c\uc6d0
UserDao user = new UserDao();

DataSet uinfo = user.find("id = " + userId + " AND status = 1");
if(!uinfo.next()) { m.jsError(_message.get("alert.member.nodata")); return; }
uinfo.put("mobile_conv", !"".equals(uinfo.s("mobile")) ? uinfo.s("mobile") : "");
//uinfo.put("mobile", !"".equals(uinfo.s("mobile")) ? SimpleAES.decrypt(uinfo.s("mobile")) : "");
String ch = !userB2BBlock ? m.rs("ch", "mypage") : "b2b";


    

String key = "7B1F83A608723CEDDFA9AED338FC796C";
String ek = m.rs("ek");
int ut = m.ri("ut");

if("".equals(ek) || 1 > ut) { m.jsReplace("modify_verify.jsp"); return; }
if(!ek.equals(m.encrypt(ut + "|" + loginId + "|" + key, "SHA-256"))) { m.jsError("\uc62c\ubc14\ub978 \uc811\uadfc\uc774 \uc544\ub2d9\ub2c8\ub2e4."); return; }
if(m.getUnixTime() - ut > 3600) {
	m.jsAlert("\uc785\ub825\uc2dc\uac04\uc774 \ub9cc\ub8cc\ub418\uc5c8\uc2b5\ub2c8\ub2e4. \ub2e4\uc2dc \uc9c4\ud589\ud574\uc8fc\uc2dc\uae30 \ubc14\ub78d\ub2c8\ub2e4.");
	m.jsReplace("modify_verify.jsp");
	return;
}

//SSO
boolean isSSO = siteinfo.b("sso_yn") && !"".equals(siteinfo.s("sso_url"));

//\uac1d\uccb4
MCal mcal = new MCal(); mcal.yearRange = 50;
FileDao file = new FileDao();
UserDeptDao userDept = new UserDeptDao();
AgreementLogDao agreementLog = new AgreementLogDao(p, siteId);
MailDao mail = new MailDao();

//\uc815\ubcf4-\uc0ac\uc774\ud2b8\uc124\uc815
DataSet siteconfig = SiteConfig.getArr(new String[] {"join_", "modify_", "user_etc_"});

//\uc774\ub3d9-\uac00\uc785\uc124\uc815\uc0ac\uc6a9\uc5ec\ubd80
if("Y".equals(siteconfig.s("join_config_yn")) && !isSSO) {
	m.redirect("modify2.jsp?" + m.qs());
	return;
}

//\ubcc0\uc218
boolean isAuth = (siteinfo.b("auth_yn") || siteinfo.b("ipin_yn"));

if(!isSSO) {

	String[] uemail = m.split("@", uinfo.s("email"), 2);
	String[] mobile = m.split("-", uinfo.s("mobile_conv"), 3);

	int userFileId = 0;
	if(!"".equals(uinfo.s("user_file"))) {
		userFileId = file.getOneInt("SELECT id FROM " + file.table + " WHERE module = 'user' AND module_id = ? AND site_id = ? ORDER BY id DESC", new Integer[] {userId, siteId});
	}

	//\ud3fc\uccb4\ud06c
	f.addElement("passwd", null, "hname:'\ube44\ubc00\ubc88\ud638'");
	f.addElement("passwd2", null, "hname:'\ube44\ubc00\ubc88\ud638', match:'passwd'");
	if(!isAuth && "".equals(uinfo.s("user_nm"))) f.addElement("user_nm", uinfo.s("user_nm"), "hname:'\uc131\uba85', required:'Y'");
	if(!isAuth) f.addElement("birthday_year", m.time("yyyy", uinfo.s("birthday")), "hname:'\uc0dd\ub144\uc6d4\uc77c(\ub144\ub3c4)'" + (1 < siteconfig.i("join_birthday_status") ? ", required:'Y'" : ""));
	if(!isAuth) f.addElement("birthday_month", m.time("MM", uinfo.s("birthday")), "hname:'\uc0dd\ub144\uc6d4\uc77c(\uc6d4)'" + (1 < siteconfig.i("join_birthday_status") ? ", required:'Y'" : ""));
	if(!isAuth) f.addElement("birthday_day", m.time("dd", uinfo.s("birthday")), "hname:'\uc0dd\ub144\uc6d4\uc77c(\uc77c)'" + (1 < siteconfig.i("join_birthday_status") ? ", required:'Y'" : ""));
	f.addElement("dept_id", uinfo.i("dept_id"), "hname:'\uc18c\uc18d', required:'Y'");
	if(!isAuth) f.addElement("gender", uinfo.s("gender"), "hname:'\uc131\ubcc4'" + (1 < siteconfig.i("join_gender_status") ? ", required:'Y'" : ""));
	f.addElement("zipcode", uinfo.s("zipcode"), "hname:'\uc6b0\ud3b8\ubc88\ud638'");
	f.addElement("addr", uinfo.s("addr"), "hname:'\uad6c \uc8fc\uc18c'");
	f.addElement("new_addr", uinfo.s("new_addr"), "hname:'\ub3c4\ub85c\uba85 \uc8fc\uc18c'");
	f.addElement("addr_dtl", uinfo.s("addr_dtl"), "hname:'\uc0c1\uc138\uc8fc\uc18c'");
	if(!isAuth) f.addElement("mobile1", mobile[0], "hname:'\ud734\ub300\ud3f0\ubc88\ud638'" + (1 < siteconfig.i("join_mobile_status") ? ", required:'Y'" : ""));
	if(!isAuth) f.addElement("mobile2", mobile[1], "hname:'\ud734\ub300\ud3f0\ubc88\ud638'" + (1 < siteconfig.i("join_mobile_status") ? ", required:'Y'" : ""));
	if(!isAuth) f.addElement("mobile3", mobile[2], "hname:'\ud734\ub300\ud3f0\ubc88\ud638'" + (1 < siteconfig.i("join_mobile_status") ? ", required:'Y'" : ""));
	f.addElement("email1", uemail[0], "hname:'\uc774\uba54\uc77c', required:'Y'");
	f.addElement("email2", uemail[1], "hname:'\uc774\uba54\uc77c', required:'Y'");
	f.addElement("user_file", null, "hname:'\uc0ac\uc9c4'");
	f.addElement("user_file_k", userFileId, "hname:'\uc0ac\uc9c4'");
	f.addElement("user_file_ek", m.sha256(userFileId + "_userfile_" + userId), "hname:'\uc0ac\uc9c4'");
	f.addElement("email_yn", uinfo.s("email_yn"), "hname:'\uc774\uba54\uc77c\uc218\uc2e0\ub3d9\uc758'");
	f.addElement("sms_yn", uinfo.s("sms_yn"), "hname:'SMS\uc218\uc2e0\ub3d9\uc758'");
	f.addElement("etc1", uinfo.s("etc1"), "hname:'\uae30\ud0c01'");
	f.addElement("etc2", uinfo.s("etc2"), "hname:'\uae30\ud0c02'");
	f.addElement("etc3", uinfo.s("etc3"), "hname:'\uae30\ud0c03'");
	f.addElement("etc4", uinfo.s("etc4"), "hname:'\uae30\ud0c04'");
	f.addElement("etc5", uinfo.s("etc5"), "hname:'\uae30\ud0c05'");

	//\ucc98\ub9ac
	if("EMAIL".equals(m.rs("mode"))) {
		//\ubcc0\uc218
		String email = f.get("e").toLowerCase();

		//\uc81c\ud55c
		if(0 < user.findCount("id != " + userId + " AND email = '" + email + "' AND site_id = " + siteId + " AND user_kind = 'U' ")) { m.jsAlert(_message.get("alert.member.used_email")); return; }

		//\ubc1c\uc1a1
		int authNo = m.getRandInt(123456, 864198);
		p.setVar("auth_no", authNo + "");
		//mailTemplate.sendMail(siteinfo, email, "findpw_authno", "\uc774\uba54\uc77c \uc778\uc99d\uc744 \uc704\ud55c \uc778\uc99d\ubc88\ud638\uac00 \ubc1c\uae09\ub418\uc5c8\uc2b5\ub2c8\ub2e4.", p);
		mail.send(siteinfo, email, "findpw_authno", p);

		//\uc138\uc158
		mSession.put("MODIFY_EMAIL", email);
		mSession.put("MODIFY_AUTHNO", "" + authNo);
		mSession.put("MODIFY_SITEID", "" + siteId);
		mSession.put("MODIFY_EMAIL_VERIFIED", "");
		mSession.put("MODIFY_EMAIL_VERIFYDATE", "");
		mSession.save();

		m.jsAlert(_message.get("alert.member.find.authno_to_email"));
		m.js("try { parent.setVerify(); } catch(e) {}");
		return;
	} else if("VERIFY".equals(m.rs("mode"))) {
		//\ubcc0\uc218
		String email = f.get("e").toLowerCase();
		String code = f.get("c");

		//\uc81c\ud55c-\uc774\uba54\uc77c
		if(0 < user.findCount("id != " + userId + " AND email = '" + email + "' AND site_id = " + siteId + " AND user_kind = 'U' ")) { m.jsAlert(_message.get("alert.member.used_email")); return; }

		//\uc81c\ud55c-\uc778\uc99d\ubc88\ud638
		String authEmail = mSession.s("MODIFY_EMAIL");
		String authNo = mSession.s("MODIFY_AUTHNO");
		int authSiteId = mSession.i("MODIFY_SITEID");

		if(!authEmail.equals(email) || !authNo.equals(code) || siteId != authSiteId) {
			m.jsAlert(_message.get("alert.member.email_fail"));
			return;
		}

		//\uc138\uc158
		mSession.put("MODIFY_EMAIL_VERIFIED", email);
		mSession.put("MODIFY_EMAIL_VERIFYDATE", m.time("yyyyMMdd"));
		mSession.save();

		m.jsAlert(_message.get("alert.member.email_success"));
		m.js(""
			+ " try { "
				+ " parent.setSuccess(); "
				+ " parent.document.forms['form1']['verify_email_yn'].value = 'Y'; "
			+ " } catch(e) {} "
		);
		return;
	}

	//\uc218\uc815
	if(m.isPost() && f.validate()) {
		//\ubcc0\uc218
		String birthday = f.glue("", "birthday_year, birthday_month, birthday_day");
		String passwd = f.get("passwd");
		String email = f.glue("@", "email1, email2").toLowerCase();
		String emailYn = f.get("email_yn", "N");
		String smsYn = f.get("sms_yn", "N");
		boolean changeEmailYn = !uinfo.s("email_yn").equals(emailYn);
		boolean changeSmsYn = !uinfo.s("sms_yn").equals(smsYn);

		if(!"".equals(passwd)) {
			//\uc81c\ud55c-\ube44\ubc00\ubc88\ud638
			if(!passwd.matches("^(?!.*(\\d)\\1)(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[\\W_]).{9,}$")) {
				m.jsAlert(_message.get("alert.member.rule_password"));
				return;
			}

			if(64 > passwd.length()) passwd = m.encrypt(passwd, "SHA-256");
			user.item("passwd", passwd);
			if(!passwd.equals(uinfo.s("passwd"))) user.item("passwd_date", m.addDate("d", siteinfo.i("passwd_day"), m.time("yyyyMMdd"), "yyyyMMdd"));
		}

		//\uc774\uba54\uc77c\ubcc0\uacbd
		if(!email.equals(uinfo.s("email"))) {
			if(!"@".equals(email)) {
				if(!mail.isMail(email)) {
					m.jsAlert(_message.get("alert.member.unvalid_email"));
					m.js("parent.resetPassword();");
					return;
				}

				if(0 < user.findCount("id != " + userId + " AND email = '" + email + "' AND site_id = " + siteId + " AND user_kind = 'U' ")) {
					m.jsAlert(_message.get("alert.member.used_email"));
					m.js("parent.resetPassword();");
					return;
				}

				if("Y".equals(siteinfo.s("verify_email_yn"))) {
					if(!email.equals(mSession.s("MODIFY_EMAIL_VERIFIED"))
						|| !m.time("yyyyMMdd").equals(mSession.s("MODIFY_EMAIL_VERIFYDATE"))
						|| !"Y".equals(f.get("verify_email_yn", "N"))) {
						m.jsAlert(_message.get("alert.member.email_expired"));
						m.js("parent.resetPassword();");
						return;
					}
				}
			} else {
				email = "";
			}
		}

		if(!isAuth) {
			user.item("birthday", 8 == birthday.length() ? birthday : "");
			user.item("gender", f.getInt("gender", 1));

			String pattern = "(\\d{3})(\\d{3,4})(\\d{4})";
			String newMobile = "";
			if(!"Y".equals(SiteConfig.s("foreign_yn"))) {
				if(!"".equals(f.get("mobile2")) || !"".equals(f.get("mobile3"))) {
					newMobile = f.get("mobile1") + f.get("mobile2") + f.get("mobile3");
					if(!Pattern.matches(pattern, newMobile)) {
						m.jsAlert(_message.get("alert.member.unvalid_mobile"));
						m.js("parent.resetPassword();");
						return;
					}
					newMobile = newMobile.replaceAll(pattern, "$1-$2-$3");
				}
			} else {
				newMobile = f.get("mobile1");
			}

			user.item("mobile", newMobile);

			//\ud68c\uc6d0\uba85\uc774 \uc5c6\ub294 \uacbd\uc6b0 \uc218\uc815\uc774 \uac00\ub2a5
			if("".equals(uinfo.s("user_nm")) && !"".equals(f.get("user_nm"))) {
				user.item("user_nm", f.get("user_nm"));
				auth.put("NAME", f.get("user_nm"));
			}

			auth.put("MOBILE", newMobile);
			auth.put("BIRTHDAY", 8 == birthday.length() ? birthday : "");
			auth.put("GENDER", f.getInt("gender", 1));
		}

		if(0 < f.getInt("dept_id")) user.item("dept_id", f.getInt("dept_id"));
		user.item("zipcode", f.get("zipcode"));
		user.item("addr", f.get("addr"));
		user.item("new_addr", f.get("new_addr"));
		user.item("addr_dtl", f.get("addr_dtl"));
		user.item("email", email);
		user.item("etc1", f.get("etc1"));
		user.item("etc2", f.get("etc2"));
		user.item("etc3", f.get("etc3"));
		user.item("etc4", f.get("etc4"));
		user.item("etc5", f.get("etc5"));

		user.item("email_yn", emailYn);
		user.item("sms_yn", smsYn);

		uinfo.put("email", email);

		auth.put("EMAIL", email);
		if(changeEmailYn) {
			agreementLog.insertLog(siteinfo, uinfo, "email", emailYn, "modify");

			p.setVar("type", m.getValue("email", agreementLog.typesMsg));
			p.setVar("agreement_yn", m.getValue(emailYn, agreementLog.receiveYnMsg));
			p.setVar("reg_date", m.time(_message.get("format.date.local")));
			//mailTemplate.sendMail(siteinfo, uinfo, "receive", m.getItem("email", agreementLog.types) + " \uc218\uc2e0\uc815\ubcf4\uac00 \ubcc0\uacbd\ub418\uc5c8\uc2b5\ub2c8\ub2e4.", p);
			mail.send(siteinfo, uinfo, "receive", p);
		}
		if(changeSmsYn) {
			agreementLog.insertLog(siteinfo, uinfo, "sms", smsYn, "modify");

			p.setVar("type", m.getValue("sms", agreementLog.typesMsg));
			p.setVar("agreement_yn", m.getValue(smsYn, agreementLog.receiveYnMsg));
			p.setVar("reg_date", m.time(_message.get("format.date.local")));
			//mailTemplate.sendMail(siteinfo, uinfo, "receive", m.getItem("sms", agreementLog.types) + " \uc218\uc2e0\uc815\ubcf4\uac00 \ubcc0\uacbd\ub418\uc5c8\uc2b5\ub2c8\ub2e4.", p);
			mail.send(siteinfo, uinfo, "receive", p);
		}

		//\ud30c\uc77c\ub9ac\uc0ac\uc774\uc9d5
		/*if(isUpload) {
			try {
				String imgPath = m.getUploadPath(f.getFileName("user_file"));
				String cmd = "convert -resize 500x " + imgPath + " " + imgPath;
				Runtime.getRuntime().exec(cmd);
			}
			catch(Exception e) { }
		}*/

		if(!user.update("id = " + userId)) {
			m.jsAlert(_message.get("alert.common.error_modify"));
			m.js("parent.resetPassword();");
			return;
		}

		auth.setAuthInfo();

		m.jsAlert(
			_message.get("alert.member.modified")
			+ (changeEmailYn || changeSmsYn ? _message.get("alert.member.modified_subscribe.prefix", new String[] {"site_nm=>" + siteinfo.s("site_nm")}) : "")
			+ (changeEmailYn ? _message.get("alert.member.modified_subscribe.email", new String[] {"email_receive_yn=>" + m.getValue(emailYn, agreementLog.receiveYnMsg)}) : "")
			+ (changeSmsYn ? _message.get("alert.member.modified_subscribe.sms", new String[] {"sms_receive_yn=>" + m.getValue(smsYn, agreementLog.receiveYnMsg)}) : "")
			+ (changeEmailYn || changeSmsYn ? _message.get("alert.member.modified_subscribe.suffix", new String[] {"site_nm=>" + siteinfo.s("site_nm")}) + _message.get("alert.member.modified_subscribe.date", new String[] {"today=>" + m.time(_message.get("format.date.local"))}) : "")
		);

		int utime = m.getUnixTime();
		String ekey = m.encrypt(utime + "|" + loginId + "|" + key, "SHA-256");
		m.jsReplace("modify.jsp?ek=" + ekey + "&ut=" + utime, "parent");
		return;
	}
} else {
	f.addElement("email_yn", uinfo.s("email_yn"), "hname:'\uc774\uba54\uc77c\uc218\uc2e0\ub3d9\uc758'");
	f.addElement("sms_yn", uinfo.s("sms_yn"), "hname:'SMS\uc218\uc2e0\ub3d9\uc758'");

	//\uc218\uc815
	if(m.isPost() && f.validate()) {
		String emailYn = f.get("email_yn", "N");
		String smsYn = f.get("sms_yn", "N");
		boolean changeEmailYn = !uinfo.s("email_yn").equals(emailYn);
		boolean changeSmsYn = !uinfo.s("sms_yn").equals(smsYn);

		user.item("email_yn", emailYn);
		user.item("sms_yn", smsYn);

		if(changeEmailYn) {
			agreementLog.insertLog(siteinfo, uinfo, "email", emailYn, "modify");

			p.setVar("type", m.getValue("email", agreementLog.typesMsg));
			p.setVar("agreement_yn", m.getValue(emailYn, agreementLog.receiveYnMsg));
			p.setVar("reg_date", m.time(_message.get("format.date.local")));
			//mailTemplate.sendMail(siteinfo, uinfo, "receive", m.getItem("email", agreementLog.types) + " \uc218\uc2e0\uc815\ubcf4\uac00 \ubcc0\uacbd\ub418\uc5c8\uc2b5\ub2c8\ub2e4.", p);
			mail.send(siteinfo, uinfo, "receive", p);
		}
		if(changeSmsYn) {
			agreementLog.insertLog(siteinfo, uinfo, "sms", smsYn, "modify");

			p.setVar("type", m.getValue("sms", agreementLog.typesMsg));
			p.setVar("agreement_yn", m.getValue(smsYn, agreementLog.receiveYnMsg));
			p.setVar("reg_date", m.time(_message.get("format.date.local")));
			//mailTemplate.sendMail(siteinfo, uinfo, "receive", m.getItem("sms", agreementLog.types) + " \uc218\uc2e0\uc815\ubcf4\uac00 \ubcc0\uacbd\ub418\uc5c8\uc2b5\ub2c8\ub2e4.", p);
			mail.send(siteinfo, uinfo, "receive", p);
		}

		if(!user.update("id = " + userId)) {
			m.jsAlert(_message.get("alert.common.error_modify"));
			return;
		}

		m.jsAlert(
			_message.get("alert.member.modified")
			+ (changeEmailYn || changeSmsYn ? _message.get("alert.member.modified_subscribe.prefix", new String[] {"site_nm=>" + siteinfo.s("site_nm")}) : "")
			+ (changeEmailYn ? _message.get("alert.member.modified_subscribe.email", new String[] {"email_receive_yn=>" + m.getValue(emailYn, agreementLog.receiveYnMsg)}) : "")
			+ (changeSmsYn ? _message.get("alert.member.modified_subscribe.sms", new String[] {"sms_receive_yn=>" + m.getValue(smsYn, agreementLog.receiveYnMsg)}) : "")
			+ (changeEmailYn || changeSmsYn ? _message.get("alert.member.modified_subscribe.suffix", new String[] {"site_nm=>" + siteinfo.s("site_nm")}) + _message.get("alert.member.modified_subscribe.date", new String[] {"today=>" + m.time(_message.get("format.date.local"))}) : "")
		);

		//m.jsAlert(_message.get("alert.member.modified"));
		m.jsReplace("index.jsp", "parent");
		return;

	}
}

//\ud3ec\ub9f7\ud305
uinfo.put("gender_conv", m.getValue(uinfo.s("gender"), user.gendersMsg));
uinfo.put("birthday_conv", m.time(_message.get("format.date.local"), uinfo.s("birthday")));
if(!"".equals(uinfo.s("user_file"))) uinfo.put("user_file_url", m.getUploadUrl(uinfo.s("user_file")));

//\ucd9c\ub825
p.setLayout(ch);
p.setBody("mypage.modify");
p.setVar("p_title", "\ud68c\uc6d0\uc815\ubcf4\uc218\uc815");
p.setVar("query", m.qs());
p.setVar("form_script", f.getScript());

p.setVar("view_block", isSSO);
p.setVar(uinfo);

p.setVar("is_auth", isAuth);
p.setLoop("dept_list", userDept.getList(siteId, "U", 0));
p.setLoop("years", mcal.getYears(m.addDate("Y", -49, sysToday, "yyyy")));
p.setLoop("months", mcal.getMonths());
p.setLoop("days", mcal.getDays());
p.setLoop("receive_yn", m.arr2loop(user.receiveYn));

p.setVar("file_ek", m.encrypt("LMS@FILE_user_ID" + userId + "_LIST_" + sysToday));
p.setVar("st_year", m.time("yyyy"));
p.setVar("SITE_CONFIG", SiteConfig.getArr(new String[] {"join_", "modify_", "user_etc_"}));

p.setVar("is_sso", isSSO);
p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mypage/modify.jsp"), 2002220855473238088L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("mypage/init.jsp"), -4599702151442401670L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 2912615399035486559L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
