/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._sysop._order;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _order_0view__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();
String tplRoot = Config.getDocRoot() + "/sysop/html";

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch (RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage()); return; }
catch (Exception ex) { m.errorLog("\uc81c\ud55c \uc6a9\ub7c9 \ucd08\uacfc - " + ex.getMessage()); return; }

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/home/pen/public_html/html");

SiteDao Site = new SiteDao();
DataSet siteinfo = Site.getSiteInfo(request.getServerName(), "sysop");
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("sysop_status") || "".equals(siteinfo.s("doc_root"))) { m.jsReplace("/main/guide.jsp", "top"); return; }
//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 60\ubd84
siteinfo.put("sysop_session_hour", 60);
//B2b\uc0ac\uc6a9X
SiteConfig.put("join_b2b_yn", "N");

//String siteDomain = request.getScheme() + "://" + request.getServerName();
String siteDomain = "https://" + request.getServerName();
/*int port = request.getServerPort();
if(port != 80) siteDomain += ":" + port;*/
String webUrl = siteDomain + "/sysop";

String dataDir = siteinfo.s("doc_root") + "/data";
f.dataDir = dataDir;
m.dataDir = dataDir;
//m.dataUrl = Config.getDataUrl() + (!"/data".equals(Config.getDataUrl()) ? siteinfo.s("ftp_id") : "");
m.dataUrl = Config.getDataUrl();

boolean isDevServer = -1 < request.getServerName().indexOf("lms.malgn.co.kr");
siteinfo.put("logo_url", (!"/data".equals(Config.getDataUrl()) ? "" : siteDomain) + m.getUploadUrl(siteinfo.s("logo")));

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr(); //Lb \uc0ac\uc6a9
boolean isMalgnOffice = "106.244.224.183".equals(userIp) || "125.129.123.211".equals(userIp) || "52.79.184.225".equals(userIp);
if(!"".equals(siteinfo.s("allow_ip_sysop")) && !isMalgnOffice && !Site.checkIP(userIp, siteinfo.s("allow_ip_sysop"))) {
	m.redirect("/");
	return;
}

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
//String sysLocale = "default";
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

//\uae30\ubcf8 \ud68c\uc6d0\uc815\ubcf4
int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
String manageCourses = "";
String userSessionId = "";
String pagreeDate = "";
boolean isUserMaster = false;
String winTitle = "[\uad00\ub9ac\uc790] " + siteinfo.s("site_nm");
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
String surl = request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : "");
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));
final int sysExcelCnt = 20000;

SessionDao mSession = new SessionDao(request, response);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "MLMSKEY2014" + siteId + "7";
if(0 < siteinfo.i("sysop_session_hour")) auth.setValidTime(siteinfo.i("sysop_session_hour") * 60);
if(auth.isValid()) {
	userId = m.parseInt(auth.getString("ID"));
	loginId = auth.getString("LOGINID");
	userName = auth.getString("NAME");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	manageCourses = auth.getString("MANAGE_COURSES");
	userSessionId = userSessionId = auth.getString("SESSIONID");
	pagreeDate = auth.getString("PAGREE_DATE");
	isUserMaster = "Y".equals(auth.getString("IS_USER_MASTER"));

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if(request.getRequestURI().indexOf("/main/auth2.jsp") == -1
		//&& "Y".equals(siteinfo.s("auth2_yn"))
		&& !"Y".equals(auth.getString("AUTH2_YN"))
		//&& !"".equals(siteinfo.s("auth2_type"))
		//&& !"malgn".equals(loginId)
		&& request.getRequestURI().indexOf("/main/otpkey_register.jsp") == -1
		&& request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1
		&& request.getRequestURI().indexOf("/main/modify_passwd.jsp") == -1
	) {
		m.jsReplace("/sysop/main/auth2.jsp?returl=" + m.rs("returl", "/sysop/index.jsp"), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& -1 == request.getRequestURI().indexOf("/sysop/main/logout.jsp")
		&& -1 == request.getRequestURI().indexOf("/sysop/main/login.jsp")
		&& -1 == request.getRequestURI().indexOf("/main/modify_passwd.jsp")
	) {
		m.jsReplace("/sysop/main/logout.jsp");
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

} else {
	if(request.getRequestURI().indexOf("/main/login.jsp") == -1
		&& request.getRequestURI().indexOf("/vod/upload.jsp") == -1
		&& request.getRequestURI().indexOf("/main/slogin.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_template.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_maildir.jsp") == -1
		&& (request.getRequestURI().indexOf("/user/sleep_insert.jsp") == -1 || !"log".equals(m.rs("after")))
	) {
		m.jsReplace(auth.loginURL, "top");
		return;
	}
}

MenuDao Menu = new MenuDao(p, siteId, "default");
SiteMenuDao SiteMenu = new SiteMenuDao();

boolean superBlock = "S".equals(userKind);
boolean adminBlock = "S".equals(userKind) || "A".equals(userKind);
boolean courseManagerBlock = "C".equals(userKind);
boolean deptManagerBlock = "D".equals(userKind);

//boolean isAuthCrm = superBlock || (-1 < siteinfo.s("auth_crm").indexOf("|" + userKind + "|"));
boolean isAuthCrm = superBlock || Menu.accessible(-999, userId, userKind, false);

//\ub85c\uadf8\uc544\uc6c3-\uacfc\uc815\uc6b4\uc601\uc790
if(courseManagerBlock && "".equals(manageCourses) && request.getRequestURI().indexOf("/main/logout.jsp") == -1) {
	m.jsAlert("\ub2f4\ub2f9\ud55c \uacfc\uc815\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\\n \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc138\uc694.");
	m.jsReplace("/sysop/main/logout.jsp", "top");
	return;
}

//\ub9e4\ub274\uc5bc
ManualDao Manual = new ManualDao();
int ManualId = Menu.getOneInt("SELECT manual_id FROM " + Menu.table + " WHERE link = '" + m.replace(request.getRequestURI(), "/sysop", "..") + "'");
if(0 < ManualId) {
	int ManualStatus = Manual.getOneInt("SELECT status FROM " + Manual.table + " WHERE id = " + ManualId);
	if(0 < ManualStatus) p.setVar("SYS_MENU_MANUAL_ID", ManualId);
}

p.setVar("WEB_URL", webUrl);
p.setVar("FRONT_URL", siteDomain);
p.setVar("SYS_TITLE", winTitle);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("IS_AUTH_CRM", isAuthCrm);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_COMMON_CDN", "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);

p.setVar("user_master_block", isUserMaster || isMalgnOffice);
p.setVar("malgn_office_block", isMalgnOffice);
p.setVar("super_block", superBlock);
p.setVar("admin_block", adminBlock);
p.setVar("course_manager_block", courseManagerBlock);
p.setVar("dept_manager_block", deptManagerBlock);
p.setVar("SYS_URL", surl);

boolean isBlindUser = !sysToday.equals(pagreeDate);
p.setVar("SYS_BLINDUSER", isBlindUser);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
UserSession.setType("sysop");
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && "N".equals(siteinfo.s("dup_sysop_yn")) && ("".equals(userSessionId) || userSessionId == null || !UserSession.isValid(userSessionId, userId))) {
	if(request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1) {
		m.jsAlert("\uc138\uc158\uc774 \ub9cc\ub8cc\ub418\uc5c8\uac70\ub098 \uc911\ubcf5 \ub85c\uadf8\uc778\uc774 \ub418\uc5b4 \uc790\ub3d9\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ub429\ub2c8\ub2e4.");
		m.jsReplace("/sysop/main/logout.jsp?mode=session", "top");
		return;
	}
}

InfoLogDao _log = new InfoLogDao(siteId); _log.setItems(userId, "B", surl, userIp);
InfoUserDao _logUser = new InfoUserDao(siteId);


    

String ch = m.rs("ch", "sysop");

p.setVar("pop_block", "pop".equals(ch) || "poplayer".equals(ch));


    

/*
** ORDER \uc0c1\ud0dc -- "1=>\uc644\ub8cc", "2=>\uc785\uae08\ub300\uae30", "-2=>\uacb0\uc81c\ucde8\uc18c", "3=>\ubd80\ubd84\ud658\ubd88", "4=>\uc804\uc561\ud658\ubd88"
** ORDER paymethod --  "SC0010=>\uc2e0\uc6a9\uce74\ub4dc", "SC0030=>\uacc4\uc88c\uc774\uccb4", "SC0040=>\ubb34\ud1b5\uc7a5\uc785\uae08"
** ORDER_ITEM \uc0c1\ud0dc -- "1=>\uc644\ub8cc", "2=>\uc785\uae08\ub300\uae30", "3=>\ud658\ubd88\uc694\uccad", "-2=>\uacb0\uc81c\ucde8\uc18c
** REFUND \uc0c1\ud0dc -- "1=>\ucc98\ub9ac\uc911", "2=>\uc644\ub8cc", "-1=>\ud658\ubd88\ubd88\uac00"
** REFUND refund_type -- "1=>\ubd80\ubd84\ud658\ubd88", "2=>\uc804\uc561\ud658\ubd88"
** REFUND paymethod -- "1=>\uacc4\uc88c\uc774\uccb4", "2=>\uce74\ub4dc\ucde8\uc18c"
*/


//\uc811\uadfc\uad8c\ud55c
if(!Menu.accessible(60, userId, userKind)) { m.jsError("\uc811\uadfc \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uae30\ubcf8\ud0a4
int id = m.ri("id");
if(id == 0) { m.jsError("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
OrderDao order = new OrderDao();
OrderItemDao orderItem = new OrderItemDao();
CourseDao course = new CourseDao();
PaymentDao payment = new PaymentDao();
CourseUserDao courseUser = new CourseUserDao();
RefundDao refund = new RefundDao();
UserDao user = new UserDao(isBlindUser);

//\uc815\ubcf4
DataSet info = order.query(
	"SELECT a.*, u.login_id, u.user_nm, u.status user_status "
	+ " FROM " + order.table + " a "
	+ " LEFT JOIN " + user.table + " u ON a.user_id = u.id "
	+ " WHERE a.id = " + id + " AND a.status != -1"
);
if(!info.next()) { m.jsError("\ud574\ub2f9 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }
info.put("ord_memo_conv", m.nl2br(info.s("ord_memo")));
info.put("order_date_conv", m.time("yyyy.MM.dd", info.s("order_date")));
info.put("pay_date_conv", m.time("yyyy.MM.dd HH:mm:ss", info.s("pay_date")));
info.put("price_conv", m.nf(info.i("price")));
info.put("disc_price_conv", m.nf(info.i("disc_price")));
info.put("disc_group_price_conv", m.nf(info.i("disc_group_price")));
info.put("coupon_price_conv", m.nf(info.i("coupon_price")));
info.put("pay_price_conv", m.nf(info.i("pay_price")));
info.put("refund_price_conv", m.nf(info.i("refund_price")));
info.put("delivery_price_conv", m.nf(info.i("delivery_price")));
info.put(info.s("paymethod") + "_block", true);
info.put("refund_date_conv", m.time("yyyy.MM.dd HH:mm:ss", info.s("refund_date")));
info.put("paymethod_conv", m.getItem(info.s("paymethod"), order.methods));
info.put("status_conv", m.getItem(info.s("status"), order.statusList));
info.put("reg_date_conv", m.time("yyyy.MM.dd HH:mm:ss", info.s("reg_date")));
info.put("delete_block", info.i("status") == 2 && ("03".equals(info.s("paymethod")) || "90".equals(info.s("paymethod"))));
info.put("order_waiting_block", -99 == info.i("status"));
String mobile = "";
if(!"".equals(info.s("ord_mobile"))) mobile = SimpleAES.decrypt(info.s("ord_mobile"));
info.put("ord_mobile", mobile);
info.put("delivery_type_conv", m.getItem(info.s("delivery_type"), order.deliveryTypeList));
info.put("delivery_block", !"N".equals(info.s("delivery_type")));
info.put("deposit_block", "90".equals(info.s("paymethod")) && 2 == info.i("status"));
info.put("force_deposit_block", !"90".equals(info.s("paymethod")) && 2 == info.i("status"));
info.put("user_out_block", -1 == info.i("user_status"));
user.maskInfo(info);

//\uae30\ub85d-\uac1c\uc778\uc815\ubcf4\uc870\ud68c
if("".equals(m.rs("mode")) && info.size() > 0 && !isBlindUser) _log.add("V", Menu.menuNm, info.size(), "\uc774\ub7ec\ub2dd \uc6b4\uc601", info);

//\ucc98\ub9ac
if("del".equals(m.rs("mode"))) {
	//\uc81c\ud55c-\uc785\uae08\ub300\uae30/\ubb34\ud1b5\uc7a5\uc785\uae08
	if(!(2 == info.i("status") && ("03".equals(info.s("paymethod")) || "90".equals(info.s("paymethod"))))) {
		m.jsAlert("\ucde8\uc18c\ud560 \uc218 \uc5c6\ub294 \uc8fc\ubb38\uc785\ub2c8\ub2e4.\n(\ubb34\ud1b5\uc7a5\uc785\uae08\uc73c\ub85c \uc2e0\uccad\ud558\uace0 \uc785\uae08\ub300\uae30\uc778 \uacbd\uc6b0\uc5d0\ub9cc \ucde8\uc18c\ud560 \uc218 \uc788\uc2b5\ub2c8\ub2e4.)");
		return;
	}

	order.item("status", -2);
	order.item("ord_memo", info.s("ord_memo") + "<br>[" + m.time("yyyy.MM.dd HH:mm") + "] \uad00\ub9ac\uc790\uc5d0 \uc758\ud55c \ubb34\ud1b5\uc7a5\uc785\uae08 \ucde8\uc18c");
	order.update("id = " + id);

	orderItem.item("status", -2);
	orderItem.update("order_id = " + id);

	courseUser.item("change_date", m.time("yyyyMMddHHmmss"));
	courseUser.item("status", -4);
	courseUser.update("order_id = " + id);

	//if(-1 == order.execute("DELETE FROM " + order.table + " WHERE id = " + id + "")) { }
	//if(-1 == orderItem.execute("DELETE FROM " + orderItem.table + " WHERE order_id = " + id + "")) { }
	//if(-1 == courseUser.execute("DELETE FROM " + courseUser.table + " WHERE order_id = " + id + "")) { }

	m.jsAlert("\ubb34\ud1b5\uc7a5\uc785\uae08\uc774 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4.");
	m.jsReplace("order_view.jsp?" + m.qs("mode"), "parent");
	return;

} else if("deposit".equals(m.rs("mode"))) {
	//\uc785\uae08\ud655\uc778
	if(!order.confirmDeposit(Integer.toString(id), siteinfo)) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	//\uc774\ub3d9
	m.jsAlert("\uc785\uae08\ud655\uc778\uc774 \uc644\ub8cc\ub410\uc2b5\ub2c8\ub2e4.");
	m.jsReplace("order_view.jsp?" + m.qs("mode"), "parent");
	return;
}


//\ud658\ubd88\uc2e0\uccad
if("refund".equals(m.rs("mode"))) {
	//\uae30\ubcf8\ud0a4
	int iid = m.ri("iid");
	if(iid == 0) { m.jsAlert("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); return; }

	//\uc815\ubcf4-\uc8fc\ubb38\ud56d\ubaa9
	DataSet oiinfo = orderItem.find("id = " + iid + " AND order_id = " + id + " AND status = 1");
	if(!oiinfo.next()) { m.jsAlert("\ud574\ub2f9 \uacb0\uc81c\uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

	//\uc815\ubcf4-\ud658\ubd88
	DataSet rinfo = refund.find("order_id = " + id + " AND order_item_id = " + iid + " AND status != -2"); //\uc218\uc815\uc911
	if(rinfo.next()) { m.jsAlert("\ud574\ub2f9 \uc8fc\ubb38\ud56d\ubaa9\uc740 \uc774\ubbf8 \ud658\ubd88\ucc98\ub9ac\uac00 \ub418\uc5c8\uc2b5\ub2c8\ub2e4."); return; }

	//\ud658\ubd88 \ub4f1\ub85d
	refund.item("site_id", siteId);
	refund.item("user_id", oiinfo.i("user_id"));
	refund.item("course_id", oiinfo.i("course_id"));
	refund.item("order_id", id);
	refund.item("order_item_id", iid);
	refund.item("refund_type", 3);
	refund.item("req_memo", "");
	refund.item("paymethod", info.s("paymethod"));
	refund.item("reg_date", m.time("yyyyMMddHHmmss"));
	refund.item("status", 1);
	if(!refund.insert()) { m.jsAlert("\ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	//\uc544\uc774\ud15c\uc0c1\ud0dc\ubcc0\uacbd
	orderItem.item("status", 3);
	if(!orderItem.update("id = " + iid + "")) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	m.jsReplace("order_view.jsp?" + m.qs("iid, mode"), "parent");
	return;
}

//\uc8fc\ubb38\ub300\uae30\uc0ad\uc81c
if("order_cancel".equals(m.rs("mode"))) {
	//\uc81c\ud55c
	if(-99 < info.i("status")) {
		m.jsAlert("\ucde8\uc18c\ud560 \uc218 \uc5c6\ub294 \uc8fc\ubb38\uc785\ub2c8\ub2e4.");
		return;
	}
	
	//\uc8fc\ubb38\uc0c1\ud0dc\ubcc0\uacbd
	order.item("status", -1);
	if(!order.update("id = " + id + " AND status = -99")) { m.jsAlert("\uc8fc\ubb38\uc744 \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	//\ucfe0\ud3f0\ucde8\uc18c
	DataSet oilist = orderItem.find("order_id = " + id + " AND status = -99");
	while(oilist.next()) {
		if(!orderItem.cancelDiscount(oilist.i("id"), oilist.i("coupon_user_id"))) { m.jsAlert("\uc801\uc6a9\ub41c \ucfe0\ud3f0\uc744 \ud574\uc81c\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
	}

	//\uc544\uc774\ud15c\uc0c1\ud0dc\ubcc0\uacbd
	orderItem.item("status", -1);
	if(!orderItem.update("order_id = " + id + " AND status = -99")) { m.jsAlert("\uc8fc\ubb38\ud56d\ubaa9\uc744 \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	m.jsReplace("order_list.jsp?" + m.qs("id, mode"), "parent");
	return;
}

//\ubaa9\ub85d-\uacb0\uc81c
DataSet plist = payment.find("oid = " + id + "");
if(0 < plist.size()) info.put("payment_block", true);

//\uc815\ubcf4-\uc2b9\uc778\uacb0\uc81c
DataSet pinfo = new DataSet();
if(-99 == info.i("status") || "90".equals(info.s("paymethod")) || "99".equals(info.s("paymethod"))) {
	p.setVar("pg_block", false);
	p.setVar("receipt_block", false);
} else {
	p.setVar("pg_block", true);
	p.setVar(
		"receipt_block"
		, (
			"01".equals(info.s("paymethod")) && (1 == info.i("status") || 3 == info.i("status") || 4 == info.i("status"))
			|| ("02".equals(info.s("paymethod")) || "03".equals(info.s("paymethod"))) && 1 == info.i("status")
		)
	);

	pinfo = payment.find("oid = " + id + " AND respcode IN ('0000', '0001', '00')");
	if(!pinfo.next()) { m.jsError(_message.get("alert.common.nodata")); return; }
	pinfo.put("paydate_conv", m.time(_message.get("format.datetime.dot"), pinfo.s("paydate")));
	pinfo.put("cardinstallmonth_conv", pinfo.i("cardinstallmonth") == 0 ? _message.get("payment.unit.month_single") : pinfo.i("cardinstallmonth") + _message.get("payment.unit.month_multi"));
	pinfo.put("amount_conv", m.nf(pinfo.i("amount")));

	//authdata\ub294 LGU+\uc5d0\uc11c\ub9cc \uc0ac\uc6a9\ub428. LGU+\uc5d0\uc11c \uc62c\uc573\uc73c\ub85c \ubcc0\uacbd\ud55c \uacbd\uc6b0 pg_key\uac00 \ubcc0\uacbd\ub418\uc5b4 \uc624\ub958 \ubc1c\uc0dd. lgu_pg_key \ucd94\uac00\ud568. by hopegiver [2019-06-05]
	String pgKey = "lgu".equals(siteinfo.s("pg_nm")) ? siteinfo.s("pg_key") : SiteConfig.s("lgu_pg_key");
	pinfo.put("authdata", m.encrypt(pinfo.s("mid") + pinfo.s("tid") + pgKey));
	pinfo.put("caslimitdate_conv", (8 != pinfo.s("caslimitdate").length() ? "-" : m.time("yyyy.MM.dd", pinfo.s("caslimitdate"))));
}

//\ubaa9\ub85d
DataSet list = orderItem.query(
	"SELECT a.* "
	+ ", r.id rid, r.status r_status "
	+ " FROM " + orderItem.table + " a "
	+ " LEFT JOIN " + refund.table + " r ON r.order_id = a.order_id AND r.order_item_id = a.id AND r.status != -2" //\uc218\uc815\uc911
	+ " WHERE a.order_id = '" + id + "' AND a.status != -1 "
	+ " ORDER BY a.id ASC "
);
while(list.next()) {
	if("book".equals(list.s("product_type"))) { info.put("book_block", true); }

	list.put("product_nm_conv", m.cutString(list.s("product_nm"), 90));
	list.put("quantity_conv", m.nf(list.i("quantity")));
	list.put("unit_price_conv", m.nf(list.i("unit_price")));
	list.put("price_conv", m.nf(list.i("price")));
	list.put("disc_price_conv", m.nf(list.i("disc_price")));
	list.put("disc_group_price_conv", m.nf(list.i("disc_group_price")));
	list.put("coupon_price_conv", m.nf(list.i("coupon_price")));
	list.put("pay_price_conv", m.nf(list.i("pay_price")));
	list.put("refund_price_conv", m.nf(list.i("refund_price")));
	list.put("product_type_conv", m.getItem(list.s("product_type"), orderItem.ptypes));
	list.put("refund_block", (list.i("rid") == 0 || list.i("r_status") == -2 ) && list.i("pay_price") > 0 && -2 != list.i("status"));//\uc218\uc815\uc911
	list.put("status_conv", m.getItem(list.s("r_status"), refund.statusList));
}

//\uc5d1\uc140
if("excel".equals(m.rs("mode"))) {
	ExcelWriter ex = new ExcelWriter(response, "\uc8fc\ubb38\ub0b4\uc5ed_" + id + "(" + m.time("yyyy-MM-dd") + ").xls");
	ex.setData(list, new String[] { "__ord=>No", "id=>\uc544\uc774\ub514", "product_type_conv=>\ud0c0\uc785", "quantity=>\uc218\ub7c9", "product_nm=>\uacfc\uc815\uba85/\uc0c1\ud488\uba85", "price=>\ud310\ub9e4\uc778\uac00", "coupon_price=>\ucfe0\ud3f0\ud560\uc778", "disc_group_price=>\ud68c\uc6d0\uadf8\ub8f9\ud560\uc778", "pay_price=>\uc2e4\uacb0\uc81c\uae08\uc561", "refund_price=>\ud658\ubd88\uc561" }, "\uc8fc\ubb38\ub0b4\uc5ed_" + id + "(" + m.time("yyyy-MM-dd") + ")");
	ex.write();
	return;
}

//\ucd9c\ub825
p.setLayout(ch);
p.setBody("order.order_view");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id,mode"));
p.setVar("mode_query", m.qs("mode"));
p.setVar("form_script", f.getScript());

p.setVar(info);
p.setVar("payment", pinfo);
p.setLoop("list", list);

p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/order/order_view.jsp"), -3722396929955351047L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/order/init.jsp"), -5256147056106035384L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 1859833422433906494L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
