/*
 * JSP generated by Resin-4.0.67 (built Thu, 01 Aug 2024 10:12:42 PDT)
 */

package _jsp._inc;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _course_0main_0list__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

//request.setCharacterEncoding("utf-8");

final String BUILDVERSION = "24.02.01";

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(RuntimeException re) {
	m.errorLog("Overflow file size. - " + re.getMessage(), re);
	return;
}
catch(Exception ex) {
	m.errorLog("Overflow file size. - " + ex.getMessage(), ex);
	return;
}

SiteDao Site = new SiteDao(); //Site.clear();
DataSet siteinfo = Site.getSiteInfo(request.getServerName());
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("status") || "".equals(siteinfo.s("doc_root"))) {
	//m.jsReplace("about:blank", "top");
	return;
}

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//CSAP \uc18c\uc15c \ub85c\uadf8\uc778 \uc0ac\uc6a9 \uc548\ud568
siteinfo.put("oauth_vendor", "");
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 1\uc2dc\uac04
siteinfo.put("session_hour", 1);
//\uacb0\uc81c\ud398\uc774\uc9c0 \uc548\ub0b4 \ubb38\uad6c
String allowTags = "a,b,br,cite,code,dd,dl,dt,div,em,i,li,ol,p,pre,q,small,span,strike,strong,sub,sup,u,ul,article,aside,details,div,dt,figcaption,footer,form,fieldset,header,hgroup,html,main,nav,section,summary,body,p,dl,multicol,dd,figure,address,center,blockquote,h1,h2,h3,h4,h5,h6,listing,xmp,pre,plaintext,menu,dir,ul,ol,li,hr,table,tbody,thead,tfoot,th,tr,td,caption,textarea,img,input,textarea,hr,iframe,video,audio";
String allowRegexr = "<(\\/?)(?!.*" + Malgn.replace(allowTags, ",", "[ >]|.*") + "[ >])([^>]*)>";
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));
boolean isDevServer = -1 < request.getServerName().indexOf("politech.malgn.co.kr");
String webUrl = request.getScheme() + "://" + request.getServerName();
int port = request.getServerPort();
if(port != 80 && port != 443) webUrl += ":" + port;
String dataDir = siteinfo.s("doc_root") + "/data";
String tplRoot = siteinfo.s("doc_root") + "/html";
f.dataDir = dataDir;
m.dataDir = dataDir;
m.dataUrl = Config.getDataUrl();

if(!"".equals(siteinfo.s("logo"))) siteinfo.put("logo_url", m.getUploadUrl(siteinfo.s("logo")));
else siteinfo.put("logo_url", "/common/images/default/malgn_logo.jpg");

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr();
if(!"".equals(siteinfo.s("allow_ip_user")) && !Site.checkIP(userIp, siteinfo.s("allow_ip_user"))) {
	m.redirect("/main/guide.jsp");
	return;
}

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("C:/Users/newkl/Desktop/MalgnLMS/public_html/html");

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String loginMethod = "";
String userName = "";
String userEmail = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
int userGroupDisc = 0;
//String aloginYn = "";
String userSessionId = "";
boolean userB2BBlock = false;
String userB2BName = "";
String userB2BFile = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean isRespWeb = (5 <= siteinfo.i("skin_cd"));
boolean isGoMobile = !isRespWeb && m.isMobile();
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));

SessionDao mSession = new SessionDao(request, response);

DataSet auth2Info = Config.getDataSet("//config/userAuth2");
auth2Info.next();

Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "MLMS14" + siteId + "7";
if(0 < siteinfo.i("session_hour")) auth.setValidTime(siteinfo.i("session_hour") * 3600);
if(auth.isValid()) {
	userId = auth.getInt("ID");
	loginId = auth.getString("LOGINID");
	loginMethod = auth.getString("LOGINMETHOD");
	userName = auth.getString("NAME");
	userEmail = auth.getString("EMAIL");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	userGroupDisc = !"null".equals(auth.getString("GROUPS_DISC")) ? m.parseInt(auth.getString("GROUPS_DISC")) : 0;
	//aloginYn = auth.getString("ALOGIN_YN");
	userSessionId = auth.getString("SESSIONID");
	userB2BName = auth.getString("B2BNAME");
	userB2BFile = auth.getString("B2BFILE");
	if(userGroups != null) {
		if(-1 < userGroups.indexOf(",")) for(String userGroupId : m.split(",", userGroups)) p.setVar("SYS_USERGROUP_" + userGroupId, true);
		else p.setVar("SYS_USERGROUP_" + userGroups, true);
	}

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if("direct".equals(loginMethod)
		&& "Y".equals(auth2Info.s("auth2Yn"))
		&& !"Y".equals(auth.getString("USER_AUTH2_YN"))
		&& "Y".equals(auth.getString("DEPT_AUTH2_YN")) //\uad00\ub9ac\uc790\ub2e8-\ud68c\uc6d0\uc18c\uc18d\uad00\ub9ac\uc5d0\uc11c 2\ucc28\uc778\uc99d\uc124\uc815 \uc5ec\ubd80 Y/N	 20230126
		//&& !"".equals(auth.getString("USER_AUTH2_TYPE"))
		//&& !"malgn".equals(loginId)
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/auth2.jsp?returl=" + Malgn.urlencode(m.getThisURI()), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/logout.jsp");
		return;
	}

	if(
		(
			(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) //\uc0dd\ub144\uc6d4\uc77c
			|| (1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) //\uc131\ubcc4
			|| (1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) //\ud734\ub300\uc804\ud654\ubc88\ud638
			|| ("".equals(auth.getString("NAME"))) //\uc131\uba85
			|| ("".equals(auth.getString("EMAIL"))) //\uc774\uba54\uc77c
		)
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/member/privacy_agree.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_verify.jsp")
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		int tut = m.getUnixTime();
		String tek = m.encrypt(tut + "|" + loginId + "|7B1F83A608723CEDDFA9AED338FC796C", "SHA-256");
		String noInfoString = "";

		if(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) noInfoString = "\uc0dd\ub144\uc6d4\uc77c";
		else if(1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) noInfoString = "\uc131\ubcc4";
		else if(1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) noInfoString = "\ud734\ub300\uc804\ud654\ubc88\ud638";
		else if("".equals(auth.getString("NAME"))) noInfoString = "\uc131\uba85";
		else if("".equals(auth.getString("EMAIL"))) noInfoString = "\uc774\uba54\uc77c";
		m.jsAlert("\ud68c\uc6d0 \ud544\uc218 \uc815\ubcf4 [" + noInfoString + "](\uc774)\uac00 \ub204\ub77d\ub418\uc5b4\\n\uc218\uc815\ud398\uc774\uc9c0\ub85c \uc774\ub3d9\ud569\ub2c8\ub2e4.");
		m.jsReplace("/mypage/modify.jsp?ek=" + tek + "&ut=" + tut);
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

	p.setVar("login_block", true);
} else {
	p.setVar("login_block", false);

	if(siteinfo.b("close_yn")) {
		boolean isNeedLogin = true;
		String[] exceptPages = m.split("|", siteinfo.s("close_except"));

		if(-1 < request.getRequestURI().indexOf("/member/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/find.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/alogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin_input.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/sysop_slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/main/site_cache.jsp")
			|| -1 < request.getRequestURI().indexOf("/mobile/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate_course.jsp")
			|| -1 < request.getRequestURI().indexOf("/kollus/check_api.jsp")
			|| -1 < request.getRequestURI().indexOf("/common/")
			|| -1 < request.getRequestURI().indexOf("/api/auto_send.jsp")
		) {
			isNeedLogin = false;
		} else if(!"".equals(siteinfo.s("close_except"))) {
			for(int i = 0; i < exceptPages.length; i++) {
				if(-1 < request.getRequestURI().indexOf(exceptPages[i])) { isNeedLogin = false; continue; }
			}
		}

		if(isNeedLogin) {
			m.redirect(!isGoMobile ? auth.loginURL : "/mobile/login.jsp");
			return;
		}
	}
}

userB2BBlock = !"".equals(userB2BName) && null != userB2BName;
p.setVar("SYS_HTTPHOST", request.getServerName());
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERID", userId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SYS_DEPTID", userDeptId);
p.setVar("SYS_GROUP_DISC", userGroupDisc);
p.setVar("SYS_B2BBLOCK", userB2BBlock);
p.setVar("SYS_B2BNAME", userB2BName);
p.setVar("SYS_B2BFILE", userB2BFile);
p.setVar("SYS_PAGE_URL", request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : ""));
p.setVar("SYS_TITLE", siteinfo.s("site_nm"));
p.setVar("webUrl", webUrl);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("CURR_DATE", m.time("yyyyMMdd"));
p.setVar("SYS_EK", m.encrypt(loginId + siteinfo.s("sso_key") + m.time("yyyyMMdd"), "SHA-256"));
p.setVar("IS_RESP_WEB", isRespWeb);
p.setVar("IS_MOBILE", m.isMobile());
p.setVar("IS_GO_MOBILE", isGoMobile);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);
p.setVar("script", siteinfo.s("header_script"));

for(int IndexSkin = 1; IndexSkin < 5; IndexSkin++) {
	p.setVar("SKIN_LT_" + IndexSkin, siteinfo.i("skin_cd") < IndexSkin);
	p.setVar("SKIN_LTE_" + IndexSkin, siteinfo.i("skin_cd") <= IndexSkin);
	p.setVar("SKIN_GT_" + IndexSkin, siteinfo.i("skin_cd") > IndexSkin);
	p.setVar("SKIN_GTE_" + IndexSkin, siteinfo.i("skin_cd") >= IndexSkin);
}

MenuDao Menu = new MenuDao(p, sysLocale);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && !siteinfo.b("duplication_yn") && !UserSession.isValid(userSessionId, userId)) {
	if(request.getRequestURI().indexOf("/member/logout.jsp") == -1 && request.getRequestURI().indexOf("/mobile/logout.jsp") == -1) {
		m.jsAlert(_message.get("alert.common.logout_session"));
		if(request.getRequestURI().indexOf("/mobile/") != -1) m.jsReplace("/mobile/logout.jsp?mode=session");
		else m.jsReplace("/member/logout.jsp?mode=session");
		return;
	}
}


    out.write('\n');
    

String ch = m.rs("ch", "inc");


    

//\ud3fc\uc785\ub825
String type = m.rs("type", "recomm");
String tpl = m.rs("tpl", "course_main_list");
int count = m.ri("cnt") > 0 ? m.ri("cnt") : 100;
int strlen = m.ri("strlen") > 0 ? m.ri("strlen") : 24;
int line = m.ri("line") > 0 ? m.ri("line") : 100;

String today = m.time("yyyyMMdd");

//\uac1d\uccb4
CourseDao course = new CourseDao();
CourseUserDao courseUser = new CourseUserDao();
CourseMainDao courseMain = new CourseMainDao();
CourseTutorDao courseTutor = new CourseTutorDao();
LmCategoryDao category = new LmCategoryDao("course");
LessonDao lesson = new LessonDao();

//\ubaa9\ub85d
//course.d(out);
DataSet list = course.query(
	"SELECT a.*"
	+ " , ( CASE "
		+ " WHEN a.course_type = 'A' THEN 'Y' "
		+ " WHEN '" + today + "' BETWEEN a.request_sdate AND a.request_edate THEN 'Y' "
		+ " ELSE 'N' "
	+ " END ) is_request "
	+ ", ( SELECT COUNT(*) FROM " + courseUser.table + " WHERE course_id = a.id AND status IN (1,3) ) user_cnt "
	+ ", l.start_url, l.lesson_type, l.content_width, l.content_height, c.category_nm "
	+ " FROM " + courseMain.table + " m INNER JOIN " + course.table + " a ON a.id = m.course_id "
	+ " LEFT JOIN " + lesson.table + " l ON a.sample_lesson_id = l.id "
	+ " LEFT JOIN " + category.table + " c ON a.category_id = c.id "
	+ " WHERE a.status = 1 AND m.site_id = " + siteId + " AND m.type = '" + type + "'"
	+ " ORDER BY m.sort ASC "
	, count
);
while(list.next()) {
	list.put("request_date", "-");
	if("R".equals(list.s("course_type"))) {
		list.put("is_regular", true);
		list.put("request_date", m.time(_message.get("format.date.dot"), list.s("request_sdate")) + " - " + m.time(_message.get("format.date.dot"), list.s("request_edate")));
		list.put("study_date", m.time(_message.get("format.date.dot"), list.s("study_sdate")) + " - " + m.time(_message.get("format.date.dot"), list.s("study_edate")));
		list.put("ready_block", !"".equals(list.s("request_sdate")) ? 0 > m.diffDate("D", list.s("request_sdate"), today) : false);
	} else if("A".equals(list.s("course_type"))) {
		list.put("is_regular", false);
		list.put("request_date", "\uc0c1\uc2dc");
		list.put("study_date", m.nf(list.i("lesson_day")) + "\uc77c");
	}

	list.put("course_nm_conv", m.cutString(list.s("course_nm"), strlen));
	list.put("subtitle_conv", m.nl2br(list.s("subtitle")));
	list.put("content_conv", m.cutString(m.stripTags(list.s("content1")), 120));
	if(!"".equals(list.s("course_file"))) {
		list.put("course_file_url", m.getUploadUrl(list.s("course_file")));
	} else {
		list.put("course_file_url", "/html/images/common/noimage_course.gif");
	}
	list.put("request_block", "Y".equals(list.s("is_request")));
	list.put("price_conv", list.i("price") > 0 ? m.nf(list.i("price")) + "\uc6d0" : "\ubb34\ub8cc");
	list.put("list_price_conv", m.nf(list.i("list_price")));
	list.put("list_price_block", list.i("list_price") > 0);
	
	list.put("is_online", "N".equals(list.s("onoff_type")));
	list.put("is_offline", "F".equals(list.s("onoff_type")));
	list.put("is_blend", "B".equals(list.s("onoff_type")));
	list.put("is_package", "P".equals(list.s("onoff_type")));
	list.put("onoff_type_conv", m.getValue(list.s("onoff_type"), course.onoffPackageTypesMsg));

	list.put("class", list.i("__ord") % line == 1 ? "first" : "");
	list.put("tutor_nm", courseTutor.getTutorSummary(list.i("id")));
}

//\ucd9c\ub825
p.setLayout(null);
if(new File(tplRoot + "/inc/course_main_" + type + "_list.html").exists()) {
	p.setBody("inc.course_main_" + type + "_list");
} else {
	p.setBody("inc." + tpl);
}
p.setLoop("list", list);
p.setVar("type_" + type, true);
p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5413665724253103304L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("inc/course_main_list.jsp"), -4200828211735827787L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("inc/init.jsp"), 8682710652156158721L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 2972221578934540967L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
