/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._classroom;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _forum_0read__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

//request.setCharacterEncoding("utf-8");

final String BUILDVERSION = "24.02.01";

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(RuntimeException re) {
	m.errorLog("Overflow file size. - " + re.getMessage(), re);
	return;
}
catch(Exception ex) {
	m.errorLog("Overflow file size. - " + ex.getMessage(), ex);
	return;
}

SiteDao Site = new SiteDao(); //Site.clear();
DataSet siteinfo = Site.getSiteInfo(request.getServerName());
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("status") || "".equals(siteinfo.s("doc_root"))) {
	//m.jsReplace("about:blank", "top");
	return;
}

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//CSAP \uc18c\uc15c \ub85c\uadf8\uc778 \uc0ac\uc6a9 \uc548\ud568
siteinfo.put("oauth_vendor", "");
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 1\uc2dc\uac04
siteinfo.put("session_hour", 1);
//\uacb0\uc81c\ud398\uc774\uc9c0 \uc548\ub0b4 \ubb38\uad6c
String allowTags = "a,b,br,cite,code,dd,dl,dt,div,em,i,li,ol,p,pre,q,small,span,strike,strong,sub,sup,u,ul,article,aside,details,div,dt,figcaption,footer,form,fieldset,header,hgroup,html,main,nav,section,summary,body,p,dl,multicol,dd,figure,address,center,blockquote,h1,h2,h3,h4,h5,h6,listing,xmp,pre,plaintext,menu,dir,ul,ol,li,hr,table,tbody,thead,tfoot,th,tr,td,caption,textarea,img,input,textarea,hr,iframe,video,audio";
String allowRegexr = "<(\\/?)(?!.*" + Malgn.replace(allowTags, ",", "[ >]|.*") + "[ >])([^>]*)>";
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));
boolean isDevServer = -1 < request.getServerName().indexOf("politech.malgn.co.kr");
String webUrl = request.getScheme() + "://" + request.getServerName();
int port = request.getServerPort();
if(port != 80 && port != 443) webUrl += ":" + port;
String dataDir = siteinfo.s("doc_root") + "/data";
String tplRoot = siteinfo.s("doc_root") + "/html";
f.dataDir = dataDir;
m.dataDir = dataDir;
m.dataUrl = Config.getDataUrl();

if(!"".equals(siteinfo.s("logo"))) siteinfo.put("logo_url", m.getUploadUrl(siteinfo.s("logo")));
else siteinfo.put("logo_url", "/common/images/default/malgn_logo.jpg");

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr();
if(!"".equals(siteinfo.s("allow_ip_user")) && !Site.checkIP(userIp, siteinfo.s("allow_ip_user"))) {
	m.redirect("/main/guide.jsp");
	return;
}

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/Users/kyounghokim/IdeaProjects/MalgnLMS/public_html/html");

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String loginMethod = "";
String userName = "";
String userEmail = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
int userGroupDisc = 0;
//String aloginYn = "";
String userSessionId = "";
boolean userB2BBlock = false;
String userB2BName = "";
String userB2BFile = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean isRespWeb = (5 <= siteinfo.i("skin_cd"));
boolean isGoMobile = !isRespWeb && m.isMobile();
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));

SessionDao mSession = new SessionDao(request, response);

DataSet auth2Info = Config.getDataSet("//config/userAuth2");
auth2Info.next();

Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "MLMS14" + siteId + "7";
if(0 < siteinfo.i("session_hour")) auth.setValidTime(siteinfo.i("session_hour") * 3600);
if(auth.isValid()) {
	userId = auth.getInt("ID");
	loginId = auth.getString("LOGINID");
	loginMethod = auth.getString("LOGINMETHOD");
	userName = auth.getString("NAME");
	userEmail = auth.getString("EMAIL");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	userGroupDisc = !"null".equals(auth.getString("GROUPS_DISC")) ? m.parseInt(auth.getString("GROUPS_DISC")) : 0;
	//aloginYn = auth.getString("ALOGIN_YN");
	userSessionId = auth.getString("SESSIONID");
	userB2BName = auth.getString("B2BNAME");
	userB2BFile = auth.getString("B2BFILE");
	if(userGroups != null) {
		if(-1 < userGroups.indexOf(",")) for(String userGroupId : m.split(",", userGroups)) p.setVar("SYS_USERGROUP_" + userGroupId, true);
		else p.setVar("SYS_USERGROUP_" + userGroups, true);
	}

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if("direct".equals(loginMethod)
		&& "Y".equals(auth2Info.s("auth2Yn"))
		&& !"Y".equals(auth.getString("USER_AUTH2_YN"))
		&& "Y".equals(auth.getString("DEPT_AUTH2_YN")) //\uad00\ub9ac\uc790\ub2e8-\ud68c\uc6d0\uc18c\uc18d\uad00\ub9ac\uc5d0\uc11c 2\ucc28\uc778\uc99d\uc124\uc815 \uc5ec\ubd80 Y/N	 20230126
		//&& !"".equals(auth.getString("USER_AUTH2_TYPE"))
		//&& !"malgn".equals(loginId)
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/auth2.jsp?returl=" + Malgn.urlencode(m.getThisURI()), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/logout.jsp");
		return;
	}

	if(
		(
			(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) //\uc0dd\ub144\uc6d4\uc77c
			|| (1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) //\uc131\ubcc4
			|| (1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) //\ud734\ub300\uc804\ud654\ubc88\ud638
			|| ("".equals(auth.getString("NAME"))) //\uc131\uba85
			|| ("".equals(auth.getString("EMAIL"))) //\uc774\uba54\uc77c
		)
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/member/privacy_agree.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_verify.jsp")
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		int tut = m.getUnixTime();
		String tek = m.encrypt(tut + "|" + loginId + "|7B1F83A608723CEDDFA9AED338FC796C", "SHA-256");
		String noInfoString = "";

		if(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) noInfoString = "\uc0dd\ub144\uc6d4\uc77c";
		else if(1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) noInfoString = "\uc131\ubcc4";
		else if(1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) noInfoString = "\ud734\ub300\uc804\ud654\ubc88\ud638";
		else if("".equals(auth.getString("NAME"))) noInfoString = "\uc131\uba85";
		else if("".equals(auth.getString("EMAIL"))) noInfoString = "\uc774\uba54\uc77c";
		m.jsAlert("\ud68c\uc6d0 \ud544\uc218 \uc815\ubcf4 [" + noInfoString + "](\uc774)\uac00 \ub204\ub77d\ub418\uc5b4\\n\uc218\uc815\ud398\uc774\uc9c0\ub85c \uc774\ub3d9\ud569\ub2c8\ub2e4.");
		m.jsReplace("/mypage/modify.jsp?ek=" + tek + "&ut=" + tut);
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

	p.setVar("login_block", true);
} else {
	p.setVar("login_block", false);

	if(siteinfo.b("close_yn")) {
		boolean isNeedLogin = true;
		String[] exceptPages = m.split("|", siteinfo.s("close_except"));

		if(-1 < request.getRequestURI().indexOf("/member/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/find.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/alogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin_input.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/sysop_slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/main/site_cache.jsp")
			|| -1 < request.getRequestURI().indexOf("/mobile/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate_course.jsp")
			|| -1 < request.getRequestURI().indexOf("/kollus/check_api.jsp")
			|| -1 < request.getRequestURI().indexOf("/common/")
			|| -1 < request.getRequestURI().indexOf("/api/auto_send.jsp")
		) {
			isNeedLogin = false;
		} else if(!"".equals(siteinfo.s("close_except"))) {
			for(int i = 0; i < exceptPages.length; i++) {
				if(-1 < request.getRequestURI().indexOf(exceptPages[i])) { isNeedLogin = false; continue; }
			}
		}

		if(isNeedLogin) {
			m.redirect(!isGoMobile ? auth.loginURL : "/mobile/login.jsp");
			return;
		}
	}
}

userB2BBlock = !"".equals(userB2BName) && null != userB2BName;
p.setVar("SYS_HTTPHOST", request.getServerName());
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERID", userId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SYS_DEPTID", userDeptId);
p.setVar("SYS_GROUP_DISC", userGroupDisc);
p.setVar("SYS_B2BBLOCK", userB2BBlock);
p.setVar("SYS_B2BNAME", userB2BName);
p.setVar("SYS_B2BFILE", userB2BFile);
p.setVar("SYS_PAGE_URL", request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : ""));
p.setVar("SYS_TITLE", siteinfo.s("site_nm"));
p.setVar("webUrl", webUrl);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("CURR_DATE", m.time("yyyyMMdd"));
p.setVar("SYS_EK", m.encrypt(loginId + siteinfo.s("sso_key") + m.time("yyyyMMdd"), "SHA-256"));
p.setVar("IS_RESP_WEB", isRespWeb);
p.setVar("IS_MOBILE", m.isMobile());
p.setVar("IS_GO_MOBILE", isGoMobile);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);
p.setVar("script", siteinfo.s("header_script"));

for(int IndexSkin = 1; IndexSkin < 5; IndexSkin++) {
	p.setVar("SKIN_LT_" + IndexSkin, siteinfo.i("skin_cd") < IndexSkin);
	p.setVar("SKIN_LTE_" + IndexSkin, siteinfo.i("skin_cd") <= IndexSkin);
	p.setVar("SKIN_GT_" + IndexSkin, siteinfo.i("skin_cd") > IndexSkin);
	p.setVar("SKIN_GTE_" + IndexSkin, siteinfo.i("skin_cd") >= IndexSkin);
}

MenuDao Menu = new MenuDao(p, sysLocale);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && !siteinfo.b("duplication_yn") && !UserSession.isValid(userSessionId, userId)) {
	if(request.getRequestURI().indexOf("/member/logout.jsp") == -1 && request.getRequestURI().indexOf("/mobile/logout.jsp") == -1) {
		m.jsAlert(_message.get("alert.common.logout_session"));
		if(request.getRequestURI().indexOf("/mobile/") != -1) m.jsReplace("/mobile/logout.jsp?mode=session");
		else m.jsReplace("/member/logout.jsp?mode=session");
		return;
	}
}


    out.write('\n');
    

//\ub85c\uadf8\uc778
if(1 > userId) { auth.loginForm(); return; }

//\uae30\ubcf8\ud0a4
int cuid = m.ri("cuid");
if(cuid == 0) { m.jsError(_message.get("alert.common.required_key")); return; }

//\uac1d\uccb4
UserDao user = new UserDao();
CourseDao course = new CourseDao();
CourseUserDao courseUser = new CourseUserDao();
CourseModuleDao courseModule = new CourseModuleDao();

CourseUserDao cu = new CourseUserDao();
CourseModuleDao cm = new CourseModuleDao();

//\ubcc0\uc218
String today = m.time("yyyyMMdd");
String now = m.time("yyyyMMddHHmmss");

//\uc815\ubcf4
DataSet cuinfo = courseUser.query(
	"SELECT a.*, c.course_nm, c.course_type, c.onoff_type, c.sms_yn, c.limit_seek_yn, t.user_nm tutor_name, c.subject_id, c.renew_max_cnt, c.renew_yn, u.id user_id, u.user_nm, u.mobile "
	+ " FROM " + courseUser.table + " a "
	+ " INNER JOIN " + course.table + " c ON a.course_id = c.id AND c.site_id = " + siteId + " "
	+ " INNER JOIN " + user.table + " u ON a.user_id = u.id"
	+ " LEFT JOIN " + user.table + " t ON a.tutor_id = t.id"
	+ " WHERE a.id = " + cuid + " AND a.user_id = '" + userId + "' AND a.status IN (1,3)"
);
if(!cuinfo.next()) { m.jsError(_message.get("alert.course_user.nodata")); return; }

//\uc815\ubcf4-\uacfc\uc815
String courseId = cuinfo.s("course_id");
DataSet cinfo = course.find("id = " + courseId + " AND site_id = " + siteId + "");
if(!cinfo.next()) { m.jsError(_message.get("alert.course.nodata")); return; }
cinfo.put("lesson_time_conv", m.nf((int)cinfo.d("lesson_time")));
cinfo.put("onoff_type_conv", m.getValue(cinfo.s("onoff_type"), course.onoffTypesMsg));
cinfo.put("std_progress", m.nf(cinfo.i("assign_progress") * cinfo.i("limit_progress") / 100, 1));
cinfo.put("std_exam", m.nf(cinfo.i("assign_exam") * cinfo.i("limit_exam") / 100, 1));
cinfo.put("std_homework", m.nf(cinfo.i("assign_homework") * cinfo.i("limit_homework") / 100, 1));
cinfo.put("std_forum", m.nf(cinfo.i("assign_forum") * cinfo.i("limit_forum") / 100, 1));
cinfo.put("std_etc", m.nf(cinfo.i("assign_etc") * cinfo.i("limit_etc") / 100, 1));

boolean alltime = "A".equals(cuinfo.s("course_type"));
cinfo.put("alltime_block", alltime);

//\uc0c1\ud0dc [progress] (W : \ub300\uae30, E : \uc885\ub8cc, I : \uc218\uac15\uc911, R : \ubcf5\uc2b5\uc911)
cuinfo.put("restudy_edate", cuinfo.s("end_date"));
cuinfo.put("restudy_block", false);
String progress = "I";
if(0 > m.diffDate("D", cuinfo.s("start_date"), today)) progress = "W"; //\ub300\uae30
else if(0 >= m.diffDate("D", cuinfo.s("end_date"), today)) progress = "I"; //\uc218\uac15\uc911
else {
	if(cinfo.b("restudy_yn")) {  //\ubcf5\uc2b5
		progress = "R";
		cuinfo.put("restudy_edate", m.addDate("D", cinfo.i("restudy_day"), cuinfo.s("end_date"), "yyyyMMdd"));
		cuinfo.put("restudy_block", true);
	} else progress = "E"; //\uc885\ub8cc
}
cuinfo.put("restudy_edate_conv", m.time(_message.get("format.date.dot"), cuinfo.s("restudy_edate")));
cuinfo.put("progress", progress);
cuinfo.put("status_conv", m.getValue(progress, courseUser.progressListMsg));
if("Y".equals(cuinfo.s("close_yn"))) cuinfo.put("status_conv", "\ub9c8\uac10");

cuinfo.put("tutor_name", !"".equals(cuinfo.s("tutor_name")) ? cuinfo.s("tutor_name") : "-");
cuinfo.put("start_date_conv", m.time(_message.get("format.date.dot"), cuinfo.s("start_date")));
cuinfo.put("end_date_conv", m.time(_message.get("format.date.dot"), cuinfo.s("end_date")));
cuinfo.put("past_day", m.diffDate("D", cuinfo.s("start_date"), today));  //\uacbd\uacfc\uc77c

cuinfo.put("total_score_conv", m.nf(cuinfo.d("total_score"), 1));
cuinfo.put("progress_ratio", m.nf(cuinfo.d("progress_ratio"), 1));
cuinfo.put("progress_ratio_conv", m.nf(cuinfo.d("progress_ratio"), 1));
cuinfo.put("exam_value_conv", m.nf(cuinfo.d("exam_value"), 1));
cuinfo.put("homework_value_conv", m.nf(cuinfo.d("homework_value"), 1));
cuinfo.put("forum_value_conv", m.nf(cuinfo.d("forum_value"), 1));
cuinfo.put("etc_value_conv", m.nf(cuinfo.d("etc_value"), 1));

cuinfo.put("progress_score_conv", m.nf(cuinfo.d("progress_score"), 1));
cuinfo.put("exam_score_conv", m.nf(cuinfo.d("exam_score"), 1));
cuinfo.put("homework_score_conv", m.nf(cuinfo.d("homework_score"), 1));
cuinfo.put("forum_score_conv", m.nf(cuinfo.d("forum_score"), 1));
cuinfo.put("etc_score_conv", m.nf(cuinfo.d("etc_score"), 1));


//\ucc44\ub110
String ch = "classroom";

p.setVar("cuinfo", cuinfo);
p.setVar("course", cinfo);


    

//\uae30\ubcf8\ud0a4
int pid = m.ri("pid");
int id = m.ri("id");
if(id == 0 || pid == 0) { m.jsError(_message.get("alert.common.required_key")); return; }

//\uac1d\uccb4
ForumDao forum = new ForumDao();
ForumUserDao forumUser = new ForumUserDao();
ForumPostDao forumPost = new ForumPostDao();
CourseProgressDao courseProgress = new CourseProgressDao();
FileDao file = new FileDao();

//\uc815\ubcf4
DataSet info = courseModule.query(
	"SELECT a.*, f.forum_nm, f.forum_file, f.content forum_content "
	+ ", u.user_id, u.submit_yn, u.score, u.marking_score, u.confirm_yn, u.mod_date "
	+ ", u.post_cnt "
	+ " FROM " + courseModule.table + " a "
	+ " INNER JOIN " + forum.table + " f ON a.module_id = f.id AND f.status != -1 AND f.id = " + id + " "
	+ " LEFT JOIN " + forumUser.table + " u ON "
		+ "u.forum_id = a.module_id AND u.course_user_id = " + cuid + " "
	+ " WHERE a.status = 1 AND a.module = 'forum' "
	+ " AND a.course_id = " + courseId + " AND f.site_id = " + siteId + ""
);
if(!info.next()) { m.jsError(_message.get("alert.common.nodata")); return; };

//\ud3ec\ub9f7\ud305
boolean isReady = false; //\ub300\uae30
boolean isEnd = false; //\uc644\ub8cc
if("1".equals(info.s("apply_type"))) { //\uc2dc\uc791\uc77c
	info.put("start_date_conv", m.time(_message.get("format.datetime.dot"), info.s("start_date")));
	info.put("end_date_conv", m.time(_message.get("format.datetime.dot"), info.s("end_date")));

	isReady = 0 > m.diffDate("I", info.s("start_date"), now);
	isEnd = 0 < m.diffDate("I", info.s("end_date"), now);

	info.put("apply_type_1", true);
	info.put("apply_type_2", false);
} else if("2".equals(info.s("apply_type"))) { //\ucc28\uc2dc
	info.put("apply_conv", info.i("chapter") == 0 ? _message.get("classroom.module.before_study") : _message.get("classroom.module.after_study", new String[] { "chapter=>" + info.i("chapter") }));
	if(info.i("chapter") > 0 && 0 == courseProgress.findCount("course_id = " + courseId + " AND chapter = " + info.i("chapter") + " AND complete_yn = 'Y'")) isReady = true;

	info.put("apply_type_1", false);
	info.put("apply_type_2", true);
}

//\uc815\ubcf4
DataSet pinfo = forumPost.query(
	"SELECT a.*, u.score, u.confirm_yn "
	+ " FROM " + forumPost.table + " a "
	+ " LEFT JOIN " + forumUser.table + " u ON a.forum_id = u.forum_id AND u.course_user_id = a.course_user_id "
	+ " WHERE a.status = 1 AND a.id = " + pid + " "
	+ " AND a.course_id = '" + courseId + "' "
);
if(!pinfo.next()) { m.jsError(_message.get("alert.common.nodata")); return; }

boolean isOpen = !isReady && !isEnd && "I".equals(progress) && !info.b("confirm_yn") && pinfo.i("course_user_id") == cuid;
info.put("open_block", isOpen);

if(isOpen) {

	//\uc0ad\uc81c
	if("del".equals(m.rs("mode"))) {
		if(!"".equals(pinfo.s("post_file"))) {
			forumPost.item("post_file", "");
			if(!forumPost.update("id = " + pid + "")) {
				m.jsAlert(_message.get("alert.file.error_delete")); return;
			}
			m.delFileRoot(m.getUploadPath(pinfo.s("post_file")));
		}
		return;
	}


	//\uc0ad\uc81c
	if("pdel".equals(m.rs("mode"))) {
		forumPost.item("status", -1);
		if(!forumPost.update("id = " + pid + "")) { m.jsError(_message.get("alert.common.error_delete")); return; }

		forumUser.item("post_cnt", forumPost.findCount("status= 1 AND forum_id = " + id + " AND course_user_id = " + cuid + ""));
		forumUser.item("mod_date", now);
		if(!forumUser.update("forum_id = " + id + " AND course_user_id = " + cuid + "")) {
			m.jsError(_message.get("alert.common.error_delete")); return;
		}

		m.jsReplace("forum_view.jsp?" + m.qs("pid, mode"), "parent");

		return;
	}

	//\ud3fc\uc785\ub825
	f.addElement("subject", pinfo.s("subject"), "hname:'\uc81c\ubaa9', required:'Y'");
	f.addElement("post_file", null, "hname:'\ucca8\ubd80\ud30c\uc77c'");
	f.addElement("content", null, "hname:'\ub0b4\uc6a9', allowhtml:'Y'");

	//\uc218\uc815
	if(m.isPost() && f.validate()) {

		forumPost.item("subject", f.get("subject"));
		forumPost.item("content", f.get("content"));

		File f1 = f.saveFile("post_file");
		if(f1 != null) {
			forumPost.item("post_file", f.getFileName("post_file"));
			if(!"".equals(pinfo.s("post_file"))) m.delFileRoot(m.getUploadPath(pinfo.s("post_file")));
		}

		forumPost.item("mod_date", now);
		if(!forumPost.update("id = " + pid + "")) { m.jsAlert(_message.get("alert.common.error_modify")); return; }

		//\uac31\uc2e0
		forumUser.execute(
			"UPDATE " + forumUser.table + " SET "
			+ " mod_date = '" + now + "' "
			+ " WHERE forum_id = " + id + " AND course_user_id = " + cuid + " "
		);

		m.jsReplace("forum_view.jsp?" + m.qs("pid, mode"), "parent");
		return;
	}
}

pinfo.put("post_file_conv", m.encode(pinfo.s("post_file")));
pinfo.put("post_file_ek", m.encrypt(pinfo.s("post_file") + m.time("yyyyMMdd")));
pinfo.put("post_file_ext", file.getFileIcon(pinfo.s("post_file")));
pinfo.put("reg_date_conv", m.getTimeString("yyyy.MM.dd HH:mm", pinfo.s("reg_date")));
pinfo.put("content_conv", m.htt(pinfo.s("content")));

//\uac31\uc2e0
String[] readArray = m.getCookie("CFREAD").split("\\,");
if(!m.inArray(""+pid + "/" + userId, readArray)) {
	forumPost.updateHitCount(pid);
	String tmp = m.join(",", readArray);
	tmp = "".equals(tmp) ? "" + pid + "/" + userId : tmp + "," + pid + "/" + userId;
	m.setCookie("CFREAD", tmp, 3600 * 24);
}

//\ucd9c\ub825
p.setLayout(ch);
p.setBody("classroom.forum_read");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("pid, mode"));
p.setVar("form_script", f.getScript());

p.setVar("forum", info);
p.setVar("post", pinfo);

p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("classroom/forum_read.jsp"), -3292668070041023724L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("classroom/init.jsp"), 3102514259663679587L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 2912615399035486559L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
