/*
 * JSP generated by Resin-4.0.67 (built Thu, 01 Aug 2024 10:12:42 PDT)
 */

package _jsp._sysop._board;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();
String tplRoot = Config.getDocRoot() + "/sysop/html";

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch (RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage()); return; }
catch (Exception ex) { m.errorLog("\uc81c\ud55c \uc6a9\ub7c9 \ucd08\uacfc - " + ex.getMessage()); return; }

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/home/lms/public_html/html");

SiteDao Site = new SiteDao();
DataSet siteinfo = Site.getSiteInfo(request.getServerName(), "sysop");
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("sysop_status") || "".equals(siteinfo.s("doc_root"))) { m.jsReplace("/main/guide.jsp", "top"); return; }
//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 60\ubd84
siteinfo.put("sysop_session_hour", 60);
//B2b\uc0ac\uc6a9X
SiteConfig.put("join_b2b_yn", "N");

//String siteDomain = request.getScheme() + "://" + request.getServerName();
String siteDomain = "https://" + request.getServerName();
/*int port = request.getServerPort();
if(port != 80) siteDomain += ":" + port;*/
String webUrl = siteDomain + "/sysop";

String dataDir = siteinfo.s("doc_root") + "/data";
f.dataDir = dataDir;
m.dataDir = dataDir;
//m.dataUrl = Config.getDataUrl() + (!"/data".equals(Config.getDataUrl()) ? siteinfo.s("ftp_id") : "");
m.dataUrl = Config.getDataUrl();

boolean isDevServer = -1 < request.getServerName().indexOf("lms.malgn.co.kr");
siteinfo.put("logo_url", (!"/data".equals(Config.getDataUrl()) ? "" : siteDomain) + m.getUploadUrl(siteinfo.s("logo")));

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr(); //Lb \uc0ac\uc6a9
if(userIp.contains(",")) {
	String[] userIpArr = m.split(",", userIp);
	userIp = userIpArr[0].trim();
}

boolean isMalgnOffice = "1.212.252.90|3.35.211.181|52.79.184.225|127.0.0.1".contains(userIp);
isMalgnOffice = true;
//if(!"".equals(siteinfo.s("allow_ip_sysop")) && !isMalgnOffice && !Site.checkIP(userIp, siteinfo.s("allow_ip_sysop"))) {
//	m.redirect("/");
//	return;
//}

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
//String sysLocale = "default";
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

//\uae30\ubcf8 \ud68c\uc6d0\uc815\ubcf4
int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
String manageCourses = "";
String userSessionId = "";
String pagreeDate = "";
boolean isUserMaster = false;
String winTitle = "[\uad00\ub9ac\uc790] " + siteinfo.s("site_nm");
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
String surl = request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : "");
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));
final int sysExcelCnt = 20000;

SessionDao mSession = new SessionDao(request, response);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "MLMSKEY2014" + siteId + "7";
if(0 < siteinfo.i("sysop_session_hour")) auth.setValidTime(siteinfo.i("sysop_session_hour") * 60);
if(auth.isValid()) {
	userId = m.parseInt(auth.getString("ID"));
	loginId = auth.getString("LOGINID");
	userName = auth.getString("NAME");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	manageCourses = auth.getString("MANAGE_COURSES");
	userSessionId = userSessionId = auth.getString("SESSIONID");
	pagreeDate = auth.getString("PAGREE_DATE");
	isUserMaster = "Y".equals(auth.getString("IS_USER_MASTER"));

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if(request.getRequestURI().indexOf("/main/auth2.jsp") == -1
		//&& "Y".equals(siteinfo.s("auth2_yn"))
		&& !"Y".equals(auth.getString("AUTH2_YN"))
		//&& !"".equals(siteinfo.s("auth2_type"))
		//&& !"malgn".equals(loginId)
		&& request.getRequestURI().indexOf("/main/otpkey_register.jsp") == -1
		&& request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1
		&& request.getRequestURI().indexOf("/main/modify_passwd.jsp") == -1
	) {
		m.jsReplace("/sysop/main/auth2.jsp?returl=" + m.rs("returl", "/sysop/index.jsp"), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& -1 == request.getRequestURI().indexOf("/sysop/main/logout.jsp")
		&& -1 == request.getRequestURI().indexOf("/sysop/main/login.jsp")
		&& -1 == request.getRequestURI().indexOf("/main/modify_passwd.jsp")
	) {
		m.jsReplace("/sysop/main/logout.jsp");
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

} else {
	if(request.getRequestURI().indexOf("/main/login.jsp") == -1
		&& request.getRequestURI().indexOf("/vod/upload.jsp") == -1
		&& request.getRequestURI().indexOf("/main/slogin.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_template.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_maildir.jsp") == -1
		&& (request.getRequestURI().indexOf("/user/sleep_insert.jsp") == -1 || !"log".equals(m.rs("after")))
	) {
		m.jsReplace(auth.loginURL, "top");
		return;
	}
}

MenuDao Menu = new MenuDao(p, siteId, "default");
SiteMenuDao SiteMenu = new SiteMenuDao();

boolean superBlock = "S".equals(userKind);
boolean adminBlock = "S".equals(userKind) || "A".equals(userKind);
boolean courseManagerBlock = "C".equals(userKind);
boolean deptManagerBlock = "D".equals(userKind);

//boolean isAuthCrm = superBlock || (-1 < siteinfo.s("auth_crm").indexOf("|" + userKind + "|"));
boolean isAuthCrm = superBlock || Menu.accessible(-999, userId, userKind, false);

//\ub85c\uadf8\uc544\uc6c3-\uacfc\uc815\uc6b4\uc601\uc790
if(courseManagerBlock && "".equals(manageCourses) && request.getRequestURI().indexOf("/main/logout.jsp") == -1) {
	m.jsAlert("\ub2f4\ub2f9\ud55c \uacfc\uc815\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\\n \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc138\uc694.");
	m.jsReplace("/sysop/main/logout.jsp", "top");
	return;
}

//\ub9e4\ub274\uc5bc
ManualDao Manual = new ManualDao();
int ManualId = Menu.getOneInt("SELECT manual_id FROM " + Menu.table + " WHERE link = '" + m.replace(request.getRequestURI(), "/sysop", "..") + "'");
if(0 < ManualId) {
	int ManualStatus = Manual.getOneInt("SELECT status FROM " + Manual.table + " WHERE id = " + ManualId);
	if(0 < ManualStatus) p.setVar("SYS_MENU_MANUAL_ID", ManualId);
}

p.setVar("WEB_URL", webUrl);
p.setVar("FRONT_URL", siteDomain);
p.setVar("SYS_TITLE", winTitle);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("IS_AUTH_CRM", isAuthCrm);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_COMMON_CDN", "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);

p.setVar("user_master_block", isUserMaster || isMalgnOffice);
p.setVar("malgn_office_block", isMalgnOffice);
p.setVar("super_block", superBlock);
p.setVar("admin_block", adminBlock);
p.setVar("course_manager_block", courseManagerBlock);
p.setVar("dept_manager_block", deptManagerBlock);
p.setVar("SYS_URL", surl);

//boolean isBlindUser = !sysToday.equals(pagreeDate);
//p.setVar("SYS_BLINDUSER", isBlindUser);

//\uac1c\uc778\uc815\ubcf4\ucc98\ub9ac \uc218\uc815 - 2024.03.25
boolean isBlindUser = !"Y".equals(m.getCookie("PCONFIRM_YN"));
p.setVar("SYS_BLINDUSER", isBlindUser);
p.setVar("PCONFIRM_YN", m.getCookie("PCONFIRM_YN"));
String inquiryPurpose = m.getCookie("INQUIRYPURPOSE");

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
UserSession.setType("sysop");
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && "N".equals(siteinfo.s("dup_sysop_yn")) && ("".equals(userSessionId) || userSessionId == null || !UserSession.isValid(userSessionId, userId))) {
	if(request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1) {
		m.jsAlert("\uc138\uc158\uc774 \ub9cc\ub8cc\ub418\uc5c8\uac70\ub098 \uc911\ubcf5 \ub85c\uadf8\uc778\uc774 \ub418\uc5b4 \uc790\ub3d9\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ub429\ub2c8\ub2e4.");
		m.jsReplace("/sysop/main/logout.jsp?mode=session", "top");
		return;
	}
}

InfoLogDao _log = new InfoLogDao(siteId); _log.setItems(userId, "B", surl, userIp);
InfoUserDao _logUser = new InfoUserDao(siteId);


    

//\uc544\uc774\ub514
String code = m.rs("code");
String md = "post";

//\uac1d\uccb4
BoardDao board = new BoardDao();
CategoryDao category = new CategoryDao();
PostDao post = new PostDao();
CommentDao comment = new CommentDao();
FileDao file = new FileDao();
WordFilterDao wordFilterDao = new WordFilterDao();

//\uc815\ubcf4-\uac8c\uc2dc\ud310
//board.d(out);
DataSet binfo = board.find(
	"code = '" + code + "' AND status != -1 AND site_id = " + siteId + ""
	+ (!("A".equals(userKind) || "S".equals(userKind)) ? " AND admin_idx LIKE '%|" + userId + "|%'" : "")
);
if(!binfo.next()) { m.jsError("\ud574\ub2f9 \uac8c\uc2dc\ud310\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

binfo.put("notice_block", binfo.b("notice_yn"));
binfo.put("category_block", binfo.b("category_yn"));
binfo.put("upload_block", binfo.b("upload_yn"));
binfo.put("reply_block", binfo.b("reply_yn"));
binfo.put("comment_block", binfo.b("comment_yn"));

//\ud658\uacbd\uc124\uc815-\ubaa8\ub4c8/\ud0c0\uc785/\uc2a4\ud0a8/\uc0c8\uae00\uae30\uc900
String btype = binfo.s("board_type");
boolean isBoardAdmin = true;
p.setVar(btype + "_type_block", true);

int bid = binfo.i("id");
int newHour = 24;											//\uc0c8\uae00\uae30\uc900(\uc2dc\uac04)
int columnCnt = 5;											//\uac24\ub7ec\ub9ac\uc6a9 \uceec\ub7fc\uc218
int listNum = 20;
p.setVar("contentwidth", post.getContentWidth());

DataSet categories = binfo.b("category_yn") ? category.getList("board", bid, siteId) : new DataSet();	//\uce74\ud14c\uace0\ub9ac

//\ucc44\ub110
String ch = "sysop";


    

//\uc811\uadfc\uad8c\ud55c
if(!(Menu.accessible(80, userId, userKind))) { m.jsError("\uc811\uadfc \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
UserDao user = new UserDao(isBlindUser);
PostLogDao postLog = new PostLogDao(siteId);

//\ud3fc\uccb4\ud06c
f.addElement("s_category_id", null, null);
f.addElement("s_proc_status", null, null);
f.addElement("s_field", null, null);
f.addElement("s_keyword", null, null);
f.addElement("s_listnum", null, null);

//\uc21c\uc11c\uc800\uc7a5
if(m.isPost()) {
	String idx[] = m.reqArr("id");
	String sorts[] = m.reqArr("sort");

	if(idx == null || sorts == null) { m.jsError("\uc21c\uc11c\ub97c \uc815\ub82c\ud560 \uac15\uc0ac\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

	for(int i = 0; i < idx.length; i++) {
		post.item("sort", sorts[i]);
		post.update("id = " + idx[i] + " AND site_id = " + siteId);
	}

	m.redirect("index.jsp?" + m.qs("id,sort"));
	return;
}

//\ubaa9\ub85d
ListManager lm = new ListManager(jndi);
//lm.d(out);
lm.setRequest(request);
lm.setListNum("excel".equals(m.rs("mode")) ? 60000 : f.getInt("s_listnum", 20));
lm.setTable(
	post.table + " a "
	+ " LEFT JOIN " + category.table + " c ON a.category_id = c.id "
	+ " LEFT JOIN " + file.table + " f ON f.module = 'post' AND f.module_id = a.id AND f.main_yn = 'Y' "
	+ " LEFT JOIN " + user.table + " u ON u.site_id = " + siteId + " AND u.id = a.user_id "
	+ " LEFT JOIN " + postLog.table + " pl ON a.id = pl.post_id AND pl.log_type = 'assign' AND pl.site_id = " + siteId + " "
	+ " LEFT JOIN " + user.table + " pu ON pl.user_id = pu.id AND pu.site_id = " + siteId + " "
);
lm.setFields("a.*, c.category_nm, f.filename, u.login_id, pu.id assign_id, pu.user_nm assign_nm, pu.login_id assign_login_id");
lm.addWhere("a.status > -1");
lm.addWhere("a.board_id = " + bid + "");
if("qna".equals(btype)) lm.addWhere("a.depth = 'A'");
lm.addSearch("a.category_id", f.get("s_category_id"));
lm.addSearch("a.proc_status", f.get("s_proc_status"));
if(!"".equals(f.get("s_field"))) lm.addSearch(f.get("s_field"), f.get("s_keyword"), "LIKE");
else if("".equals(f.get("s_field")) && !"".equals(f.get("s_keyword"))) {
	lm.addSearch("a.subject, a.content, a.writer, u.login_id", f.get("s_keyword"), "LIKE");
}
lm.setOrderBy(!"".equals(m.rs("ord")) ? m.rs("ord") : "a.sort ASC, a.thread ASC, a.depth ASC");

//\ud3ec\ub9f7\ud305
int no = 1;
DataSet list = lm.getDataSet();
while(list.next()) {
	list.put("reg_date_conv", m.time("yyyy.MM.dd HH:mm", list.s("reg_date")));
	list.put("mod_date_conv", m.time("yyyy.MM.dd HH:mm", list.s("mod_date")));

	list.put("comment_conv", list.i("comm_cnt") > 0? "(" + list.i("comm_cnt") + ")" : "" );
	list.put("hit_conv", m.nf(list.i("hit_cnt")));
	list.put("recomm_conv", m.nf(list.i("recomm_cnt")));

	list.put("subject", m.htt(list.s("subject")));
	list.put("subject_conv", m.cutString(list.s("subject"), 76));
	list.put("content_conv", m.nl2br(list.s("content")));
	list.put("category_conv", binfo.b("category_yn") && !"".equals(list.s("category_nm")) ? "[" + list.s("category_nm") + "]" : "");
	list.put("reply_block", list.s("depth").length() > 1);

	list.put("user_id", list.i("user_id") > 0 ? list.s("user_id") : "");
	list.put("login_id_conv", "".equals(list.s("login_id")) ? "-" : list.s("login_id"));

	list.put("new_block", m.diffDate("H", list.s("reg_date"), m.time("yyyyMMddHHmmss")) <= newHour);
	list.put("notice_block", list.b("notice_yn"));
	list.put("status_conv", m.getItem(list.s("status"), post.statusList));
	list.put("display_yn_conv", m.getItem(list.s("display_yn"), post.displayYn));

	//\ud0c0\uc785\ubcc4 \ucc98\ub9ac
	if("board".equals(btype)) {	//\ub9ac\uc2a4\ud2b8\ud615
		//\ub2f5\uae00
		int replyWidth = (list.s("depth").length() - 1) * 15;
		list.put("reply_width", replyWidth > 200 ? 200 : replyWidth);

	} else if("qna".equals(btype)) {	//QNA
		list.put("proc_status_conv", m.getItem(list.s("proc_status"), post.procStatusList));
	}
	user.maskInfo(list);
}

//\uae30\ub85d-\uac1c\uc778\uc815\ubcf4\uc870\ud68c
if("".equals(m.rs("mode")) && list.size() > 0 && !isBlindUser) _log.add("L", Menu.menuNm, list.size(), "\uc774\ub7ec\ub2dd \uc6b4\uc601", list);

//\uc5d1\uc140
if("excel".equals(m.rs("mode"))) {
	if(list.size() > 0 && !isBlindUser) _log.add("E", Menu.menuNm, list.size(), "\uc774\ub7ec\ub2dd \uc6b4\uc601", list);

	ExcelWriter ex = new ExcelWriter(response, binfo.s("board_nm") + "(" + m.time("yyyy-MM-dd") + ").xls");
	ex.setData(list, new String[] { "__ord=>No", "id=>\uac8c\uc2dc\ubb3c\uc544\uc774\ub514", "category_conv=>\uce74\ud14c\uace0\ub9ac", "thread=>thread", "depth=>depth", "writer=>\uc791\uc131\uc790", "login_id=>\ub85c\uadf8\uc778\uc544\uc774\ub514", "subject=>\uc81c\ubaa9", "youtube_cd=>YouTube\uc601\uc0c1\ucf54\ub4dc", "content_conv=>\ub0b4\uc6a9", "notice_yn=>\uacf5\uc9c0\uae00\uc5ec\ubd80", "secret_yn=>\ube44\ubc00\uae00\uc5ec\ubd80", "hit_cnt=>\uc870\ud68c\uc218", "comm_cnt=>\ub313\uae00\uc218", "recomm_cnt=>\ucd94\ucc9c\uc218", "file_cnt=>\ucca8\ubd80\ud30c\uc77c\uc218", "display_yn_conv=>\ub178\ucd9c\uc5ec\ubd80", "sort=>FAQ\uc815\ub82c\uc21c\uc11c", "proc_status_conv=>QNA\ub2f5\ubcc0\uc0c1\ud0dc", "mod_date_conv=>\uc218\uc815\uc77c\uc2dc", "reg_date_conv=>\ub4f1\ub85d\uc77c\uc2dc", "status_conv=>\uc0c1\ud0dc"}, binfo.s("board_nm") + "(" + m.time("yyyy-MM-dd") + ")");
	ex.write();
	return;
}//

//\ube48\uceec\ub7fc-\uac24\ub7ec\ub9ac
DataSet xlist = new DataSet();
if("gallery".equals(btype)) {
	int remain = columnCnt - (list.size() % columnCnt);
	if(remain != columnCnt) {
		for(int i = 0; i < remain; i++) {
			xlist.addRow();
		}
	}
}

//\uacf5\uc9c0\uc0ac\ud56d/\ubca0\uc2a4\ud2b8/\uc0c1\uc704
DataSet notices = new DataSet();
if(binfo.b("notice_yn")) {
	notices = post.query(
		"SELECT a.*, c.category_nm, f.filename, u.login_id "
		+ " FROM " + post.table + " a "
		+ " LEFT JOIN " + category.table + " c ON a.category_id = c.id "
		+ " LEFT JOIN " + file.table + " f ON f.module = 'post' AND f.module_id = a.id AND f.main_yn = 'Y' "
		+ " LEFT JOIN " + user.table + " u ON u.site_id = " + siteId + " AND u.id = a.user_id "
		+ " WHERE a.status = 1 AND a.board_id = " + bid + " "
		+ " AND a.notice_yn = 'Y' "
		+ " ORDER BY a.thread ASC, a.depth ASC "
	);

	no = 1;
	while(notices.next()) {
		notices.put("reg_date_conv", m.time("yyyy.MM.dd HH:mm", notices.s("reg_date")));
		notices.put("mod_date_conv", m.time("yyyy.MM.dd HH:mm", notices.s("mod_date")));

		notices.put("comment_conv", notices.i("comm_cnt") > 0? "(" + notices.i("comm_cnt") + ")" : "" );
		notices.put("hit_conv", m.nf(notices.i("hit_cnt")));
		notices.put("recomm_conv", m.nf(notices.i("recomm_cnt")));

		notices.put("subject", m.htt(notices.s("subject")));
		notices.put("subject_conv", m.cutString(notices.s("subject"), 80));
		notices.put("category_conv", binfo.b("category_yn") && !"".equals(notices.s("category_nm")) ? "[" + notices.s("category_nm") + "]" : "");
		notices.put("reply_block", notices.s("depth").length() > 1);
		notices.put("new_block", m.diffDate("H", notices.s("reg_date"), m.time("yyyyMMddHHmmss")) <= newHour);

		notices.put("user_id", notices.i("user_id") > 0 ? notices.s("user_id") : "");
		notices.put("login_id_conv", "".equals(notices.s("login_id")) ? "-" : notices.s("login_id"));
		notices.put("display_yn_conv", m.getItem(notices.s("display_yn"), post.displayYn));

		//\ud0c0\uc785\ubcc4 \ucc98\ub9ac
		if("gallery".equals(btype)) {			//\uac24\ub7ec\ub9ac\ud615
			notices.put("subject_conv", m.cutString(notices.s("subject"), 16));
			notices.put("newline", no % columnCnt == 0 && notices.size() != no ? "</tr></tbody></table>\n<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr align=\"center\">" : "");
			notices.put("picture_url", m.getUploadUrl(notices.s("filename")));

		} else if("webzine".equals(btype)) {	//\uc6f9\uc9c4\ud615
			notices.put("subject_conv", m.cutString(notices.s("subject"), 90));
			notices.put("content_conv", m.cutString(m.stripTags(notices.s("content")), 300));
			notices.put("picture_url", m.getUploadUrl(notices.s("filename")));
		}
		no++;
	}
}


//\ucd9c\ub825
p.setLayout(ch);
p.setBody("board.list");
p.setVar("p_title", binfo.s("board_nm"));
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id"));
p.setVar("form_script", f.getScript());

p.setLoop("list", list);
p.setVar("pagebar", lm.getPaging());
p.setVar("list_total", lm.getTotalString());
p.setLoop("xlist", xlist);

p.setVar("board", binfo);
p.setLoop("categories", categories);
p.setLoop("notices", notices);
p.setLoop("proc_status_list", m.arr2loop(post.procStatusList));
p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5413665724253103304L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/board/index.jsp"), -1869094692650610576L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/board/init.jsp"), -2159147454975939377L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 4999103467299093826L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
