/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._order;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _cart_0list__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

//request.setCharacterEncoding("utf-8");

final String BUILDVERSION = "24.02.01";

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(RuntimeException re) {
	m.errorLog("Overflow file size. - " + re.getMessage(), re);
	return;
}
catch(Exception ex) {
	m.errorLog("Overflow file size. - " + ex.getMessage(), ex);
	return;
}

SiteDao Site = new SiteDao(); //Site.clear();
DataSet siteinfo = Site.getSiteInfo(request.getServerName());
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("status") || "".equals(siteinfo.s("doc_root"))) {
	//m.jsReplace("about:blank", "top");
	return;
}

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//CSAP \uc18c\uc15c \ub85c\uadf8\uc778 \uc0ac\uc6a9 \uc548\ud568
siteinfo.put("oauth_vendor", "");
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 1\uc2dc\uac04
siteinfo.put("session_hour", 1);
//\uacb0\uc81c\ud398\uc774\uc9c0 \uc548\ub0b4 \ubb38\uad6c
String allowTags = "a,b,br,cite,code,dd,dl,dt,div,em,i,li,ol,p,pre,q,small,span,strike,strong,sub,sup,u,ul,article,aside,details,div,dt,figcaption,footer,form,fieldset,header,hgroup,html,main,nav,section,summary,body,p,dl,multicol,dd,figure,address,center,blockquote,h1,h2,h3,h4,h5,h6,listing,xmp,pre,plaintext,menu,dir,ul,ol,li,hr,table,tbody,thead,tfoot,th,tr,td,caption,textarea,img,input,textarea,hr,iframe,video,audio";
String allowRegexr = "<(\\/?)(?!.*" + Malgn.replace(allowTags, ",", "[ >]|.*") + "[ >])([^>]*)>";
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("pay_notice", siteinfo.s("pay_notice").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(allowRegexr, "&lt;$1$2&gt;"));
siteinfo.put("copyright", siteinfo.s("copyright").replaceAll(" on([^\\t\\n\\f\\- \\/>\"'=]+\\s*)=", " on-$1="));

//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));
boolean isDevServer = -1 < request.getServerName().indexOf("politech.malgn.co.kr");
String webUrl = request.getScheme() + "://" + request.getServerName();
int port = request.getServerPort();
if(port != 80 && port != 443) webUrl += ":" + port;
String dataDir = siteinfo.s("doc_root") + "/data";
String tplRoot = siteinfo.s("doc_root") + "/html";
f.dataDir = dataDir;
m.dataDir = dataDir;
m.dataUrl = Config.getDataUrl();

if(!"".equals(siteinfo.s("logo"))) siteinfo.put("logo_url", m.getUploadUrl(siteinfo.s("logo")));
else siteinfo.put("logo_url", "/common/images/default/malgn_logo.jpg");

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr();
if(!"".equals(siteinfo.s("allow_ip_user")) && !Site.checkIP(userIp, siteinfo.s("allow_ip_user"))) {
	m.redirect("/main/guide.jsp");
	return;
}

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/Users/kyounghokim/IdeaProjects/MalgnLMS/public_html/html");

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String loginMethod = "";
String userName = "";
String userEmail = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
int userGroupDisc = 0;
//String aloginYn = "";
String userSessionId = "";
boolean userB2BBlock = false;
String userB2BName = "";
String userB2BFile = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean isRespWeb = (5 <= siteinfo.i("skin_cd"));
boolean isGoMobile = !isRespWeb && m.isMobile();
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));

SessionDao mSession = new SessionDao(request, response);

DataSet auth2Info = Config.getDataSet("//config/userAuth2");
auth2Info.next();

Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "MLMS14" + siteId + "7";
if(0 < siteinfo.i("session_hour")) auth.setValidTime(siteinfo.i("session_hour") * 3600);
if(auth.isValid()) {
	userId = auth.getInt("ID");
	loginId = auth.getString("LOGINID");
	loginMethod = auth.getString("LOGINMETHOD");
	userName = auth.getString("NAME");
	userEmail = auth.getString("EMAIL");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	userGroupDisc = !"null".equals(auth.getString("GROUPS_DISC")) ? m.parseInt(auth.getString("GROUPS_DISC")) : 0;
	//aloginYn = auth.getString("ALOGIN_YN");
	userSessionId = auth.getString("SESSIONID");
	userB2BName = auth.getString("B2BNAME");
	userB2BFile = auth.getString("B2BFILE");
	if(userGroups != null) {
		if(-1 < userGroups.indexOf(",")) for(String userGroupId : m.split(",", userGroups)) p.setVar("SYS_USERGROUP_" + userGroupId, true);
		else p.setVar("SYS_USERGROUP_" + userGroups, true);
	}

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if("direct".equals(loginMethod)
		&& "Y".equals(auth2Info.s("auth2Yn"))
		&& !"Y".equals(auth.getString("USER_AUTH2_YN"))
		&& "Y".equals(auth.getString("DEPT_AUTH2_YN")) //\uad00\ub9ac\uc790\ub2e8-\ud68c\uc6d0\uc18c\uc18d\uad00\ub9ac\uc5d0\uc11c 2\ucc28\uc778\uc99d\uc124\uc815 \uc5ec\ubd80 Y/N	 20230126
		//&& !"".equals(auth.getString("USER_AUTH2_TYPE"))
		//&& !"malgn".equals(loginId)
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/auth2.jsp?returl=" + Malgn.urlencode(m.getThisURI()), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		m.jsReplace("/member/logout.jsp");
		return;
	}

	if(
		(
			(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) //\uc0dd\ub144\uc6d4\uc77c
			|| (1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) //\uc131\ubcc4
			|| (1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) //\ud734\ub300\uc804\ud654\ubc88\ud638
			|| ("".equals(auth.getString("NAME"))) //\uc131\uba85
			|| ("".equals(auth.getString("EMAIL"))) //\uc774\uba54\uc77c
		)
		&& !request.getRequestURI().startsWith("/member/logout.jsp")
		&& !request.getRequestURI().startsWith("/member/login.jsp")
		&& !request.getRequestURI().startsWith("/member/privacy_agree.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_verify.jsp")
		&& !request.getRequestURI().startsWith("/main/site_cache.jsp")
		&& !request.getRequestURI().startsWith("/member/auth2.jsp")
		&& !request.getRequestURI().startsWith("/member/otpkey_register.jsp")
		&& !request.getRequestURI().startsWith("/member/alogin.jsp")
		&& !request.getRequestURI().startsWith("/member/slogin.jsp")
		&& !request.getRequestURI().startsWith("/member/login_facebook.jsp")
		&& !request.getRequestURI().startsWith("/member/login_google.jsp")
		&& !request.getRequestURI().startsWith("/member/login_kakao.jsp")
		&& !request.getRequestURI().startsWith("/member/login_line.jsp")
		&& !request.getRequestURI().startsWith("/member/login_naver.jsp")
		&& !request.getRequestURI().startsWith("/classroom/attend_insert.jsp")
		&& !request.getRequestURI().startsWith("/mypage/modify_passwd.jsp")
	) {
		int tut = m.getUnixTime();
		String tek = m.encrypt(tut + "|" + loginId + "|7B1F83A608723CEDDFA9AED338FC796C", "SHA-256");
		String noInfoString = "";

		if(1 < SiteConfig.i("join_birthday_status") && "".equals(auth.getString("BIRTHDAY"))) noInfoString = "\uc0dd\ub144\uc6d4\uc77c";
		else if(1 < SiteConfig.i("join_gender_status") && "".equals(auth.getString("GENDER"))) noInfoString = "\uc131\ubcc4";
		else if(1 < SiteConfig.i("join_mobile_status") && "".equals(auth.getString("MOBILE"))) noInfoString = "\ud734\ub300\uc804\ud654\ubc88\ud638";
		else if("".equals(auth.getString("NAME"))) noInfoString = "\uc131\uba85";
		else if("".equals(auth.getString("EMAIL"))) noInfoString = "\uc774\uba54\uc77c";
		m.jsAlert("\ud68c\uc6d0 \ud544\uc218 \uc815\ubcf4 [" + noInfoString + "](\uc774)\uac00 \ub204\ub77d\ub418\uc5b4\\n\uc218\uc815\ud398\uc774\uc9c0\ub85c \uc774\ub3d9\ud569\ub2c8\ub2e4.");
		m.jsReplace("/mypage/modify.jsp?ek=" + tek + "&ut=" + tut);
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

	p.setVar("login_block", true);
} else {
	p.setVar("login_block", false);

	if(siteinfo.b("close_yn")) {
		boolean isNeedLogin = true;
		String[] exceptPages = m.split("|", siteinfo.s("close_except"));

		if(-1 < request.getRequestURI().indexOf("/member/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/find.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/alogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/slogin_input.jsp")
			|| -1 < request.getRequestURI().indexOf("/member/sysop_slogin.jsp")
			|| -1 < request.getRequestURI().indexOf("/main/site_cache.jsp")
			|| -1 < request.getRequestURI().indexOf("/mobile/login.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate.jsp")
			|| -1 < request.getRequestURI().indexOf("/mypage/certificate_course.jsp")
			|| -1 < request.getRequestURI().indexOf("/kollus/check_api.jsp")
			|| -1 < request.getRequestURI().indexOf("/common/")
			|| -1 < request.getRequestURI().indexOf("/api/auto_send.jsp")
		) {
			isNeedLogin = false;
		} else if(!"".equals(siteinfo.s("close_except"))) {
			for(int i = 0; i < exceptPages.length; i++) {
				if(-1 < request.getRequestURI().indexOf(exceptPages[i])) { isNeedLogin = false; continue; }
			}
		}

		if(isNeedLogin) {
			m.redirect(!isGoMobile ? auth.loginURL : "/mobile/login.jsp");
			return;
		}
	}
}

userB2BBlock = !"".equals(userB2BName) && null != userB2BName;
p.setVar("SYS_HTTPHOST", request.getServerName());
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERID", userId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SYS_DEPTID", userDeptId);
p.setVar("SYS_GROUP_DISC", userGroupDisc);
p.setVar("SYS_B2BBLOCK", userB2BBlock);
p.setVar("SYS_B2BNAME", userB2BName);
p.setVar("SYS_B2BFILE", userB2BFile);
p.setVar("SYS_PAGE_URL", request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : ""));
p.setVar("SYS_TITLE", siteinfo.s("site_nm"));
p.setVar("webUrl", webUrl);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("CURR_DATE", m.time("yyyyMMdd"));
p.setVar("SYS_EK", m.encrypt(loginId + siteinfo.s("sso_key") + m.time("yyyyMMdd"), "SHA-256"));
p.setVar("IS_RESP_WEB", isRespWeb);
p.setVar("IS_MOBILE", m.isMobile());
p.setVar("IS_GO_MOBILE", isGoMobile);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);
p.setVar("script", siteinfo.s("header_script"));

for(int IndexSkin = 1; IndexSkin < 5; IndexSkin++) {
	p.setVar("SKIN_LT_" + IndexSkin, siteinfo.i("skin_cd") < IndexSkin);
	p.setVar("SKIN_LTE_" + IndexSkin, siteinfo.i("skin_cd") <= IndexSkin);
	p.setVar("SKIN_GT_" + IndexSkin, siteinfo.i("skin_cd") > IndexSkin);
	p.setVar("SKIN_GTE_" + IndexSkin, siteinfo.i("skin_cd") >= IndexSkin);
}

MenuDao Menu = new MenuDao(p, sysLocale);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && !siteinfo.b("duplication_yn") && !UserSession.isValid(userSessionId, userId)) {
	if(request.getRequestURI().indexOf("/member/logout.jsp") == -1 && request.getRequestURI().indexOf("/mobile/logout.jsp") == -1) {
		m.jsAlert(_message.get("alert.common.logout_session"));
		if(request.getRequestURI().indexOf("/mobile/") != -1) m.jsReplace("/mobile/logout.jsp?mode=session");
		else m.jsReplace("/member/logout.jsp?mode=session");
		return;
	}
}


    out.write('\n');
    

//\ub85c\uadf8\uc778
if(0 == userId) {
    //m.jsAlert("\ub85c\uadf8\uc778\uc774 \ud544\uc694\ud55c \ud398\uc774\uc9c0\uc785\ub2c8\ub2e4.");
    //m.jsReplace("/member/login.jsp");
    auth.loginForm();
    return;
}

//\uc815\ubcf4-\ud68c\uc6d0
UserDao user = new UserDao();
DataSet uinfo = user.find("id = " + userId + " AND status = 1");
if(!uinfo.next()) { m.jsError(_message.get("alert.member.nodata")); return; }
uinfo.put("mobile_conv", !"".equals(uinfo.s("mobile")) ? uinfo.s("mobile") : "");

String ch = m.rs("ch", "mypage");


    

//\uac1d\uccb4
CourseDao course = new CourseDao();
BookDao book = new BookDao();
FreepassDao freepass = new FreepassDao();
OrderDao order = new OrderDao();
OrderItemDao orderItem = new OrderItemDao();
GroupDao group = new GroupDao();

//\uac31\uc2e0-\uacb0\uc81c\ub300\uae30\uc5d0\uc11c \uce74\ud2b8\ub85c \uc62e\uae40
//orderItem.execute("UPDATE " + orderItem.table + " SET status = 10 WHERE order_id = -99 AND status = 20 AND user_id = " + userId);
orderItem.execute("UPDATE " + orderItem.table + " SET order_id = -99, status = 10 WHERE status = 20 AND user_id = " + userId);

//\ubcc0\uc218
String today = m.time("yyyyMMdd");
boolean isReload = false;
boolean isMobile = m.isMobile();
String moveDir = "/" + (!isGoMobile ? "order" : "mobile") + "/";
String tmpGroups = group.getUserGroup(uinfo);
int groupDisc = group.getMaxDiscRatio();

//\ubaa9\ub85d
//orderItem.d(out);
DataSet list = orderItem.query(
	"SELECT a.*"
	+ ", c.id course_id, c.course_type, c.onoff_type, c.request_sdate, c.request_edate, c.credit, c.close_yn, c.sale_yn, c.disc_group_yn course_disc_group_yn "
	+ ", c.price c_price, b.book_price, b.delivery_type, b.delivery_price, b.disc_group_yn book_disc_group_yn "
	+ ", f.price freepass_price, f.disc_group_yn freepass_disc_group_yn "
	+ " FROM " + orderItem.table + " a "
	+ " LEFT JOIN " + course.table + " c ON a.product_type = 'course' AND a.product_id = c.id AND c.status = 1 "
	+ " LEFT JOIN " + book.table + " b ON a.product_type = 'book' AND a.product_id = b.id AND b.sale_yn = 'Y' AND b.status = 1 "
	+ " LEFT JOIN " + freepass.table + " f ON a.product_type = 'freepass' AND a.product_id = f.id AND f.status = 1 "
	+ " WHERE a.user_id = " + userId + " AND a.status = 10 "
	+ " ORDER BY a.course_id ASC, a.product_type DESC, a.id ASC "
);
while(list.next()) {
	list.put("course_block", false);
	list.put("book_block", false);
	list.put("freepass_block", false);
	list.put(list.s("product_type") + "_block", true);
	list.put("use_block", true);
	list.put("unit_price_conv", m.nf(list.i("unit_price")));
	list.put("price_conv", m.nf(list.i("price")));
	list.put("delivery_price_conv", m.nf(list.i("delivery_price")));
	list.put("delivery_block", list.i("delivery_price") > 0);
	list.put("product_type_conv", m.getItem(list.s("product_type"), orderItem.ptypes));
	list.put("credit", m.nf(list.i("credit")));

	orderItem.cancelDiscount(list.i("id"), list.i("coupon_user_id"));

	if("course".equals(list.s("product_type"))) {
		list.put("use_block", true);

		list.put("request_date", "");

		//\uc0ad\uc81c-\uadf8\ub8f9\ud560\uc778\uae08\uc561\uac80\uc0ac
		if(list.b("course_disc_group_yn") && 0 < groupDisc) {
			int discGroupPrice = list.i("price") * groupDisc / 100; //CouponUserDao.getDiscountPrice() \uc640 \ub9de\ucda4
			if(discGroupPrice != list.i("disc_group_price")) {
				orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
				isReload = true;
			}
		} else if(0 < list.i("disc_group_price")) {
			orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
			isReload = true;
		}

		if("R".equals(list.s("course_type"))) {
			list.put("request_date", m.time(_message.get("format.date.dot"), list.s("request_sdate")) + " - " + m.time(_message.get("format.date.dot"), list.s("request_edate")));

			//\uc0ad\uc81c-\uae30\uac04\uc774 \uc9c0\ub09c \uacbd\uc6b0/\uae08\uc561\ud2c0\ub9bc
			if(	0 > m.diffDate("D", list.s("request_sdate"), today)
				|| 0 > m.diffDate("D", today, list.s("request_edate"))
				|| list.b("close_yn")
				|| list.i("price") != list.i("c_price")
			) {
				orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
				isReload = true;
			}

		} else if("A".equals(list.s("course_type"))) {
			//list.put("request_date", "\uc0c1\uc2dc");

			//\uc0ad\uc81c-\uae08\uc561\ud2c0\ub9bc
			if(list.i("price") != list.i("c_price") || list.b("close_yn")) {
				orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
				isReload = true;
			}
		}

		//\uc0ad\uc81c-\ud310\ub9e4\ub9c8\uac10
		if(!list.b("sale_yn")) {
			orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
			isReload = true;
		}

	} else if("book".equals(list.s("product_type"))) {
		//list.put("use_block", list.i("pay_price") == list.i("book_price"));
		list.put("use_block", true);

		//\uc0ad\uc81c-\uadf8\ub8f9\ud560\uc778\uae08\uc561\uac80\uc0ac
		if(list.b("book_disc_group_yn") && 0 < groupDisc) {
			int discGroupPrice = list.i("price") * groupDisc / 100; //CouponUserDao.getDiscountPrice() \uc640 \ub9de\ucda4
			if(discGroupPrice != list.i("disc_group_price")) {
				orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
				isReload = true;
			}
		} else if(0 < list.i("disc_group_price")) {
			orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
			isReload = true;
		}

		//\uc0ad\uc81c-\uae08\uc561\ud2c0\ub9bc
		if(list.i("unit_price") != list.i("book_price")) {
			orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
			isReload = true;
		}
	} else if("freepass".equals(list.s("product_type"))) {
		//list.put("use_block", list.i("pay_price") == list.i("freepass_price"));
		list.put("use_block", true);

		//\uc0ad\uc81c-\uadf8\ub8f9\ud560\uc778\uae08\uc561\uac80\uc0ac
		if(list.b("freepass_disc_group_yn") && 0 < groupDisc) {
			int discGroupPrice = list.i("price") * groupDisc / 100; //CouponUserDao.getDiscountPrice() \uc640 \ub9de\ucda4
			if(discGroupPrice != list.i("disc_group_price")) {
				orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
				isReload = true;
			}
		} else if(0 < list.i("disc_group_price")) {
			orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
			isReload = true;
		}

		//\uc0ad\uc81c-\uae08\uc561\ud2c0\ub9bc
		if(list.i("unit_price") != list.i("freepass_price")) {
			orderItem.deleteCartItem(list.i("id"), list.i("coupon_user_id"));
			isReload = true;
		}
	}

}

//\ub9ac\ub85c\ub4dc
if(isReload) {
	m.jsAlert(_message.get("alert.order_item.canceled_by_change"));
	m.jsReplace("cart_list.jsp");
	return;
}


//\ud3fc\uc785\ub825
f.addElement("idx", null, "hname:'\ud56d\ubaa9', required:'Y'");

//\uce74\ud2b8\uc218\uc815
if(m.isPost()) {

	if("qty".equals(f.get("mode"))) {
		//\uae30\ubcf8\ud0a4
		int iid = f.getInt("order_item_id");
		if(0 == iid) { m.jsAlert(_message.get("alert.common.required_key")); return; }

		//\uc815\ubcf4
		DataSet info = orderItem.query(
			" SELECT a.*, b.book_price "
			+ " FROM " + orderItem.table + " a "
			+ " LEFT JOIN " + book.table + " b ON a.product_type = 'book' AND a.product_id = b.id AND b.status = 1 "
			//+ " WHERE a.id = " + iid + " AND a.user_id = " + userId + " AND a.order_id = -99 AND a.status = 10 "
			+ " WHERE a.id = " + iid + " AND a.user_id = " + userId + " AND a.status = 10 "
		);
		if(!info.next()) { m.jsAlert(_message.get("alert.common.nodata")); return; }

		//\uc218\uc815
		int qty = f.getInt("quantity");
		int unitPrice = info.i("book_price");
		if(qty < 1) qty = 1;
		if(qty > 1000) qty = 1000;
		orderItem.item("quantity", qty);
		orderItem.item("price", qty * unitPrice);
		orderItem.item("pay_price", qty * unitPrice);

		//\uadf8\ub8f9\ud560\uc778
		if(0 < info.i("disc_group_price") && 0 < groupDisc) {
			int discGroupPrice = qty * unitPrice * groupDisc / 100; //CouponUserDao.getDiscountPrice() \uc640 \ub9de\ucda4
			orderItem.item("disc_group_price", discGroupPrice);
			orderItem.item("pay_price", qty * (unitPrice - discGroupPrice));
		} else {
			orderItem.item("disc_group_price", 0);
			orderItem.item("pay_price", qty * unitPrice);
		}

		if(!orderItem.update("id = " + iid)) { m.jsAlert(_message.get("alert.common.error_modify")); return; }

		//\uc774\ub3d9
		m.jsReplace("cart_list.jsp?" + m.qs(), "parent");
		return;

	} else if(f.validate()) {
		String[] idx = m.reqArr("idx");

		//\uc81c\ud55c
		if(0 < orderItem.findCount("( status != 10 OR user_id != " + userId + " ) AND id IN (" + m.join(",", idx) + ")")) {
			m.jsError(_message.get("alert.order_item.permission_delete"));
			return;
		}

		//\uc0ad\uc81c
		int newOrderId = order.getSequence();
		orderItem.item("order_id", newOrderId);
		orderItem.item("status", 20);
		if(!orderItem.update("status = 10 AND user_id = " + userId + " AND id IN (" + m.join(",", idx) + ")")) {
			m.jsError(_message.get("alert.common.error_modify"));
			return;
		}

		//\uc138\uc158
		mSession.put("last_order_id", newOrderId);
		mSession.save();

		m.jsReplace("../order/payment.jsp?oek=" + order.getOrderEk(newOrderId, userId)/* + "&oid=" + m.encode(""+newOrderId)*/, "parent");
		return;
	}
}

//\ucd9c\ub825
p.setLayout(!isGoMobile ? ch : "mobile");
p.setBody("order.cart_list");
p.setVar("p_title", "\uc7a5\ubc14\uad6c\ub2c8");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id"));

p.setLoop("list", list);

p.setVar("move_dir", moveDir);
p.setVar("is_mobile", isMobile);
p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("order/cart_list.jsp"), -9137512430798580275L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("order/init.jsp"), 5573800058954498271L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 2912615399035486559L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
