/*
 * JSP generated by Resin-4.0.66 (built Mon, 29 Nov 2021 04:22:10 PST)
 */

package _jsp._sysop._book;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _book_0modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();
String tplRoot = Config.getDocRoot() + "/sysop/html";

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch (RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage()); return; }
catch (Exception ex) { m.errorLog("\uc81c\ud55c \uc6a9\ub7c9 \ucd08\uacfc - " + ex.getMessage()); return; }

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/Users/kyounghokim/IdeaProjects/MalgnLMS/public_html/html");

SiteDao Site = new SiteDao();
DataSet siteinfo = Site.getSiteInfo(request.getServerName(), "sysop");
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("sysop_status") || "".equals(siteinfo.s("doc_root"))) { m.jsReplace("/main/guide.jsp", "top"); return; }
//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));

//CSAP \uae30\uc900 \ub85c\uadf8\uc778 \uc2e4\ud328 \ud69f\uc218 5\ud68c
siteinfo.put("login_block_cnt", 5);
//CSAP \uae30\uc900 \ube44\ubc00\ubc88\ud638 \ub9cc\ub8cc\uc77c 90\uc77c
siteinfo.put("passwd_day", 90);
//\uc911\ubcf5\ub85c\uadf8\uc778 \ud5c8\uc6a9\ud558\uc9c0 \uc54a\uc74c
siteinfo.put("duplication_yn", "N");
siteinfo.put("dup_sysop_yn", "N");
//\uac8c\uc2dc\ud310 \ub9c8\uc2a4\ud0b9 \ud568
siteinfo.put("masking_yn", "Y");
//\uc124\ubb38 \ub9c8\uc2a4\ud0b9 \uc548\ud568
siteinfo.put("course_survey_masking_yn", "N");
//\uc138\uc158 \uc720\uc9c0\uc2dc\uac04 60\ubd84
siteinfo.put("sysop_session_hour", 60);
//B2b\uc0ac\uc6a9X
SiteConfig.put("join_b2b_yn", "N");

//String siteDomain = request.getScheme() + "://" + request.getServerName();
String siteDomain = "https://" + request.getServerName();
/*int port = request.getServerPort();
if(port != 80) siteDomain += ":" + port;*/
String webUrl = siteDomain + "/sysop";

String dataDir = siteinfo.s("doc_root") + "/data";
f.dataDir = dataDir;
m.dataDir = dataDir;
//m.dataUrl = Config.getDataUrl() + (!"/data".equals(Config.getDataUrl()) ? siteinfo.s("ftp_id") : "");
m.dataUrl = Config.getDataUrl();

boolean isDevServer = -1 < request.getServerName().indexOf("lms.malgn.co.kr");
siteinfo.put("logo_url", (!"/data".equals(Config.getDataUrl()) ? "" : siteDomain) + m.getUploadUrl(siteinfo.s("logo")));

//IP\ucc28\ub2e8
//String userIp = request.getRemoteAddr();
String userIp = m.getRemoteAddr(); //Lb \uc0ac\uc6a9
if(userIp.contains(",")) {
	String[] userIpArr = m.split(",", userIp);
	userIp = userIpArr[0].trim();
}
boolean isMalgnOffice = "1.212.252.90|3.35.211.181|52.79.184.225|127.0.0.1".contains(userIp);
if(!"".equals(siteinfo.s("allow_ip_sysop")) && !isMalgnOffice && !Site.checkIP(userIp, siteinfo.s("allow_ip_sysop"))) {
	m.redirect("/");
	return;
}

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
//String sysLocale = "default";
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

//\uae30\ubcf8 \ud68c\uc6d0\uc815\ubcf4
int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
String manageCourses = "";
String userSessionId = "";
String pagreeDate = "";
boolean isUserMaster = false;
String winTitle = "[\uad00\ub9ac\uc790] " + siteinfo.s("site_nm");
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
String surl = request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : "");
int sysViewerVersion = Math.max(SiteConfig.i("sys_viewer_version"), 1);
boolean sysViewerComment = "Y".equals(SiteConfig.s("sys_viewer_comment_yn"));
final int sysExcelCnt = 20000;

SessionDao mSession = new SessionDao(request, response);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "MLMSKEY2014" + siteId + "7";
if(0 < siteinfo.i("sysop_session_hour")) auth.setValidTime(siteinfo.i("sysop_session_hour") * 60);
if(auth.isValid()) {
	userId = m.parseInt(auth.getString("ID"));
	loginId = auth.getString("LOGINID");
	userName = auth.getString("NAME");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	manageCourses = auth.getString("MANAGE_COURSES");
	userSessionId = userSessionId = auth.getString("SESSIONID");
	pagreeDate = auth.getString("PAGREE_DATE");
	isUserMaster = "Y".equals(auth.getString("IS_USER_MASTER"));

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	if(request.getRequestURI().indexOf("/main/auth2.jsp") == -1
		//&& "Y".equals(siteinfo.s("auth2_yn"))
		&& !"Y".equals(auth.getString("AUTH2_YN"))
		//&& !"".equals(siteinfo.s("auth2_type"))
		//&& !"malgn".equals(loginId)
		&& request.getRequestURI().indexOf("/main/otpkey_register.jsp") == -1
		&& request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1
		&& request.getRequestURI().indexOf("/main/modify_passwd.jsp") == -1
	) {
		m.jsReplace("/sysop/main/auth2.jsp?returl=" + m.rs("returl", "/sysop/index.jsp"), "top");
		return;
	}

	//\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd \uc548\ud568
	if(
		"N".equals(auth.getString("MODIFY_PASSWD"))
		&& -1 == request.getRequestURI().indexOf("/sysop/main/logout.jsp")
		&& -1 == request.getRequestURI().indexOf("/sysop/main/login.jsp")
		&& -1 == request.getRequestURI().indexOf("/main/modify_passwd.jsp")
	) {
		m.jsReplace("/sysop/main/logout.jsp");
		return;
	}

	mSession.put("id", userSessionId);
	mSession.save();

} else {
	if(request.getRequestURI().indexOf("/main/login.jsp") == -1
		&& request.getRequestURI().indexOf("/vod/upload.jsp") == -1
		&& request.getRequestURI().indexOf("/main/slogin.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_template.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_maildir.jsp") == -1
		&& (request.getRequestURI().indexOf("/user/sleep_insert.jsp") == -1 || !"log".equals(m.rs("after")))
	) {
		m.jsReplace(auth.loginURL, "top");
		return;
	}
}

MenuDao Menu = new MenuDao(p, siteId, "default");
SiteMenuDao SiteMenu = new SiteMenuDao();

boolean superBlock = "S".equals(userKind);
boolean adminBlock = "S".equals(userKind) || "A".equals(userKind);
boolean courseManagerBlock = "C".equals(userKind);
boolean deptManagerBlock = "D".equals(userKind);

//boolean isAuthCrm = superBlock || (-1 < siteinfo.s("auth_crm").indexOf("|" + userKind + "|"));
boolean isAuthCrm = superBlock || Menu.accessible(-999, userId, userKind, false);

//\ub85c\uadf8\uc544\uc6c3-\uacfc\uc815\uc6b4\uc601\uc790
if(courseManagerBlock && "".equals(manageCourses) && request.getRequestURI().indexOf("/main/logout.jsp") == -1) {
	m.jsAlert("\ub2f4\ub2f9\ud55c \uacfc\uc815\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\\n \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc138\uc694.");
	m.jsReplace("/sysop/main/logout.jsp", "top");
	return;
}

//\ub9e4\ub274\uc5bc
ManualDao Manual = new ManualDao();
int ManualId = Menu.getOneInt("SELECT manual_id FROM " + Menu.table + " WHERE link = '" + m.replace(request.getRequestURI(), "/sysop", "..") + "'");
if(0 < ManualId) {
	int ManualStatus = Manual.getOneInt("SELECT status FROM " + Manual.table + " WHERE id = " + ManualId);
	if(0 < ManualStatus) p.setVar("SYS_MENU_MANUAL_ID", ManualId);
}

p.setVar("WEB_URL", webUrl);
p.setVar("FRONT_URL", siteDomain);
p.setVar("SYS_TITLE", winTitle);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("IS_AUTH_CRM", isAuthCrm);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
//p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");
p.setVar("SYS_COMMON_CDN", "");
p.setVar("SYS_VIEWER_VERSION", sysViewerVersion);
p.setVar("SYS_VIEWER_COMMENT", sysViewerComment);

p.setVar("user_master_block", isUserMaster || isMalgnOffice);
p.setVar("malgn_office_block", isMalgnOffice);
p.setVar("super_block", superBlock);
p.setVar("admin_block", adminBlock);
p.setVar("course_manager_block", courseManagerBlock);
p.setVar("dept_manager_block", deptManagerBlock);
p.setVar("SYS_URL", surl);

//boolean isBlindUser = !sysToday.equals(pagreeDate);
//p.setVar("SYS_BLINDUSER", isBlindUser);

//\uac1c\uc778\uc815\ubcf4\ucc98\ub9ac \uc218\uc815 - 2024.03.25
boolean isBlindUser = !"Y".equals(m.getCookie("PCONFIRM_YN"));
p.setVar("SYS_BLINDUSER", isBlindUser);
p.setVar("PCONFIRM_YN", m.getCookie("PCONFIRM_YN"));
String inquiryPurpose = m.getCookie("INQUIRYPURPOSE");

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
UserSession.setType("sysop");
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && "N".equals(siteinfo.s("dup_sysop_yn")) && ("".equals(userSessionId) || userSessionId == null || !UserSession.isValid(userSessionId, userId))) {
	if(request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1) {
		m.jsAlert("\uc138\uc158\uc774 \ub9cc\ub8cc\ub418\uc5c8\uac70\ub098 \uc911\ubcf5 \ub85c\uadf8\uc778\uc774 \ub418\uc5b4 \uc790\ub3d9\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ub429\ub2c8\ub2e4.");
		m.jsReplace("/sysop/main/logout.jsp?mode=session", "top");
		return;
	}
}

InfoLogDao _log = new InfoLogDao(siteId); _log.setItems(userId, "B", surl, userIp);
InfoUserDao _logUser = new InfoUserDao(siteId);


    

String ch = "sysop";


    

//\uc811\uadfc\uad8c\ud55c
if(!Menu.accessible(38, userId, userKind)) { m.jsError("\uc811\uadfc \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uae30\ubcf8\ud0a4
int id = m.ri("id");
if(id == 0) { m.jsError("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
BookDao book = new BookDao();
BookTargetDao bookTarget = new BookTargetDao();
BookRelateDao bookRelate = new BookRelateDao();
BookPackageDao bookPackage = new BookPackageDao();
UserDao user = new UserDao();
LessonDao lesson = new LessonDao();
CourseBookDao courseBook = new CourseBookDao();
LmCategoryDao category = new LmCategoryDao("book");
GroupDao group = new GroupDao();

//\uc815\ubcf4
DataSet info = book.query(
	"SELECT a.*, g.category_nm category_nm, u.user_nm manager_name, l.lesson_nm "
	+ " FROM " + book.table + " a "
	+ " LEFT JOIN " + category.table + " g ON a.category_id = g.id "
	+ " LEFT JOIN " + user.table + " u ON a.manager_id = u.id "
	+ " LEFT JOIN " + lesson.table + " l ON a.lesson_id = l.id "
	+ " WHERE a.id = ? AND a.status != -1 AND a.site_id = ?"
,
	new Object[] {new Integer(id), new Integer(siteId)}
);
if(!info.next()) { m.jsError("\ud574\ub2f9 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }
info.put("pub_date_conv", m.time("yyyy-MM-dd", info.s("pub_date")));

//\ubcc0\uc218
boolean isPackage = "P".equals(info.s("book_type"));

//\ud30c\uc77c\uc0ad\uc81c
if("fdel".equals(m.rs("mode"))) {
	if(!"".equals(info.s("book_img"))) {
		book.item("book_img", "");
		if(!book.update("id = " + id)) { m.jsAlert("\ud30c\uc77c\uc744 \uc0ad\uc81c\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
		m.delFileRoot(m.getUploadPath(info.s("book_img")));
	}
	return;
}

//\ud3fc\uccb4\ud06c
f.addElement("category_id", info.s("category_id"), "hname:'\uce74\ud14c\uace0\ub9ac\uba85', required:'Y'");
f.addElement("book_nm", info.s("book_nm"), "hname:'\ub3c4\uc11c\uba85', required:'Y'");
f.addElement("book_img_url", info.s("book_img_url"), "hname:'\ub3c4\uc11c\uc774\ubbf8\uc9c0 URL'");
f.addElement("book_img", null, "hname:'\ub3c4\uc11c\uc774\ubbf8\uc9c0', allow:'jpg|gif|png'");
f.addElement("book_info", info.s("book_info"), "hname:'\ub3c4\uc11c\uc815\ubcf4'");
f.addElement("taxfree_yn", info.s("taxfree_yn"), "hname:'\ubd80\uac00\uc138\uba74\uc138\uc5ec\ubd80', required:'Y'");
f.addElement("disc_group_yn", info.s("disc_group_yn"), "hname:'\uadf8\ub8f9\ud560\uc778\uc801\uc6a9\uc5ec\ubd80'");
f.addElement("list_price", info.i("list_price"), "hname:'\uc815\uac00', option:'number'");
f.addElement("book_price", info.i("book_price"), "hname:'\ud310\ub9e4\uac00', option:'number', required:'Y'");
f.addElement("delivery_type", info.s("delivery_type"), "hname:'\ubc30\uc1a1\ub8cc \ud0c0\uc785'");
f.addElement("delivery_price", info.i("delivery_price"), "hname:'\ubc30\uc1a1\ub8cc', option:'number'");
f.addElement("author", info.s("author"), "hname:'\uc800\uc790'");
f.addElement("publisher", info.s("publisher"), "hname:'\ucd9c\ud310\uc0ac'");
f.addElement("isbn", info.s("isbn"), "hname:'ISBN'");
f.addElement("pub_date", info.s("pub_date_conv"), "hname:'\ucd9c\uac04\uc77c'");
f.addElement("link", info.s("link"), "hname:'\ub3c4\uc11c\ub9c1\ud06c'");
f.addElement("lesson_id", info.s("lesson_id"), "hname:'e-Book'");
f.addElement("lesson_nm", info.s("lesson_nm"), "hname:'e-Book'");
f.addElement("rental_day", info.i("rental_day"), "hname:'\ub300\uc5ec\uc77c', option:'number'");
f.addElement("summary", null, "hname:'\uac04\ub7b5\uc18c\uac1c'");
f.addElement("outline", null, "hname:'\ub3c4\uc11c\uc18c\uac1c', allowiframe:'Y', allowhtml:'Y'");
f.addElement("introduce", null, "hname:'\uc800\uc790\uc18c\uac1c', allowiframe:'Y', allowhtml:'Y'");
f.addElement("contents", null, "hname:'\ubaa9\ucc28', allowiframe:'Y', allowhtml:'Y'");
f.addElement("etc1", info.s("etc1"), "hname:'\uae30\ud0c01'");
f.addElement("etc2", info.s("etc2"), "hname:'\uae30\ud0c02'");
f.addElement("target_yn", info.s("target_yn"), "hname:'\uad6c\ub9e4\ub300\uc0c1\uc790 \uc0ac\uc6a9\uc5ec\ubd80', required:'Y'");
f.addElement("recomm_yn", info.s("recomm_yn"), "hname:'\ucd94\ucc9c\uacfc\uc815'");
f.addElement("manager_id", info.s("manager_id"), "hname:'\ub2f4\ub2f9\uc790'");
f.addElement("manager_name", info.s("manager_name"), "hname:'\ub2f4\ub2f9\uc790'");
f.addElement("sale_yn", info.s("sale_yn"), "hname:'\ud310\ub9e4\uc5ec\ubd80'");
f.addElement("display_yn", info.s("display_yn"), "hname:'\ub178\ucd9c\uc5ec\ubd80'");
f.addElement("status", info.i("status"), "hname:'\uc0c1\ud0dc', option:'number'");

//\uc218\uc815
if(m.isPost() && f.validate()) {

	//\uc81c\ud55c
	if("E".equals(info.s("book_type")) && "".equals(f.get("lesson_id"))) {
		m.jsAlert("\uc804\uc790\ucc45\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694.");
		return;
	}

	//\uc81c\ud55c-\ud328\ud0a4\uc9c0
	if("P".equals(info.s("book_type")) && "Y".equals(f.get("display_yn")) && 0 >= bookPackage.findCount("package_id = " + id)) {
		m.jsAlert("\ud574\ub2f9 \ud328\ud0a4\uc9c0\uc5d0 \ub4f1\ub85d\ub41c \ub3c4\uc11c\uac00 \uc5c6\uc5b4 \uc0c1\ud0dc\ub97c \ubcc0\uacbd\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.");
		return;
	}

	//\uc81c\ud55c-\uc774\ubbf8\uc9c0URI\ubc0f\uc6a9\ub7c9
	String outline = f.get("outline");
	String introduce = f.get("introduce");
	String contents = f.get("contents");
	int bytesOutline = outline.replace("\r\n", "\n").getBytes("UTF-8").length;
	int bytesIntroduce = introduce.replace("\r\n", "\n").getBytes("UTF-8").length;
	int bytesContents = contents.replace("\r\n", "\n").getBytes("UTF-8").length;
	if(-1 < outline.indexOf("<img") && -1 < outline.indexOf("data:image/") && -1 < outline.indexOf("base64")) { m.jsAlert("\ub3c4\uc11c\uc18c\uac1c \uc774\ubbf8\uc9c0\ub294 \ucca8\ubd80\ud30c\uc77c \uae30\ub2a5\uc73c\ub85c \uc5c5\ub85c\ub4dc \ud574 \uc8fc\uc138\uc694."); return; }
	if(-1 < introduce.indexOf("<img") && -1 < introduce.indexOf("data:image/") && -1 < introduce.indexOf("base64")) { m.jsAlert("\uc800\uc790\uc18c\uac1c \uc774\ubbf8\uc9c0\ub294 \ucca8\ubd80\ud30c\uc77c \uae30\ub2a5\uc73c\ub85c \uc5c5\ub85c\ub4dc \ud574 \uc8fc\uc138\uc694."); return; }
	if(-1 < contents.indexOf("<img") && -1 < contents.indexOf("data:image/") && -1 < contents.indexOf("base64")) { m.jsAlert("\ubaa9\ucc28 \uc774\ubbf8\uc9c0\ub294 \ucca8\ubd80\ud30c\uc77c \uae30\ub2a5\uc73c\ub85c \uc5c5\ub85c\ub4dc \ud574 \uc8fc\uc138\uc694."); return; }
	if(60000 < bytesOutline) { m.jsAlert("\ub3c4\uc11c\uc18c\uac1c \ub0b4\uc6a9\uc740 60000\ubc14\uc774\ud2b8\ub97c \ucd08\uacfc\ud574 \uc791\uc131\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\\n(\ud604\uc7ac " + bytesOutline + "\ubc14\uc774\ud2b8)"); return; }
	if(60000 < bytesIntroduce) { m.jsAlert("\uc800\uc790\uc18c\uac1c \ub0b4\uc6a9\uc740 60000\ubc14\uc774\ud2b8\ub97c \ucd08\uacfc\ud574 \uc791\uc131\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\\n(\ud604\uc7ac " + bytesIntroduce + "\ubc14\uc774\ud2b8)"); return; }
	if(60000 < bytesContents) { m.jsAlert("\ubaa9\ucc28 \ub0b4\uc6a9\uc740 60000\ubc14\uc774\ud2b8\ub97c \ucd08\uacfc\ud574 \uc791\uc131\ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\\n(\ud604\uc7ac " + bytesContents + "\ubc14\uc774\ud2b8)"); return; }

	book.item("category_id", f.get("category_id"));
	book.item("book_nm", f.get("book_nm"));
	if(f.getFileName("book_img") != null) {
		File f1 = f.saveFile("book_img");
		if(f1 != null) {
			book.item("book_img", f.getFileName("book_img"));
			if(!"".equals(info.s("book_img"))) m.delFileRoot(m.getUploadPath(info.s("book_img")));
			
			//\ub9ac\uc0ac\uc774\uc988
			try {
				String imgPath = dataDir + "/file/" + f1.getName();
				String cmd = "convert -resize 1000x " + imgPath + " " + imgPath;
				Runtime.getRuntime().exec(cmd);
			}
			catch(RuntimeException re) { m.errorLog("RuntimeException : " + re.getMessage(), re); return; }
			catch(Exception e) { m.errorLog("Exception : " + e.getMessage(), e); return; }
		}
	}
	book.item("book_img_url", f.get("book_img_url"));
	book.item("taxfree_yn", f.get("taxfree_yn"));
	book.item("disc_group_yn", f.get("disc_group_yn", "Y"));
	book.item("list_price", f.getInt("list_price"));
	book.item("book_price", f.getInt("book_price"));
	book.item("book_info", f.get("book_info"));
	book.item("summary", f.get("summary"));
	book.item("isbn", f.get("isbn"));
	book.item("delivery_type", f.get("delivery_type"));
	book.item("delivery_price", f.getInt("delivery_price", 0));
	book.item("author", f.get("author"));
	book.item("publisher", f.get("publisher"));
	book.item("link", f.get("link"));
	book.item("lesson_id", f.getInt("lesson_id"));
	book.item("rental_day", f.getInt("rental_day"));
	book.item("outline", outline);
	book.item("introduce", introduce);
	book.item("contents", contents);
	book.item("manager_id", f.getInt("manager_id"));
	book.item("recomm_yn", f.get("recomm_yn", "N"));
	book.item("target_yn", f.get("target_yn", "N"));
	book.item("sale_yn", f.get("sale_yn", "N"));
	book.item("display_yn", f.get("display_yn", "N"));
	book.item("pub_date", "".equals(f.get("pub_date")) ? "" : m.time("yyyyMMdd", f.get("pub_date")));
	book.item("status", f.get("status", "0"));
	book.item("etc1", f.get("etc1"));
	book.item("etc2", f.get("etc2"));

	//\ub3c4\uc11c
	if(-1 != bookRelate.execute("DELETE FROM " + bookRelate.table + " WHERE book_id = " + id + "")) {
		if(null != f.getArr("relate_id")) {
			bookRelate.item("book_id", id);
			bookRelate.item("site_id", siteId);
			for(int i = 0; i < f.getArr("relate_id").length; i++) {
				bookRelate.item("relate_id", f.getArr("relate_id")[i]);
				if(!bookRelate.insert()) { }
			}
		}
	}

	//\uadf8\ub8f9
	if(-1 != bookTarget.execute("DELETE FROM " + bookTarget.table + " WHERE book_id = " + id + "")) {
		if(null != f.getArr("group_id")) {
			bookTarget.item("book_id", id);
			bookTarget.item("site_id", siteId);
			for(int i = 0; i < f.getArr("group_id").length; i++) {
				bookTarget.item("group_id", f.getArr("group_id")[i]);
				if(!bookTarget.insert()) { }
			}
		}
	}

	if(!book.update("id = " + id + "")) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	m.jsReplace("book_list.jsp?" + m.qs("id"), "parent");
	return;
}

info.put("book_type_" + info.s("book_type"), true);
info.put("book_type_conv", m.getItem(info.s("book_type"), book.packageTypes));
info.put("book_img_conv", m.encode(info.s("book_img")));
info.put("book_img_isrc", siteDomain + m.getUploadUrl(info.s("book_img")));
info.put("book_img_ek", m.encrypt(info.s("book_img") + m.time("yyyyMMdd")));
info.put("reg_date_conv", m.time("yyyy.MM.dd HH:mm:ss", info.s("reg_date")));

//\ubaa9\ub85d-\ub300\uc0c1\uc790
DataSet targets = bookTarget.query(
	"SELECT a.*, g.group_nm "
	+ " FROM " + bookTarget.table + " a "
	+ " INNER JOIN " + group.table + " g ON a.group_id = g.id AND g.site_id = " + siteId + " "
	+ " WHERE a.book_id = " + id + ""
);

//\ubaa9\ub85d-\uad00\ub828\ucc45
DataSet rbooks = bookRelate.query(
	"SELECT b.id relate_id, b.book_nm relate_nm "
	+ " FROM " + bookRelate.table + " a "
	+ " INNER JOIN " + book.table + " b ON a.relate_id = b.id "
	+ " WHERE a.book_id = " + id
);
/*
while(rbooks.next()) {
	rbooks.put("book_nm_conv", m.cutString(rbooks.s("book_nm"), 40));
	rbooks.put("status_conv", m.getItem(rbooks.s("status"), book.statusList));
	rbooks.put("display_conv", rbooks.b("display_yn") ? "\uc815\uc0c1" : "\uc228\uae40");
	rbooks.put("book_type_conv", m.getItem(rbooks.s("book_type"), book.packageTypes));
	//rbooks.put("onoff_type_conv", m.getItem(rbooks.s("onoff_type"), course.onoffTypes));

	//rbooks.put("alltimes_block", "A".equals(rbooks.s("course_type")));
	//rbooks.put("request_sdate_conv", m.time("yyyy.MM.dd", rbooks.s("request_sdate")));
	//rbooks.put("request_edate_conv", m.time("yyyy.MM.dd", rbooks.s("request_edate")));
	//rbooks.put("study_sdate_conv", m.time("yyyy.MM.dd", rbooks.s("study_sdate")));
	//rbooks.put("study_edate_conv", m.time("yyyy.MM.dd", rbooks.s("study_edate")));
}
*/

//\ucd9c\ub825
p.setBody("book.book_insert");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id,mode"));
p.setVar("form_script", f.getScript());

p.setVar("modify", true);
p.setVar(info);

p.setLoop("targets", targets);
p.setLoop("rbooks", rbooks);

p.setLoop("types", m.arr2loop(book.types));
p.setLoop("status_list", m.arr2loop(book.statusList));
p.setLoop("taxfree_yn", m.arr2loop(book.taxfreeYn));
p.setLoop("display_yn", m.arr2loop(book.displayYn));
p.setLoop("delivery_types", m.arr2loop(book.deliveryTypes));
p.setLoop("managers", user.getManagers(siteId));
p.setLoop("courses", courseBook.getCourses(id));
p.setLoop("categories", category.getList(siteId));

p.setVar("tab_modify", "current");
p.setVar("package_block", isPackage);
p.setVar("course_cnt", courseBook.getCourseCount(id));
p.display();


  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -243257770274170091L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/book/book_modify.jsp"), 6318026939142014588L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/book/init.jsp"), -7162420496711387185L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 9197471702019162279L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
}
